### ISSUE TITLE
1.3.1: FAIL: tst-pam_faillock

### ISSUE THREAD

**Issue by kloczek** [linux-pam/linux-pam#101]
I just tried to execute check target from current Fedora pam package.

<pre><font color="#CD0000">FAIL</font>: tst-pam_faillock
<font color="#CD0000">============================================================================</font>
<font color="#CD0000">Testsuite summary for Linux-PAM 1.3.1</font>
<font color="#CD0000">============================================================================</font>
<b># TOTAL: 1</b>
# PASS:  0
# SKIP:  0
# XFAIL: 0
<font color="#CD0000"># FAIL:  1</font>
# XPASS: 0
# ERROR: 0
<font color="#CD0000">============================================================================</font>
<font color="#CD0000">See modules/pam_faillock/test-suite.log</font>
<font color="#CD0000">============================================================================</font>
</pre>

<pre>[tkloczko@domek tests]$ cat tst-pam_fail_delay.log 
PASS tst-pam_fail_delay (exit status: 0)
[tkloczko@domek tests]$ ./tst-pam_fail_delay --lt-debug  cd &quot;`printf &apos;%b&apos; &apos;\0057home\0057tkloczko\0057rpmbuild\0057SPECS&apos;`&quot;
tst-pam_fail_delay:tst-pam_fail_delay:93: libtool wrapper (GNU libtool) 2.4.6
tst-pam_fail_delay:tst-pam_fail_delay:114: newargv[0]: /home/tkloczko/rpmbuild/BUILD/Linux-PAM-1.3.1/tests/.libs/lt-tst-pam_fail_delay
tst-pam_fail_delay:tst-pam_fail_delay:104: newargv[1]: cd
tst-pam_fail_delay:tst-pam_fail_delay:104: newargv[2]: /home/tkloczko/rpmbuild/SPECS
</pre>

**Comment by t8m** [comment]
pam_faillock is not upstream PAM module yet.
