### ISSUE TITLE
Extracting crypt_make_salt for use in other programs/modules

### ISSUE THREAD

**Issue by Jnchi** [linux-pam/linux-pam#110]
I am using `crypt_make_salt` from `passverify.c` in an NSS module, and I have a [patch](https://github.com/CyberNinjas/libnss_aad/blob/master/.patches/0001-Remove-static-keyword-from-crypt_make_salt.patch) that simply takes the static keyword off of the function so that I can include it.

Are there any other libraries for creating passwords and hashes for POSIX systems?
Otherwise, is it possible to expose this functionality in linux-pam for external use such as this?

**Comment by t8m** [comment]
Please look at libxcrypt. https://github.com/besser82/libxcrypt

**Comment by Jnchi** [comment]
Thanks!
