### ISSUE TITLE
pam_unix failed for non-root even with correct credentials

### ISSUE THREAD

**Issue by swanandt** [linux-pam/linux-pam#112]
Hi 

We are using LIBPAM 1.3.0  and we are getting strange issues.  
The process is running as non-root and trying to execute a PAM stack with library calls via libpam.

Even with correct username password we are getting following error in pam_unix.
May 09 14:53:55 mn-0 unix_chkpwd[13827]: check pass; user unknown
May 09 14:53:55 mn-0 unix_chkpwd[13827]: password check failed for user (robot)

The "s" bit is set for unix_chkpwd helper binary. 
 ls -lrt /usr/sbin/unix_chkpwd
-rwsr-xr-x 1 root root 36200 Mar 17  2018 /usr/sbin/unix_chkpwd

& /etc/shadow and /etc/passwd has following permission.
-rw-r--r-- 1 root root 4457 May  7 10:54 /etc/passwd
---------- 1 root root 2619 May  7 10:54 /etc/shadow  [ Security Implications can't change it ]

We try to validate same user using 
"echo -n -e 'correct password\0' | /sbin/unix_chkpwd user nonull 

and it pass successfully 

Then we try to unset the "s" bit for unix_chkpwd and try and then we are getting the same error even for correct password.

So our analysis so far:

pam_unix module when used with non-root process [ using libpam ] is somehow unsetting the "s" of helper Binary unix_chkpwd.
and because of that non-root process can not perform authentication. Our non-root process is for "external interface"
and as part of security hardening it is must for us to run as non-root and authenticate users login to our Cluster.

We have started looking at pam_unix module code but not able to identify when is it doing so

Q: Can you identify why is it doing so ?
Q: As part of PAM module testing does it have some scenario where non-root process can perform the pam_unix based authentication?
Q: Does PAM support authentication for non-root process ?

We also have written a small binary program [ as helper is not supposed to be used ] and it works perfectly fine with "s" bit set
and also unix_chkpwd also works fine but when it is invoked from pam_unix which is used by non-root process somehow those errors are coming
which are able to reproduce by un-setting the "s" bit of helper binary so we are suspecting it.

If we set the "s" bit for our non-root process it works fine but that is not what is intended for us.

Please provide your suggestion on how to fix it.

Thanks
Swan

**Comment by t8m** [comment]
This is by design and won't be changed. If you want to authenticate other users by a non-root PAM process you have to change your /etc/shadow permissions to allow reading it by the non-root PAM process. For example have the non-root PAM process run with some special group and make the /etc/shadow readable by this group. The unix-chkpwd is setuid to only allow reauthentication of the user that is calling it such as in case of the screensaver screen lock.

**Comment by swanandt** [comment]
Hi 

Thanks for you comments !!!
But can you also high-light the code part of pam_unix module which is doing this check,
where it explicitly unset this "s" bit of unix_chkpwd.

Br
Swan

**Comment by t8m** [comment]
It does not unset anything. unix_chkpwd checks, when it is run with real uid != 0, whether the authenticated user is the user with the real uid which runs it. If not, it will reject the authentication attempt.

**Comment by t8m** [comment]
Or rather to be more precise, the unix_chkpwd will change its effective user to the real uid and thus if the shadow file is not readable for the process, the authentication attempt will fail.

**Comment by swanandt** [comment]
Many Thanks for timely response !!! Much Appreciated !! 

We already have small authentication helper binary but we would like to use LIBPAM rather, we will try to address it at our end.
