### ISSUE TITLE
conditional behaviour with pam_exec and PAM_TYPE not functional

### ISSUE THREAD

**Issue by helge42** [linux-pam/linux-pam#116]
Hi,

I want to implement conditions for PAM_TYPE open_session and close_session. With this I can trigger different actions at different times for login and logout. This was suggested [here](https://github.com/linux-pam/linux-pam/issues/36#issuecomment-341839865) 

I have a script which tests for the variable PAM_TYPE and give appropriate exit codes: exit 0 for success and exit 1 otherwise.

But I get weird problems with the assembly; pam_exec don't get the right exit codes from the script. 

Here is my implementation for testing:

In `/etc/pam.d/common-session` I have added:

    session [success=ignore default=1] pam_exec.so debug seteuid /usr/sbin/test.sh logout
    session optional        pam_exec.so debug log=/tmp/test_pam.txt /bin/echo "logout reached"
    session [success=1 default=ignore] pam_exec.so debug seteuid /usr/sbin/test.sh logout
    session optional        pam_exec.so  debug log=/tmp/test_pam.txt /bin/echo "login reached"

The script `/usr/sbin/test.sh` is

    #!/bin/bash
    # some actions
    # invocted by pam_exec.so
    
    echo $PAM_TYPE
    case $1 in
    logout)
      if [ $PAM_TYPE == "close_session" ]; then echo $PAM_TYPE; exit 0; else exit 1; fi
      ;;
    esac

When I make a su to an user and immediately a logout I get in the log-file

    $ cat /tmp/test_pam.txt 
    *** Mon Jun  3 12:14:07 2019
    "login reached"
    *** Mon Jun  3 12:15:00 2019
    "login reached"

This behavior is weird. The last line must be _logout reached_.  
So Pam takes every time the condition to false. But for testing I have placed  `echo $PAM_TYPE;` in the true-condition and this echo is displayed in the terminal by logout. So the if Statement leads to _true_ with `exit 0` but pam_exec takes it as false.

Has someone an idea what is going wrong?

Thanks in advance,

Helge 

PS: I use debian stretch and ubuntu 18.04

**Comment by t8m** [comment]
You cannot depend on jumps in PAM stack in the close_session calls. The pam module stack is "frozen" in the open_session and identical modules in the same order are invoked in the close_session call.

**Comment by helge42** [comment]
Thanks for the clarification. So my approach is not possible :-(

**Comment by t8m** [comment]
But why don't you use the type=<type> option of pam_exec?
session optional        pam_exec.so type=close_session log=/tmp/test_pam.txt /bin/echo "logout reached"
session optional        pam_exec.so type=open_session log=/tmp/test_pam.txt /bin/echo "login reached"

**Comment by shareandenjoy** [comment]
I am working on the referenced issue https://github.com/linux-pam/linux-pam/issues/36#issuecomment-341839865 . I have some calls of pam_mount and I want to change the actual positions of the call depending of open_session and close_session.

It's similar to the systemd problem. To solve this you mentioned to use jumps. But as you explained this is not possible.

Are there other suggestions?

**Comment by helge42** [comment]
I am working on the referenced [issue](https://github.com/linux-pam/linux-pam/issues/36#issuecomment-341741677)  . I have some calls of pam_mount and I want to change the actual positions of the call depending of open_session and close_session.

It's similar to the systemd problem. To solve this you mentioned to use jumps. But as you explained this is not possible.

Are there other suggestions?

**Comment by t8m** [comment]
No, I did not say that #36 can be solved by using jumps. I just said that when jumps are used the proposal of the reporter of the issue does not make sense.

What I proposed instead here https://github.com/linux-pam/linux-pam/issues/36#issuecomment-341656293 actually makes sense thanks to the stack freezing with one exception - the situation where the pam_open_session was not called by the application. But in that case the pam_close_session() should probably just return PAM_IGNORE and not call any module.

But anyway this would be a major behavior change in PAM and it would warrant something like PAM-2.0 release.

Other way that might be less intrusive would be an introduction of another module types in the configuration - session_open and session_close types where session would be regarded as both session_open and session_close. All the rules for session stack handling would be kept but the module calls for the modules which have only either session_open or session_close would be replaced by simple PAM_IGNORE return in the other call.

**Comment by t8m** [comment]
@ldv-alt @thkukuk What do you think about the previous comment, would it be worth implementing?

**Comment by thkukuk** [comment]
It makes sense to separate session open and close, that's a long standing problem.

**Comment by t8m** [comment]
My proposal here would be backwards-compatible and would not require full separation of session open and close.

Of course other options are possible but they would always change the behavior for existing configurations in one way or another. I do not know if we want to do this although the solutions could have a nicer design.

The options we have currently are:

a) session_open session_close types added as in the comment above, stack freezing kept

b) no new types but stack is not frozen between open/close

c) stack is frozen but the modules in the frozen stack are called in reverse order in close_session call. If there is no open_session call close_session simply returns PAM_SUCCESS.

Both b) and c) are changing behavior, of course the c) change is much bigger however it also makes logically some sense. Also c) (or b)) could be combined with a).

**Comment by ldv-alt** [comment]
I'd prefer a backwards-compatible approach which seems to be a).

**Comment by thkukuk** [comment]
I'm against the "reverse call" option, this makes some things pretty difficult. I would also vote for a).

**Comment by t8m** [comment]
OK, I'll try to prepare PR for a) when I find time.
