### ISSUE TITLE
"illegal module type:" due to long variable contents

### ISSUE THREAD

**Issue by HTlocal** [linux-pam/linux-pam#117]
Hello,

I am getting an error for my pam_tty_audit file.

Jun 24 09:24:33 testing-api-05 sshd[128658]: PAM (sshd) illegal module type: ***,*******************,***********,***************,************,************,******************,****************,***************,**************,**************,***********,***************
The stars are usernames, I preserved length while masking.

Turns out that the first 3 letters in the error are just the last part of a name, so I counted after how many chars in the file it cuts off and turns out it's 1024.
So I was thinking maybe it was related to https://github.com/linux-pam/linux-pam/issues/31 but there it was populated using an env variable. In my case it's deployed via ansible and the file is complete anyway. nothing cut off.

So it seems that either SSH or PAM are only reading the file up to the 1024th char and throws an error for the rest.

Any idea how I could fix this? Any help would be appreciated.

Cheers,
Jay.

**Comment by t8m** [comment]
I think you could place multiple pam_tty_audit calls, each for different set of users, so the lines will not be longer than 1024 characters.
Fixing this would require changing libpam.

**Comment by HTlocal** [comment]
I just see the problem that the disable=* will negate what's already there

Could one maybe work with user groups instead of names? I haven't found anything in the documentation though.

**Comment by t8m** [comment]
pam_tty_audit does not require the disable=* option.
Matching for groups is unfortunately not supported.
There is only support for uids and uid ranges.
The missing support for groups could be workarounded via using pam_succeed_if to jump over the pam_tty_audit for non-matching groups.

**Comment by HTlocal** [comment]
Hi t8m,
thanks I'll try the stacking approach without disable=* in the second file.
