### ISSUE TITLE
pam_unix failed to update the expired password 

### ISSUE THREAD

**Issue by adityaK18** [linux-pam/linux-pam#123]
The login utility failed to update the expired password as pam_unix not asking the user to enter the new password. 

"~#login
login: user
Password:****
You are required to change your password immediately (root enforced)
Changing password for user.
Password unchanged
Password unchanged
Password unchanged
~ # 

The login configuration in pam.d is 

auth       required     /lib/security/pam_nologin.so
auth       sufficient   /lib/security/pam_unix.so try_first_pass debug
auth       sufficient   /lib/security/pam_ipmi.so
account    sufficient   /lib/security/pam_unix.so debug
account    sufficient   /lib/security/pam_ipmi.so
password   sufficient   /lib/security/pam_unix.so debug
password   sufficient   /lib/security/pam_ipmi.so debug
session    required     /lib/security/pam_unix.so debug
session    sufficient   /lib/security/pam_ipmi.so
auth       sufficient   /lib/security/pam_custom_ldap.so use_first_pass
account    sufficient   /lib/security/pam_custom_ldap.so
password   sufficient   /lib/security/pam_custom_ldap.so
session    sufficient   /lib/security/pam_custom_ldap.so
auth       sufficient   /lib/security/pam_custom_ad.so use_first_pass
account    sufficient   /lib/security/pam_custom_ad.so
password   sufficient   /lib/security/pam_custom_ad.so
session    sufficient   /lib/security/pam_custom_ad.so
auth       sufficient   /lib/security/pam_custom_radius.so use_first_pass
account    sufficient   /lib/security/pam_custom_radius.so
password   sufficient   /lib/security/pam_custom_radius.so
session    sufficient   /lib/security/pam_custom_radius.so

If change the configuration as 
password   required   /lib/security/pam_unix.so debug
It is not allowing me to login which is expected.  
After enabling the debug in PAM configuration I could see the debug logs which shows that it is using the OLD password as a new password.
"
debug.log
<87>  2012-01-01T00:39:56.980000+00:00 localhost login[24398]: login 24398 -  pam_unix(login:chauthtok): username [sysadmin] obtained -
<87>  2012-01-01T00:39:56.990000+00:00 localhost login[24398]: login 24398 -  pam_unix(login:chauthtok): bad authentication token -
<87>  2012-01-01T00:39:56.990000+00:00 localhost login[24398]: login 24398 -  pam_unix(login:chauthtok): bad authentication token -
<87>  2012-01-01T00:39:56.990000+00:00 localhost login[24398]: login 24398 -  pam_unix(login:chauthtok): bad authentication token -

notice.log
<85>  2012-01-01T00:41:14.910000+00:00 localhost login[25229]: login 25229 -  pam_unix(login:account): expired password for user sysadmin (root enforced) -
<85>  2012-01-01T00:41:22.420000+00:00 localhost login[25229]: login 25229 -  pam_unix(login:chauthtok): new password not acceptable -
"

**Comment by t8m** [comment]
Unfortunately this does not give enough information to be able to help you. What is the system in play. The configuration looks really ancient. Is this really Linux-PAM and what exact version, etc. etc.

**Comment by adityaK18** [comment]
It is a Debian version running on AST2400 chipset. Yes, it is a pam_unix module of Linux PAM. Right now I don't have the exact pam_unix version information.

**Comment by adityaK18** [comment]
Has anyone observed such issue with pam_unix earlier?

**Comment by adityaK18** [comment]
A few days earlier I have identified the root cause the conversion function in application layer i.e. login is not properly implemented. It is passing saved password in response and did not prompt for new password.
We are good to close this issue.
