### ISSUE TITLE
Faulty logical expression evaluation in pam_time

### ISSUE THREAD

**Issue by daniel-deptula** [linux-pam/linux-pam#124]
Hi,

The issue is easy to reproduce.

Create 3 users on the system:
developer1
developer2
developer3

Enable pam_time (`account required pam_time.so`) and add the following rule to /etc/security/time.conf:
`*;*;deve*;!Al0000-2400`
This rule  should prevent all users that have names starting with "deve" from accessing the system (every day, every hour).
It works fine.
developer1 isn't permitted
developer2 isn't permitted
developer3 isn't permitted

Now let's change the rule as follows:
`*;*;deve*&!developer2;!Al0000-2400`
This rule should allow only developer2 out of the 3 users to access the system.
It works fine too.
developer1 isn't permitted
developer2 is permitted
developer3 isn't permitted

Now let's also exclude developer3 from the rule so that developer2 and developer3 should be able to access the system:
`*;*;deve*&!developer2&!developer3;!Al0000-2400`
Now strange things start happening:
developer1 is permitted (shouldn't be)
developer2 is permitted (OK)
developer3 isn't permitted (should be permitted)

The same issue was encountered in year 2000 and a patch was proposed but apparently it wasn't included:
https://www.redhat.com/archives/pam-list/2000-January/msg00048.html
For me this patch resolved the problem.

Kind regards,
Daniel

**Comment by edneville** [comment]
It looks like this issue was closed by commit a33d198dd [24th Feb].

**Comment by ldv-alt** [comment]
Fixed by commit a33d198dd60d34422c706fd85d00b64d43402690, thanks.
