### ISSUE TITLE
RFE: please consider reading PAM configuration file fragments from /usr/lib (or /usr/share)

### ISSUE THREAD

**Issue by poettering** [linux-pam/linux-pam#127]
Currently all PAM configuration is read from /etc/pam.d/. I think it would be great if PAM was capable of falling back to looking for these fragments in /usr/lib/pam.d/ if nothing is found in /etc/pam.d/. Rationale:

/usr is the place for (immutable) vendor resources, and in most ways PAM configuration is supplied by the vendor, and not really user-facing configuration. Yes, users can also configure it manually with an editor, but this is not the common case today, as PAM stack configuration is kind of a programming language of its own, and requires a deep understanding of its own.

I think it would be great if /etc would be where actual user configuration is placed, while /usr is where the vendor ships its resources including defaults. This then enables systems to boot up safely and correctly even if /etc is entirely unpopulated.

Usecases for this: systemd systems know the "systemd.volatile=" kernel command line option. If you use that the system will boot up like normal, however only /usr is used from the configured root file system (and mounted read-only), and / is replaced with a tmpfs. This allows to quickly boot up a system with all settings reset to the default. (systemd-nspawn --volatile= implements a similar mode, just for OS containers). This mostly already works fine, at least for simple systems. However currently the big issue is PAM: you can't log in without PAM being configured, but PAM currently wants to be configured in /etc/pam.d/ only which doesn't exist in this mode. Currently, there's a fix in systemd to make this work anyway: a tmpfiles.d/ snippet will copy a "factory" pam.d/ directory from /usr/share/factory/ to /etc if its missing there. I would like to get rid of that in the long run though, and would prefer if PAM would just work without any such hacks as long as /usr/lib/pam.d/ is properly populated.

Implementation for this would be easy: when PAM looks for a file /etc/pam.d/XYZ and gets an ENOENT it should immediately check /usr/lib/pam.d/XYZ as fallback, and propagate ENOENT only if that fails too.

Note that I am just requesting this as a *fallback*. I am very sure /etc/pam.d should always remain what is checked first, as user configuration should always win over vendor configuration.

(In the long run I'd like to see Fedora move most of its PAM snippets from /etc/pam.d to /usr/lib/pam.d/, and only leave the stuff generated by authconfig in /etc/pam.d)

**Comment by thkukuk** [comment]
What's wrong with the current implementation of this in Linux-PAM?

Beside that I would prefer to move all the configuration files and *.d directories out of /usr/lib, one of the biggest complains of Linux users is, that it is meanwhile impossible to find the right configuration file with grep or so.

**Comment by poettering** [comment]
oh, it is? i wasn't aware. Ignore me then. Sorry!

(and i see this is even documented!)

**Comment by poettering** [comment]
(in
