### ISSUE TITLE
pam_modutil_user_in_group_common does same job twice?

### ISSUE THREAD

**Issue by habazut** [linux-pam/linux-pam#133]
In the code below, if HAVE_GETGROUPLIST is defined, does not checkgrouplist() do the same thing as the for loop and the if clause above it? Should it not be something like (pseudo code):

```
#ifdef HAVE_GETGROUPLIST
    call to checkgrouplist
#elseif 
 if (pwd->pw_gid == grp->gr_gid)
 (...)
 for (i = 0; (grp->gr_mem != NULL) && (grp->gr_mem[i] != NULL); i++)
 (...)
#endif 
```

Or is there an case when the if/for combination and checkgroplist return different results. (IMHO that should never happen according to what getgrouplist is for)

Regards,
Harald.

```
static int
pam_modutil_user_in_group_common(pam_handle_t *pamh UNUSED,
				 struct passwd *pwd,
				 struct group *grp)
{
	int i;

	if (pwd == NULL) {
		return 0;
	}
	if (grp == NULL) {
		return 0;
	}

	if (pwd->pw_gid == grp->gr_gid) {
		return 1;
	}

	for (i = 0; (grp->gr_mem != NULL) && (grp->gr_mem[i] != NULL); i++) {
		if (strcmp(pwd->pw_name, grp->gr_mem[i]) == 0) {
			return 1;
		}
	}

#ifdef HAVE_GETGROUPLIST
	if (checkgrouplist(pwd->pw_name, pwd->pw_gid, grp->gr_gid)) {
		return 1;
	}
#endif

	return 0;
}

```

**Comment by t8m** [comment]
These actually can do different things for remote user identity services. Basically the group members might not be populated for them but getgrouplist might work. On the other hand it is a faster shortcut to check the list if it is already populated.
