### ISSUE TITLE
optimize checkgrouplist by not looping over getgrouplist

### ISSUE THREAD

**Issue by habazut** [linux-pam/linux-pam#134]
The documentation for getgrouplist says:

       The ngroups argument is a value-result argument: on  return  it  always
       contains  the  number  of  groups found for user, including group; this
       value may be greater than the number of groups stored in groups.

Unfortunately this is not used. Is there a reason for this?

So in checkgrouplist the whole 

do {
  ... agroups *= 2; .... 
} while (((i < 0) || (ngroups < 1)) && (agroups < 10000))

loop is unneccessary and shold be replaced by first a call to getgrouplist with a reasonable default like ngroups=100 ( a malloc(sizeof(gid_t) * 100 ) is not that big) and if that call fails with -1 (the user is in more than 100 groups) then one can do a malloc (sizeof(gid_t) * ngroups ) and redo the call to getgrouplist which then will give back all groups the user is part of.

When failing the malloc, should there be some pam_strerror call?

The current strategy of testing with n=3,6,12,.... is quite suboptimal if you have some thousand students in a group used in /etc/security/access.conf.

Regards,
Harald.

**Comment by t8m** [comment]
You're right. Thanks for the report, I'll prepare a patch.

**Comment by t8m** [comment]
Fixed in master.
