### ISSUE TITLE
Man page for pam_fail_delay() is misleading

### ISSUE THREAD

**Issue by lifecrisis** [linux-pam/linux-pam#137]
Greetings,

I am working to fix some bugs and to simplify the code in the KDE screen locker.  The relevant problem related to this issue is found at [this link](https://phabricator.kde.org/D23734).

While working on this, I came across a misleading line in the `pam_fail_delay` [man page](https://github.com/linux-pam/linux-pam/blob/2405afa2f019e4409b52396cdf62383b1440a165/doc/man/pam_fail_delay.3.xml#L96), reproduced below:

```
Note, if PAM_FAIL_DELAY item is unset (or set to NULL), then no delay
will be performed.
```

This led me to believe that I could disable any delay with the following line in the client code:

```c
pam_set_item(pamh, PAM_FAIL_DELAY, NULL);
```

Upon examining the Linux-PAM code, this doesn't seem to be true.  The relevant function is `_pam_await_timer()` found [here](https://github.com/linux-pam/linux-pam/blob/0698382cf55ad79d0d591fad9609c68eabfac2a2/libpam/pam_delay.c#L87).

The `_pam_await_timer()` function will still perform a specified delay when `PAM_FAIL_DELAY` is `NULL`.  Thus, it does not seem to be possible to disable any delay in this way.  I have reproduced a shortened version of this internal Linux-PAM function to show why this is true:

```c
void _pam_await_timer(pam_handle_t *pamh, int status)
{
    /* compute the delay first here ... */

    if (pamh->fail_delay.delay_fn_ptr) {

        /* ... PAM_FAIL_DELAY was not NULL, call the user function ... */

    } else if (status != PAM_SUCCESS && pamh->fail_delay.set) {

        /* PAM_FAIL_DELAY was NULL, still perform the  delay */

	if (delay > 0) {
	    struct timeval tval;

	    tval.tv_sec  = delay / 1000000;
	    tval.tv_usec = delay % 1000000;
	    select(0, NULL, NULL, NULL, &tval);
	}
    }

    /* reset timer and return */
}
```

The screen locker disables the delay by defining a no-op function and then having `PAM_FAIL_DELAY` point to it (so that the call within the body of `_pam_await_timer()` does nothing).

Perhaps the proper method for a PAM client to disable any delay should be documented?

**Comment by t8m** [comment]
Would you like to submit a PR which fixes the manual page bug?

**Comment by lifecrisis** [comment]
I'd love to contribute a PR!

I started by creating an issue because I wanted to see which way the problem went: i.e., does the documentation need to change to match the code, or does the code need to change to match the documentation?

I wanted to note that changing the code to match the documentation could be done well, I think.  This could be accomplished by setting the default value of `PAM_FAIL_DELAY` to be a pointer to a function whose body matches the behavior of the `else` clause in the `_pam_await_timer()` function.  This would mean that the default delay behavior could then be disabled with ...

```c
pam_set_item(pamh, PAM_FAIL_DELAY, NULL);
```

... as promised by the documentation.  One could even save and restore the default behavior with a call to `pam_get_item()` first.  I'm not sure if this would ever be useful, but it would be possible.

I assume you mean that I should adjust the documentation.  Is that correct?

**Comment by t8m** [comment]
As this behavior was there forever I do not think it would be good to make it behave according to the documentation now. So in my opinion fixing the documentation would be more appropriate.
But what do @ldv-alt @thkukuk  think?

**Comment by thkukuk** [comment]
There are at minimum three PAM implementations. Don't change the behavior of the function, this would break too much and may make us even more incompatible. Fix the documentation that it describes the behavior.

**Comment by lifecrisis** [comment]
> Don't change the behavior of the function, ...

Understood.  The above was just an idea.

I'll re-read the relevant code sections carefully and come up with a reasonable change to the man page.  Expect a pull request from me in the near future.
