### ISSUE TITLE
pam_env: Potential issue with changing of a static variable

### ISSUE THREAD

**Issue by guidovilla** [linux-pam/linux-pam#14]
**pam_env.c**:74:
```
/* This is a flag used to designate an empty string */
static char quote='Z';
```

but in function **check_var** (row 511):
```
    if (&quote == var->defval) {
      /*
       * This means that the empty string was given for defval value
       * which indicates that a variable should be defined with no value
       */
      *var->defval = '\0';
```
as it can be seen, the last line changes the value of `quote`. This does not seem to have ill effects at the moment, but it is not nice because `quote` becomes = `'\0'`, which has also a special meaning different from `quote` itself (`quote` means the empty quoted string, `'\0'` means the empty unquoted string).

**Comment by glensc** [comment]
probably should just make copy of the variable in `check_var` and perhaps change the original as `#define`

**Comment by glensc** [comment]
made #14 based on the description. however `pam_env` may relying on such behavior.

**Comment by cgzones** [comment]
Should be addressed by https://github.com/linux-pam/linux-pam/commit/563d21d6dbb6d64613919ccb1cc939bae546baab.
