### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [linux-pam/linux-pam#141]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by kloczek** [comment]
Guys please make new release soon.
More and more distros are using substantial part of the already committed patches.
It does not make sense hold everything for already +1.5y.

**Comment by t8m** [comment]
I agree, we should do a new release soon.

**Comment by edneville** [comment]
Linking with #159

**Comment by ldv-alt** [comment]
According to
https://translate.fedoraproject.org/projects/linux-pam/master/
our translations are not in a good shape yet.

**Comment by kloczek** [comment]
Just do "make -C po update-po" and commit changes to push signal that .po files needs to be updated.

**Comment by t8m** [comment]
> Just do "make -C po update-po" and commit changes to push signal that .po files needs to be updated.

This was already done. We are now waiting for the translations to be updated by translators.

**Comment by ldv-alt** [comment]
The latest update of translations was two weeks ago.
I think the master branch is ready to be tagged for release.

**Comment by t8m** [comment]
+1

**Comment by ldv-alt** [comment]
Linux-PAM 1.4.0 released.
