### ISSUE TITLE
Please add support for pam_start("/path/to/service", ...)

### ISSUE THREAD

**Issue by cryptomilk** [linux-pam/linux-pam#143]
Please add support for `pam_start("/path/to/service", ...)`.

This would be useful for pam_wrapper: https://cwrap.org/pam_wrapper.html

OpenPam from FreeBSD allows this. However you need to explicitly disable some security checks to allow this. It would be great to have this with Linux-PAM too. Currently we need to use an ugly hack to get pam_wrapper working with Linux-PAM

**Comment by cryptomilk** [comment]
https://www.daemon-systems.org/man/openpam_get_feature.3.html

**Comment by t8m** [comment]
The proper solution would be to add pam_start_ex() function that would add a new argument to specify the path where the service files should be looked up.
@ldv-alt @thkukuk  - What do you think? I can make PR for the int pam_start_ex(const char *pam_directory, const char *service_name, const char *user,
                     const struct pam_conv *pam_conversation,
                     pam_handle_t **pamh) function.

**Comment by thkukuk** [comment]
The current problem is: /path/to/service is already implemented, but there is a check in pam_start() which forbids it. So this is something we have to look anyways, currently there is dead code.

I would prefer the pam_set_feature() function which disables the check in pam_start().
Because if we had a new function now and get a new request for another check, we have to add the next function. And if somebody wants to have both functions, will we add a third fourth function? In my opinion, this will not scale.
And as the code is already there for /path/to/service, we only need to temporary disable the check, this would be the cleanest solution.

**Comment by t8m** [comment]
I really dislike to add global state just for this thing.

**Comment by t8m** [comment]
Also, how would be handled the include and substack directives? And I would not say the current code already implements /path/to/service - yes, there are some pieces of it already but...

**Comment by t8m** [comment]
Another option would just be to allow the /path/to/service unconditionally, there is actually no major reason why to block it. But we still need to properly think about and implement the substack/include handling.

**Comment by cryptomilk** [comment]
Do you already have a solution?

**Comment by t8m** [comment]
No, not yet.
@ldv-alt @thkukuk What about allowing /path/to/service unconditionally in pam_start. Any opinion?

**Comment by thkukuk** [comment]
We and every other implementation did allow that in the beginning, but for some reason, everybody did disallow it. I think it were security reasons, but I don't remember any details.

Can there be any problem, if a normal user can bring in his own configuration files, while the appliations is not running as root?

**Comment by t8m** [comment]
I have no idea what could be the problem - there is nothing preventing regular users to patch and run libpam in whatever way they wish on whatever configuration files they wish. That should not provide any kind of privilege escalation to them.
I think the reason could be instead to prevent disaster if there was some way how to arbitrarily influence the service string for some root application. Or just a preventive measure against that kind of misconfiguration - such as using a directory for the pam stack configuration of a system application where regular user has write access.

**Comment by t8m** [comment]
Except if there is a way for some system application to influence the service string for it by regular users it already is a major security issue for that application even without paths being allowed. So I do not see that adding the path support is regressing in that sense.

**Comment by ldv-alt** [comment]
On Tue, Oct 15, 2019 at 01:46:05AM -0700, Thorsten Kukuk wrote:
> We and every other implementation did allow that in the beginning, but for some reason, everybody did disallow it. I think it were security reasons, but I don't remember any details.
> 
> Can there be any problem, if a normal user can bring in his own configuration files, while the appliations is not running as root?

If we are trying to recollect the reason for the traditional behaviour,
let's extend the audience behind this issue tracker.

**Comment by t8m** [comment]
How to do that? The pam-list is quite dormant I think.

**Comment by cryptomilk** [comment]
Implement it in pam_start() and then you can always add a function like pam_set_feature() to enable it if there are security concerns.

**Comment by cryptomilk** [comment]
Any update? :-)

**Comment by cryptomilk** [comment]
@ldv-alt Friendly ping!

**Comment by t8m** [comment]
We now have a new API call pam_start_confdir() that allows specifying the config directory path.

**Comment by cryptomilk** [comment]
Thanks!
