### ISSUE TITLE
Centos 7 - pam_session_open() PAM_SESSION_ERR 14

### ISSUE THREAD

**Issue by VladAdGad** [linux-pam/linux-pam#147]
I have a simple code which works on Ubuntu and Debian systems but on Centos 7 and Oracle Linux 7 I got error 14 on line 20 Pam_open_session()

![image](https://user-images.githubusercontent.com/15636176/67108473-9516c380-f19c-11e9-9491-1ba764f70e62.png)

**Comment by t8m** [comment]
What error do you get?

**Comment by VladAdGad** [comment]
PAM_SESSION_ERR
Code 14
/* Can not make/remove an entry for the specified session */
Line 20

**Comment by t8m** [comment]
This really depends on what your PAM stack configuration for the "service_name" looks like. If you do not have any configuration for this service then the PAM_SESSION_ERR which you obtained is appropriate.

**Comment by VladAdGad** [comment]
as I know if there is not configuration for a service then defaults are used

**Comment by t8m** [comment]
What do you mean by "defaults"? The service file for "other" service will be used which denies everything by default on Fedora/RHEL/CentOS.

**Comment by VladAdGad** [comment]
I mean that if you are binding PAM session to a service named service_name then first PAM looks for /etc/pam.d/service_name. If there is no such file then defaults from file /etc/pam.conf are used.
Correct me if I'm wrong or smth.

**Comment by t8m** [comment]
It depends on how PAM is built with which options.

**Comment by t8m** [comment]
--enable-read-both-confs during configure controls that and Fedora/RHEL PAM does not have this option enabled.
