### ISSUE TITLE
pam_stress: There is no man page

### ISSUE THREAD

**Issue by miztake** [linux-pam/linux-pam#148]
Only pam_stress has no man page in the PAM modules provided by linux-pam.
We should create the man page based on modules/pam_stress/README.

**Comment by oxr463** [comment]
I'll take a crack at this one.

**Comment by oxr463** [comment]
@miztake please review my PR when you get a chance.

**Comment by miztake** [comment]
@oxr463

Sorry for the late reply.
I will review this shortly.
Please wait for a while.

**Comment by miztake** [comment]
@oxr463

I'm sorry that I was late.
I made a comment below.

https://github.com/oxr463/linux-pam/commit/31ecedf0d2622bba94a1770a757681998dfbf830#diff-81efd074dd5f345151fa312a2bfafa26R22
