### ISSUE TITLE
fails to compile with GCC stricter option

### ISSUE THREAD

**Issue by n8v8R** [linux-pam/linux-pam#156]
cross reference downstream https://bugs.gentoo.org/701982 where the issue explained and the reason why being deferred to lodge the issue upstream

**Comment by ldv-alt** [comment]
On Wed, Dec 04, 2019 at 11:28:10AM -0800, n8v8R wrote:
> cross reference downstream https://bugs.gentoo.org/701982 where the issue explained and the reason why being deferred to lodge the issue upstream

Isn't it a duplicate of https://github.com/linux-pam/linux-pam/issues/38 ?

**Comment by n8v8R** [comment]
In way of the output yes, but apparently it has not been reported that package compilation fails with the GCC option stricter and causing the subsequent QA issue and abort.

**Comment by n8v8R** [comment]
Seems I was mistakenly reckoning that the QA check issue stems from the GCC code but apparently it is something implemented by the downstream repo in their `ebuild` (package) concept. Thus it is a bit unclear why downstream is deferring to upstream.

Closing since it has the potential for a ping pong between upstream (not caused by our code) and downstream's (stricter) QA check implementation.
