### ISSUE TITLE
pam_shells denies if user shell is empty in /etc/passwd

### ISSUE THREAD

**Issue by kewne** [linux-pam/linux-pam#159]
When a user is created by `useradd` and no shell is specified, that user's shell is set to the empty string in `/etc/passwd` which, according to the documentation:
> If this field is empty, it defaults to the value /bin/sh.

However, the `pam_shells` module performs a simple string comparison and always fails the check for these users, even if `/bin/sh` is in the `/etc/shells` file.

**Comment by kewne** [comment]
I think this is solved by 28189d80695e320c4bf014232e279671182b502e.

Is there a release with that change yet, or when is it expected?

Thanks for fixing this, btw! 🙇

**Comment by t8m** [comment]
I'd like to do a pre-release ASAP and the final release within March.

**Comment by ldv-alt** [comment]
Fixed by commit 28189d80695e320c4bf014232e279671182b502e, thanks.
