### ISSUE TITLE
pam_tally2: SSH account locking reveals real users

### ISSUE THREAD

**Issue by ipylypiv** [linux-pam/linux-pam#160]
This was asked on the StackExchange:
https://unix.stackexchange.com/questions/387880/ssh-account-locking-reveals-real-users

> On my ssh server, I'm trying to hide the existence of all the users except for one. For any user besides that one user, I will get a Password: prompt which will never allow the user to enter. That's good. But for real users, after a certain number of attempts, it will start printing "Account locked due to XX failed logins". It will not do this for non-existent users.

Looks like this is still an issue.

**Comment by edneville** [comment]
Are you using `silent`?

**Comment by ipylypiv** [comment]
I'm using `silent` because of this issue.

I would expect the module to show "Account locked due to XX failed logins" regardless if there is such a user or not.

**Comment by edneville** [comment]
From looking at the description of the issue I think `silent` would solve the issue, if I understand correctly as a remote adversary could determine valid accounts through a dictionary attack, since a response message changes. I would prefer to avoid this on an internet reachable machine running SSH. For internal machines where the threat is reduced I might consider to report failed logins.

Doesn't `audit` report the same message for valid and invalid users?

**Comment by ipylypiv** [comment]
The man page doesn't mention this vulnerability so many people out there are using pam_tally2 on the internet reachable servers without the `silent` option since it is not a default param.

---
**audit**
`Will log the user name into the system log if the user is not found.`

`audit` is for internal logging.

**Comment by edneville** [comment]
> The man page doesn't mention this vulnerability so many people out there are using pam_tally2 on the internet reachable servers without the silent option since it is not a default param. 

Often when new features are made they are often added as opt-in, so users need to do something differently to benefit from new features. As this could be seen as a security feature then perhaps 'nosilent' would be preferable.

> audit is for internal logging

I hadn't looked, but wanted to know. If audit populates the tally log, then there's no reason (I suppose) to simulate the same behaviour. Could be of benefit to those running honeypots/tarpits if they wish to make false accounts appear real. Tarpitting a scanner at 'abc123' may be preferable to allowing it to continue to 'bob'.

**Comment by t8m** [comment]
The `audit` option is completely unrelated. Yes, you have to use `silent` if you do not want the account locked message to be printed. It is fairly obvious. It would not be good idea to simulate this for nonexistent accounts (pam_tally2 file format would not even allow it). We are not going to change the default behavior. You can submit a PR to adjust the manual page to make it clear that using the module without silent leaks the user's presence on the system.
