### ISSUE TITLE
library linkage Issue with successful cross compilation libraries of linux-pam source

### ISSUE THREAD

**Issue by manikanta226** [linux-pam/linux-pam#17]
This is not an issue, i need help regarding ./configure flags for library linkage. my problem is
Taken the Linux-pam source Linux-PAM-1.3.0.tar.gz and configure to my ARM board and cross compiled using below commands

    # ./configure --prefix=/u02/tasks/linux-pam/Linux-PAM-1.3.0/output/pre --exec-prefix=/u02/tasks/linux-pam/Linux-PAM-1.3.0/output/epre CC=/opt/96TT/usr/bin/arm-linkwell-linux-gnueabihf-gcc ARCH=arm --host=arm-none-linux-gnueabi
    # make install

Then copied the libraries to my target board to /lib and /lib/security/ respectively, while running pam based application got the error in /var/log/message as

    Feb 10 16:13:16 authpriv.err pam_aut: PAM adding faulty module: /u02/tasks/linux-pam/Linux-PAM-1.3.0/output/epre/lib/security/pam_unix.so
    Feb 10 16:13:16 authpriv.err pam_aut: PAM unable to dlopen(/u02/tasks/linux-pam/Linux-PAM-1.3.0/output/epre/lib/security/pam_deny.so): /u02/tasks/linux-pam/Linux-PAM-1.3.0/output/epre/lib/security/pam_deny.so: cannot open shared object file: No such file or direct
    Feb 10 16:13:16 authpriv.err pam_aut: PAM adding faulty module: /u02/tasks/linux-pam/Linux-PAM-1.3.0/output/epre/lib/security/pam_deny.so

By default application links to /lib/security/*.so , but the library in /lib/security searches for supported library in pc compiled path instead of /lib. so, on board that path not exists its getting file not found.

Here, question is how to change the linkage path of /lib/security/pam_*.so from pc compiled path to /lib/, to achieve this How to configure the pam source to take library linkage from /lib/ instead of PC compiled Path ? Is there any FLAG is need to set while configuring ?

 Help me ..

**Comment by adityaK18** [comment]
I am facing the same issue. Wanted to know if you have fixed it.

**Comment by t8m** [comment]
You should not use prefix with configure but `make install DESTDIR=/path/to/install` instead.
