### ISSUE TITLE
What is the version of the GPL in the COPYING file ?

### ISSUE THREAD

**Issue by Silviu-Caprar** [linux-pam/linux-pam#19]
Hi there,

I am interested in finding out the version of the GPL from COPYING for Linux-PAM 1.1.6 . 
Also there are other files under BSD 3 Clause or GPL. For example: 
\libpam\include\security\pam_modules.h or
\modules\pam_tty_audit\pam_tty_audit.c
I think there are around 50 files like that.

Can you please clarify the GPL version ?

Thank you in advance.

**Comment by t8m** [comment]
The whole Linux PAM is licensed under BSD 3 clause license, that means you can relicense it under any GPL version if you wish.
