### ISSUE TITLE
redundant check

### ISSUE THREAD

**Issue by milabs** [linux-pam/linux-pam#197]
https://github.com/linux-pam/linux-pam/blob/1205c0e828eedebeac22eb52894c5c436264c638/libpam/pam_handlers.c#L724

**Comment by ldv-alt** [comment]
On Tue, Mar 24, 2020 at 02:57:39PM -0700, Ilya V. Matveychikov wrote:
> https://github.com/linux-pam/linux-pam/blob/1205c0e828eedebeac22eb52894c5c436264c638/libpam/pam_handlers.c#L724

Let the compiler optimize it out.

**Comment by milabs** [comment]
Well, this code as is:
~~~
		    strcpy(mod_full_isa_path, mod_path);
                    isa = strstr(mod_full_isa_path, "$ISA");
		    if (isa) {
		        memmove(isa + strlen(_PAM_ISA), isa + 4, strlen(isa + 4) + 1);
		        memmove(isa, _PAM_ISA, strlen(_PAM_ISA));
		    }
		    mod->dl_handle = _pam_dlopen(mod_full_isa_path);
		    _pam_drop(mod_full_isa_path);
~~~
... doesn't make any sense without `isa` to be valid.

**Comment by CompilerThoughts** [comment]
@ldv-alt 
> Let the compiler optimize it out.

Man, I don't know what string you checked before.

**Comment by ldv-alt** [comment]
On Tue, Mar 24, 2020 at 03:17:34PM -0700, Ilya V. Matveychikov wrote:
> Well, this code as is:

The code is correct but there is a room for improvement,
feel free to take a stab at it.

**Comment by milabs** [comment]
https://github.com/linux-pam/linux-pam/pull/198
