### ISSUE TITLE
Some questions about pam_usertype.so

### ISSUE THREAD

**Issue by blueskycs2c** [linux-pam/linux-pam#203]
Create the system user by useradd -r -u 2000  test2000
get the test2000 types by pam_usertype.so is isregular.The type of the account is decided with help of SYS_UID_MIN and SYS_UID_MAX settings in /etc/login.defs.

**Comment by t8m** [comment]
The system user in the sense of pam_usertype is determined only by matching the uid with the SYS_UID_MIN and SYS_UID_MAX range. There is actually no other reliable way how to tell whether some user is a system user. This is by-definiton.
Perhaps it would make some sense to print a warning from useradd if -r is used with uid number outside of the SYS_UID_MIN and SYS_UID_MAX range. If you want, please report an RFE to shadow.
https://github.com/shadow-maint/shadow
