### ISSUE TITLE
vim syntax for ~/.pam_environment

### ISSUE THREAD

**Issue by lzutao** [linux-pam/linux-pam#221]
Or make it clear about the parsing rule of `.pam_environment`.
cc https://github.com/vim/vim/pull/6051#issuecomment-625316747

**Comment by ldv-alt** [comment]
On Thu, May 07, 2020 at 08:19:49AM -0700, lzutao wrote:
> Or make it clear about the parsing rule of `.pam_environment`.
> cc https://github.com/vim/vim/pull/6051#issuecomment-625316747

The source code comment says:
"we try to be smart about quotes around the value, but not too smart, we can't get all fancy with escaped values like bash".

**Comment by lzutao** [comment]
Thanks, I opened a PR in vim: <https://github.com/vim/vim/pull/6065>. Please take a look if you are interested.

**Comment by lzutao** [comment]
The commit merged. Closed as fixed. Thanks for coordinate!
