### ISSUE TITLE
Have to create /var/lib/faillock/user manually for pam_faillock now

### ISSUE THREAD

**Issue by FirstLoveLife** [linux-pam/linux-pam#231]
I'm trying to play with latest pam_faillock, and found it will not mkdir /var/lib/faillock/ integral. So I have to manually mkdir the dir and touch user file for per user. This is really confusing and annoying. What's your idea?

**Comment by t8m** [comment]
The default directory is `/var/run/faillock`. Yes, it needs to be created by other means as the module might not have sufficient privileges to create it. You can use for example tmpfilesd from systemd to create the directory. The individual user files do not have to be touched, they will be created when the user tries to log-in if the `/var/run/faillock` directory has permissions allowing the authenticating processes to create them.

**Comment by FirstLoveLife** [comment]
```
$ cat /usr/lib/tmpfiles.d/faillock.conf 
d /var/run/faillock 0755 root root
```

Thanks!
