### ISSUE TITLE
sudo delayed by 25 seconds with pam_systemd

### ISSUE THREAD

**Issue by PrinterFranklin** [linux-pam/linux-pam#232]
I found the problem on Fedora 29, but this problem is hard to reproduce.

My /etc/pam.d/system-auth has:
`session     optional      pam_keyinit.so revoke
session     required      pam_limits.so
-session     optional      pam_systemd.so
session     [success=1 default=ignore] pam_succeed_if.so service in crond quiet use_uid
session     required      pam_unix.so
-session     optional      pam_sss.so`

When pam_systemd.so is commented, the problem can not be reproduced anymore. Can I comment pam_systemd.so? What will be the risk of doing it?

**Comment by t8m** [comment]
I'd suggest reporting the problem against systemd to Fedora bugzilla. Also as Fedora 29 is out of support for a long time, I'd suggest upgrading to the latest released version (32) first.

**Comment by t8m** [comment]
I am sorry we cannot help you more here but pam_systemd is not part of Linux PAM.
