### ISSUE TITLE
pam_motd: respect ~/.hushlogin

### ISSUE THREAD

**Issue by mkoskar** [linux-pam/linux-pam#233]
The idea is to do nothing when ``~/.hushlogin`` is present, similarly to how ``login`` and ``sshd`` behave.

**Comment by ldv-alt** [comment]
Do you suggest to change the default behaviour of pam_motd, or add a new option to honor ~/.hushlogin?

**Comment by t8m** [comment]
I would be for adding option because this means influencing pam_motd behavior by the user configuration and that might not be something that the system administrator might want.
It might not be necessarily a pam module option as there already is HUSHLOGIN_FILE option in login.defs which is unset by default and should provide the configurability.

**Comment by ldv-alt** [comment]
Then it would make sense to implement login.defs HUSHLOGIN_FILE semantics:

"If defined, file which inhibits all the usual chatter during the login sequence.  If a full pathname, then hushed mode will be enabled if the user's name or shell are found in the file.  If not a full pathname, then hushed mode will be enabled if the file exists in the user's home directory."

**Comment by t8m** [comment]
Yes, sure.

**Comment by mkoskar** [comment]
Let's call "hushed mode" the presence of ``~/.hushlogin`` or to be more precise conditions met as by semantics described in ``login.defs``.

For reference I was looking at ``ssh`` and ``login`` and I believe that actually problem is with ``util-linux/login`` for not calling ``pam_open_session`` with ``PAM_SILENT`` flag when in "hushed mode". 

I realized that to be consistent with original ``login`` behavior, there are more pam session modules which would need to be aware of "hushed mode" apart from ``pam_motd`` (at least ``pam_lastlog`` and possibly ``pam_mail``).

Further I think the problem is with semantics of "hushed mode" as a whole. Most of the time what one actually wants is to get rid of MOTD and doesn't mind "lastlog info" or "new mail", so ideally it would be ``~/.hushmotd`` and then that would be straightforward, no need to PAM_SILENT all modules and only ``pam_motd`` would pick up on it.

Anyway as things stand I believe most consistent would be for ``util-linux/login`` to call ``pam_open_session`` with ``PAM_SILENT`` flag.  

ssh
---

https://github.com/openssh/openssh-portable/blob/master/session.c#L1550
https://github.com/openssh/openssh-portable/blob/master/session.c#L821

* it has its own ``PrintMotd yes/no`` but it's usually ``no`` and uses same pam session stack config as local login which includes ``pam_motd`` (``/etc/pam.d/system-login`` on Arch Linux)
* output of session modules is captured and then diplayed or not depending on presence of ``~/.hushlogin``

util-linux login
----------------

https://github.com/karelzak/util-linux/blob/master/login-utils/login.c#L1345
https://github.com/karelzak/util-linux/blob/master/login-utils/logindefs.c#L471

* here ``pam_motd`` session module won't be silenced

shadow login
------------

https://github.com/shadow-maint/shadow/blob/master/src/login.c#L885
https://github.com/shadow-maint/shadow/blob/master/libmisc/hushed.c#L50

* here ``pam_open_session`` is called with ``PAM_SILENT`` flag

**Comment by karelzak** [comment]
I don't see a problem to use PAM_SILENT in util-linux login(1).

Note about hushlogin file semantic, there is a small difference between shadow and util-linux, copy & paste from code:
```
 * Hushed mode is enabled:
 *   
 * a) if a global (e.g. /etc/hushlogins) hush file exists:
 *     1) for ALL ACCOUNTS if the file is empty
 *     2) for the current user if the username or shell is found in the file
 *   
 * b) if a ~/.hushlogin file exists
 *   
 * The ~/.hushlogin file is ignored if the global hush file exists.
 *   
 * The HUSHLOGIN_FILE login.def variable overrides the default hush filename.
 *   
 * Note that shadow-utils login(1) does not support "a1)". The "a1)" is
 * necessary if you want to use PAM for "Last login" message.
```

**Comment by mkoskar** [comment]
@karelzak Thanks!

Closing.
