### ISSUE TITLE
fails to build pam_faildelay

### ISSUE THREAD

**Issue by oneforall2** [linux-pam/linux-pam#238]
make[3]: Entering directory '/tmp/Linux-PAM-1.4.0/modules/pam_faildelay'
make[3]: Nothing to be done for 'install-exec-am'.
 /usr/bin/mkdir -p '/tmp/package-pam/usr/man/man8'
 /usr/bin/ginstall -c -m 644 pam_faildelay.8 '/tmp/package-pam/usr/man/man8'
 /usr/bin/mkdir -p '/tmp/package-pam/lib64/security'
 /bin/sh ../../libtool   --mode=install /usr/bin/ginstall -c   pam_faildelay.la '/tmp/package-pam/lib64/security'
libtool: warning: relinking 'pam_faildelay.la'
libtool: install: (cd /tmp/Linux-PAM-1.4.0/modules/pam_faildelay; /bin/sh "/tmp/Linux-PAM-1.4.0/libtool"  --tag CC --mode=relink g
libtool: relink: gcc -shared  -fPIC -DPIC  .libs/pam_faildelay.o   -L/lib64 -L/usr/lib64 -L/tmp/package-pam/lib64 -lpam -ldl  -O2
/usr/bin/ld: .libs/pam_faildelay.o: in function `pam_sm_authenticate':
pam_faildelay.c:(.text+0x115): undefined reference to `pam_modutil_search_key'
collect2: error: ld returned 1 exit status
libtool:   error: error: relink 'pam_faildelay.la' with the above command before installing it
make[3]: *** [Makefile:652: install-securelibLTLIBRARIES] Error 1
make[3]: Leaving directory '/tmp/Linux-PAM-1.4.0/modules/pam_faildelay'
make[2]: *** [Makefile:1048: install-am] Error 2
make[2]: Leaving directory '/tmp/Linux-PAM-1.4.0/modules/pam_faildelay'
make[1]: *** [Makefile:501: install-recursive] Error 1GitHub
make[1]: Leaving directory '/tmp/Linux-PAM-1.4.0/modules'
make: *** [Makefile:491: install-recursive] Error 1

**Comment by oneforall2** [comment]
hmm I removed the old package and it built .. 
I think the pam_faildelay.c   needs the #include <security/pam_modutil.h> removed and #include "pam_modutil.h" or build with --disable-rpath?

**Comment by ldv-alt** [comment]
-L/lib64 -L/usr/lib64 before -L/tmp/package-pam/lib64 is wrong, but this must a libtool error that doesn't manifest itself elsewhere.  For example, there are no -L/lib64 at all in log files of test builds in github actions.

**Comment by ldv-alt** [comment]
The build system was changed from autotools to meson, closing this issue.
