### ISSUE TITLE
Any way to escape fingerprint prompt and type password instead when using sudo in terminal?

### ISSUE THREAD

**Issue by spxak1** [linux-pam/linux-pam#239]
Apologies if this is the wrong place for this.

In systems where the fingerprint scanner works, you can enable sudo authentication in the terminal, so that you can swipe your finger instead of typing your password when you issue "sudo" in terminal.

You can enable this by enabling "Fingerprint authentication" on pam-auth-update (by issuing "sudo pam-auth-update").

This works fine, although it is now always convenient to move your hand from the keyboard to the fingerprint scanner when typing. But it works as expected.

The problem starts when the laptop is docked or otherwise with the lid closed with external keyboard and the fingerprint scanner unreachable.

What happens is that when you type a sudo command, it prompts you to scan your finger, which of course you cannot, so you have to wait for the prompt to time out.

And here is the question. Is there a way to escape the timeout so that you can type the password right away? So, for instance you type the sudo command, you get the prompt, hit Esc, prompt goes, then you type the password.

Waiting for that prompt to time out is really annoying, whether you type on the laptop and you don't want to move your hand to the scanner, or when you type on an external keyboard and have no access to the scanner.

Thank you.

P.S. Currently I have to enable/disable it from pam-auth-update every time I change from dock to lap.

**Comment by t8m** [comment]
This would be a question for the pam_fprintd module - that is for the fprintd package https://gitlab.freedesktop.org/libfprint/fprintd as the module that is waiting for the fingerprint is that one and it is not part of the Linux PAM package.
