### ISSUE TITLE
pam_kwallet is not loading correctly with pam-1.4: sm_pam_authenticate never got called

### ISSUE THREAD

**Issue by Civil** [linux-pam/linux-pam#243]
Distro: gentoo

pam.d/sddm:
```
#%PAM-1.0
auth            include         system-login
-auth           optional        pam_gnome_keyring.so
-auth   optional  pam_kwallet5.so

account         include         system-login

password        include         system-login
-password       optional        pam_gnome_keyring.so use_authtok

session         optional        pam_keyinit.so force revoke
session         include         system-login
-session                optional        pam_gnome_keyring.so auto_start
-session  optional  pam_kwallet5.so auto_start
```

for both versions.

/etc/pam.d/system-login 
```
auth            required        pam_faillock.so preauth silent audit deny=3 unlock_time=600
auth            sufficient      pam_unix.so nullok try_first_pass
auth            [default=die]   pam_faillock.so authfail audit deny=3 unlock_time=600
auth            required        pam_shells.so 
auth            required        pam_nologin.so 
auth            include         system-auth
account         required        pam_access.so 
account         required        pam_nologin.so 
account         include         system-auth
account         required        pam_faillock.so
password        include         system-auth
session         optional        pam_loginuid.so
session         required        pam_env.so envfile=/etc/profile.env 
session         optional        pam_lastlog.so silent 
session         include         system-auth
session         optional        pam_motd.so motd=/etc/motd
session         optional        pam_mail.so
```

system-auth:
```
auth            required        pam_env.so 
auth            required        pam_faillock.so preauth silent audit deny=3 unlock_time=600
auth            sufficient      pam_unix.so nullok try_first_pass
auth            [default=die]   pam_faillock.so authfail audit deny=3 unlock_time=600
auth            required        pam_unix.so try_first_pass likeauth nullok 
auth            optional        pam_permit.so
account         required        pam_unix.so 
account         optional        pam_permit.so
account         required        pam_faillock.so
password        required        pam_passwdqc.so min=8,8,8,8,8 retry=3
password        required        pam_unix.so try_first_pass use_authtok nullok sha512 shadow 
password        optional        pam_permit.so
-session        optional        pam_systemd.so
session         required        pam_limits.so 
session         required        pam_env.so 
session         required        pam_unix.so 
session         optional        pam_permit.so
```

For system-auth and system-login difference is that with pam-1.3 there are no calls to faillock (obviously) and cracklib is used instead of passwdqc. I've tried to run pam-1.3 (to be precise, gentoo provided a snapshot based on commit 4dd9b97b762cc73816cb867d49c9d0d0b91d642c from January, so its not exactly 1.3 anymore) with config from 1.4 and kwallet works just fine with it.

I've compiled all of that with debug and the difference that I found is that with pam 1.4, even though auth line is parsed, but `sm_pam_authenticate` never got called:

Some interesting lines from the log (I'm using sddm if that matters) with pam-1.3:
https://gist.github.com/Civil/8ebf7b327ab482e601fbba9fd58f4816

And logs with pam-1.4:
https://gist.github.com/Civil/30bd87d7ab1bb41e1bbcc7f94514dd33

I really don't want to bisect pam between those two commits to find what exactly changed, so I'm opening an issue here as it seems to me that it's very likely an issue on the pam side (or some side effect of another change, which could be worked around)

**Comment by t8m** [comment]
You have incorrect configration in pam.d/sddm - you use `auth include system-login` where it should be `auth substack system-login` if you have any modules that should be called after the auth            `sufficient      pam_unix.so nullok try_first_pass`. For the other stacks you can keep include or change it to substack but that should not matter as there is no module configuration line which would abort the execution of the whole stack.

**Comment by madsl** [comment]
> You have incorrect configration in pam.d/sddm - you use `auth include system-login` where it should be `auth substack system-login` if you have any modules that should be called after the auth `sufficient pam_unix.so nullok try_first_pass`. For the other stacks you can keep include or change it to substack but that should not matter as there is no module configuration line which would abort the execution of the whole stack.

I changed from `auth include system-login` to `auth substack system-login` in /etc/pam.d/sddm, and now auto unlock works again!

**Comment by Civil** [comment]
Thanks. But is this something that have changed in pam-1.4? Because the same config worked fine before upgrading to 1.4.

Also that is somewhat standard configuration that sddm provides in most (if not all) distros nowadays, again because it used to work with pam 1.3

**Comment by t8m** [comment]
I do not believe this could work with pam-1.3 ever. Unless there were some gentoo-specific patches in your 1.3 build or unless the pam configuration was different. Are you absolutely sure that you used completely identical configuration with pristine 1.3 and 1.4 Linux PAM and it worked differently in this regard? I suppose you just used a different configuration with no pam_faillock and no sufficient pam_unix with 1.3. Btw I also see other errors in your configuration - the auth modules in system-auth and system-login after the 
```
auth            sufficient      pam_unix.so nullok try_first_pass
auth            [default=die]   pam_faillock.so authfail audit deny=3 unlock_time=600
```
will be completely ignored.

**Comment by Civil** [comment]
In gentoo there are two packages - one provides pam, another - basic pam configuration.

What I've tried is to install previous version of PAM configuration and manually remove (comment out) cracklib. And kwallet still wasn't working. However once I rollback pam to 1.3 it started to work.

I'm not a mainatiner of pam, I'm just a user. So all the questions and comments about the configuration should be addressed to Gentoo Dev who maintain pam: @Zlogene

**Comment by t8m** [comment]
OK, then I am going to close this issue as this is not an upstream Linux-PAM issue.
