### ISSUE TITLE
pam_unix: Warning: your password will expire in 32766 days.

### ISSUE THREAD

**Issue by t-hahn** [linux-pam/linux-pam#255]
I've been getting this message ever since PAM 1.4.0 (on openSUSE Tumbleweed, the 32766 may vary) and have meanwhile traced it down to the _unix_verify_user function which gets called from pam_sm_acct_mgmt in modules/pam_unix/pam_unix_acct.c.

In 1.3.1 the code that is now in _unix_verify_user was still in pam_sm_acct_mgmt and the lines
```C
        if (retval == PAM_SUCCESS && spent == NULL)
                return PAM_SUCCESS;
```
would actually exit from pam_sm_acct_mgmt and not just from _unix_verify_user.

Likely the simplest fix would be to initialize daysleft in _unix_verify_user with 0.

Best Wishes,

Thomas

**Comment by ldv-alt** [comment]
This is a regression introduced by commit f5adefa106e28c92dd73dbabac12bad667ef7b8f aka v1.4.0~249.
@pbrezina @t8m any ideas how to fix this?

**Comment by t8m** [comment]
@ldv-alt I'd just initialize daysleft = -1 in pam_sm_acct_mgmt(). If you agree I'll commit a fix right away. Or I can create a PR if you prefer.

**Comment by ldv-alt** [comment]
On Wed, Jul 22, 2020 at 01:56:57AM -0700, Tomáš Mráz wrote:
> @ldv-alt I'd just initialize daysleft = -1 in pam_sm_acct_mgmt(). If you agree I'll commit a fix right away.

Yes, that should fix the issue, please commit.
