### ISSUE TITLE
Pam 1.4 changes to pam_env might cause silent brakage on some setups.

### ISSUE THREAD

**Issue by rustonaut** [linux-pam/linux-pam#260]
The change in question:

`pam_env: Changed the default to not read the user .pam_environment file`

As far as I understand PAM/`pam_env` (I'm new to PAM!) then the environment variables set by `pam_env` are also available in the authenticated session later one (i.e. there is no separate process loading them).

Because of this `pam_env` seems to be used to set desktop and shell independent environment variables, including by users through `~/.pam_environment`  (e.g. after  research I found that at least in my case pam_env is the best way to set them).

(I thing) this is also the reason why e.g. arch linux does run `pam_env` at the _end_ of the auth pam stack.

I generally thing the change is good idea, but it might be a very good idea to highlight this change in the change note so that linux distributions don't forget to change there pam base setup to also load the user env file if they use pam_env.so in the way I described.

Or at least if I'm not wrong about how PAM works, if not I apologize for the additional work. (I do plan to setup a containerized PAM playground to better understand it but I don't know when I will come to it so I thought it's a good idea to open a issue now anyway).

**Comment by t8m** [comment]
Your analysis is correct. But we have the NEWS file entry for exactly that purpose. The distributions are expected to look at it when updating.

**Comment by rustonaut** [comment]
Thanks, I opened a bug/issue with archlinux which seems to have overlooked it as far as I can tell.

**Comment by captn3m0** [comment]
@rustonaut Couldn't find the issue on the Archlinux site, can you please give a link?
