### ISSUE TITLE
[RFC] pam_unix locked accounts

### ISSUE THREAD

**Issue by vbatts** [linux-pam/linux-pam#261]
Hey there,
Doing some reconciling of a patch that had been carried in CoreOS Container Linux (https://github.com/coreos/coreos-overlay/pull/1873/commits/8d8002043bd218703b1dcbef1eeacd0fad0a2371).

Effective to make an `/etc/shadow` entry of `systemd-coredump:!!:18402::::::` appear as a locked account.
Despite the shadow(5) docs of:
> If the password field contains some string that is not a valid result of crypt(3), for instance ! or *, the user will not be able to use a unix password to log in (but the user may log in the system by other means).

There does not seem to be much on the use-case or requirements behind this, except for continued hardening.
Also this patch does not appear to have landed upstream, nor surfaced for conversation.

My request for comments is whether this is something that would be considered for upstream?

Perhaps you could provide more background @mjg59 ?

/cc @krnowak

**Comment by mjg59** [comment]
I genuinely have no recollection at all of writing this patch.

**Comment by t8m** [comment]
No, I do not think this is a correct change. The exclamation mark in the password field does not really indicate fully locked account but a locked password only. You can have user password locked this way but still allow user's access by having for example ssh public key based authentication or kerberos authentication.
The proper way to lock the account fully is with `chage -E 0`
