### ISSUE TITLE
pam_env: .pam_environment behaviour change in pam 1.4

### ISSUE THREAD

**Issue by loqs** [linux-pam/linux-pam#263]
.pam_environment containing the following single line with no end of line marker:
```
SSH_AUTH_SOCK DEFAULT="${XDG_RUNTIME_DIR}/ssh-agent.socket"
```
Previous to pam 1.4 was accepted.  With pam 1.4 it is rejected.  Debug from pam 1.4
```
[pam_env.c:_parse_config_file(138)] Config file name is: /home/testuser/.pam_environment
[pam_env.c:_assemble_line(294)] called.
[pam_env.c:_assemble_line(315)] _assemble_line: line too long
[pam_env.c:_parse_config_file(179)] Exit. 
[pam_env.c:handle_env(847)] Exit.
```
This change was introduced by 563d21d6dbb6d64613919ccb1cc939bae546baab.
There is no mention of this change in the NEWS file.  Is this intended?

Downstream bug report https://bugs.archlinux.org/task/67636

**Comment by Serranya** [comment]
This also seems to happen with the following line:
`RXVT_SOCKET DEFAULT=${XDG_RUNTIME_DIR}/urxvtd.socket`

**Comment by loqs** [comment]
@t8m have you been able to take a look at this?

**Comment by loqs** [comment]
@ldv-alt and @t8m before Linux-PAM 1.5 is released could this issue please be resolved?
Would you accept a revert of 563d21d?

**Comment by t8m** [comment]
No, I do not think we should revert this.

**Comment by t8m** [comment]
Please try the PR #289 if it fixes your issue.
