### ISSUE TITLE
pam_unix: Improve PAM_USER_UNKNOWN test so that systemd-homed users are handled properly

### ISSUE THREAD

**Issue by chandradeepdey** [linux-pam/linux-pam#265]
With the current `pam_get_item(PAM_USER)` test systemd-homed users don't get `PAM_USER_UNKNOWN`ed, and then fail at a later point, returning some other error.

Workaround-
currently the `account pam_systemd_home.so` module has no workarounds since https://github.com/systemd/systemd/issues/16906. The first comment describes a pam configuration that doesn't work due to `pam_unix.so`'s handling of `PAM_USER_UNKNOWN`. The second comment describes a pam configuration that works with a fix there and no changes here.

`auth` and `password` modules return correctly with `PAM_USER_UNKNOWN` and `pam_unix.so` can be conditionally skipped as a workaround.

However, this means either forcing a specific order in the pam configuration (systemd-homed first, then unix), or losing the return value of both the modules with a `sufficient` and following it up with a `pam_deny.so`. This causes other issues with applications like `login` that check the return values for account expiry and stuff.

**Comment by oxr463** [comment]
This seems like an issue with systemd, not `pam_unix`. Feel free to submit a PR, of course.

**Comment by chandradeepdey** [comment]
> This seems like an issue with systemd, not `pam_unix`.

Not really, `account pam_unix.so` sends a `PAM_USER_UNKNOWN` from https://github.com/linux-pam/linux-pam/blob/9f24bbeeb4fe04bc396898cd9825478ad52c5ac7/modules/pam_unix/pam_unix_acct.c#L199 and https://github.com/linux-pam/linux-pam/blob/9f24bbeeb4fe04bc396898cd9825478ad52c5ac7/modules/pam_unix/pam_unix_acct.c#L202
The tests pass for systemd-homed users. It probably needs to determine which NSS database the user is actually mentioned in.

**Comment by t8m** [comment]
The pam_unix should return PAM_AUTHINFO_UNAVAIL for users that do not have /etc/shadow entry.
What do you see as the return value?

**Comment by chandradeepdey** [comment]
Oh, I didn't know that this was by design. Sorry.
