### ISSUE TITLE
Sandbox in a mount namespace systemd --user when pam_namespace is enabled

### ISSUE THREAD

**Issue by bobsaintcool** [linux-pam/linux-pam#268]
When enabling [pam_namespace(8)](https://www.man7.org/linux/man-pages/man8/pam_namespace.8.html) on my system I've hard time to make a use of user services started by systemd.

As `systemd --user` start service into a different mount namespace that the one the user is. 

Let's say that my `/etc/security/namespace.conf` is as the following:

```
HOME    $HOME/$USER.inst/     user
```

On the root mount namespace I'll have something like this:

```
# find /proc/1/root/home/
/proc/1/root/home/
/proc/1/root/home/user
/proc/1/root/home/user/.bash_profile
/proc/1/root/home/user/.cache
/proc/1/root/home/user/.cache/vim
/proc/1/root/home/user/user.inst
/proc/1/root/home/user/user.inst/user
/proc/1/root/home/user/user.inst/user/in_ns
/proc/1/root/home/user/user.inst/user/.bash_profile
/proc/1/root/home/user/user.inst/user/.cache
/proc/1/root/home/user/user.inst/user/.cache/vim
/proc/1/root/home/user/user.inst/user/.ssh
/proc/1/root/home/user/user.inst/user/.ssh/config
/proc/1/root/home/user/user.inst/user/.bash_history
/proc/1/root/home/user/user.inst/user/.bash_logout
/proc/1/root/home/user/user.inst/user/.lesshst
/proc/1/root/home/user/user.inst/user/.bashrc
/proc/1/root/home/user/.bash_history
/proc/1/root/home/user/.bash_logout
/proc/1/root/home/user/not_in_ns
/proc/1/root/home/user/.bashrc
```

If I'm looking what are the mntns setup if got two different (4026531840) for `systemd --user` and (4026532360) for the shell I
ran:

```
$ ps -u "$(id -u)" -o pid,user,mntns,command --sort mntns
PID USER          MNTNS COMMAND
442 user     4026531840 /usr/lib/systemd/systemd --user
480 user     4026532360 -bash
532 user     4026532360 ps -u 1000 -o pid,user,mntns,command --sort mntns
```

4026531840 seems to be the initial mnt namespace:

```
# ls -l /proc/1/ns/mnt
lrwxrwxrwx 1 root root 0 Sep 13 16:23 /proc/1/ns/mnt -> 'mnt:[4026531840]'
```

Thus, if I'm starting a user service it is executed within the initial mount namespace:

  - The service cannot use the data that the user see easily
  - The user cannot see the data generated by the service
  - The data generated by the service are not protected by the namespace

I will imagine a way (if possible) to execute user service within the polyinstantiated namespace instead of the initial namespace. That way it will be able to use and generate data usable for the sandboxed user.

I'm not sure if its something that can be done or if I just miss something in this particular setup.

I've also noted that running multiple session will lead each of them into different mnt namespace. Maybe there is a way to get a single mnt NS separated from the intial mnt ns?

I've considered adding something like `session required pam_namespace.so` into `/etc/pam.d/systemd-user` which seems used by `user@.service` but I'm not sure I'm not mess up doing so.

Unsure how it relevant or can be improve. It may probably be mentioned in the doc somewhere as systemd is now a common thing on most linux based system.

**Comment by hexchain** [comment]
If the ultimate goal is to share data between the interactive session and the `systemd --user` session, it can work when:

- `pam_namespace` is run for both sessions (e.g. the line is in `/etc/pam.d/system-login`, which is included by both the display manager/`/usr/bin/login` and `systemd-user`), and
- the poly-instantiate method is set to `user`, so the instance directory is consistent among sessions.

In this situation, both sessions will still have different mount namespaces, but they will share the same directory.

I don't think `tmpfs` or `tmpdir` method can work, unless e.g. `pam_namespace` is able to reuse poly-instantiated mount namespaces, maybe?

**Comment by bobsaintcool** [comment]
Thanks @hexchain for your detailed answer. I was looking at all my history trying figuring out what was the use case I wanted to achieve when creating this issue.

I believe you are right on the requirement for this to work when one want to achieve data sharing between interactive and user service.
In addition I'm not sure that the `tmpfs` or `tmpdir` can works here neither.

**Comment by bobsaintcool** [comment]
@hexchain  for information my initial issue at systemd side has been re-opened to add part of your suggestion :)
https://github.com/systemd/systemd/issues/17043#issuecomment-1325215370
