### ISSUE TITLE
pam_unix(dovecot:auth): user [...] has blank password; authenticated without it

### ISSUE THREAD

**Issue by fajabird** [linux-pam/linux-pam#284]
Hi,

since yesterday my mail server is sending massive spam and I try to figure out if my account has been hacked or there is an configuration failure with my server (postfix+dovecot running on arch). I found the following message in the logs even after changing the password for the user "USER":

pam_unix(dovecot:auth): user [USER@domain.com] has blank password; authenticated without it

and it seems that after this postfix allows to relay the incoming "spam" mails. 

btw. postfix is using dovecot as SASL provider and dovecot is configured to use PAM. PAM settings are default, i.e. 

using swaks-tool I was not able to generate same message on server side - even If I keep password empty. Any help is much appreciated. First question is: in what circumstances will the server generate this message and how can I reproduce it?

**Comment by t8m** [comment]
What do you see after calling `getent passwd USER` ?
Do you see x in the second field or is it empty?
If the field is empty, that is the problem.
Also removing nullok option from pam_unix.so command lines in /etc/pam.d/* files should help disabling this.

**Comment by t8m** [comment]
The correct command might be `getent passwd USER@domain.com`

**Comment by fajabird** [comment]
Hi - thanks for the feedback. I need to roll back my last change to test this I guess (or I leave it and wait if the issue reoccures) 

Here is the old and new content of /etc/pam.d/dovecot:

OLD:
auth include system-auth
account include system-auth
session include system-auth
password include system-auth

NEW:
auth      required        pam_unix.so
account   required        pam_unix.so

On Arch system-auth contains this line:
auth       [success=2 default=ignore]  pam_unix.so          try_first_pass nullok

So with the new config I should have archived what you wrote right?

**Comment by fajabird** [comment]
BTW. I never have seen this issue before - I have 3 mail servers setup the same way and the issue stated to show up 2 days ago when I was notified via abuse-mail that I'm sending spam. This might become bigger - maybe hackers found a way to trigger this behaviour in postfix/dovecot SASL implementation. 
All dovecot how-tos I found are suggesting to have "nullok" in /etc/pam.d/dovecot 

BTW using the tool swaks I was not able to trigger this message manually - so no idea how this guys are doing this. I tried it with the same user-id and no password or empty password - this all resulted in:

auth[1676]: pam_unix(dovecot:auth): authentication failure; logname= uid=0 euid=0 tty=dovecot ruser=user@domain.com rhost=IP
auth[1676]: pam_unix(dovecot:auth): check pass; user unknown

**Comment by fajabird** [comment]
Here is the full log of the issue (filtered on that id 1139735):

auth[1139735]: pam_faillock(dovecot:auth): User unknown
auth[1139735]: pam_unix(dovecot:auth): user [user@domain.com] has blank password; authenticated without it
auth[1139735]: pam_faillock(dovecot:auth): User unknown
dbus-daemon[34]: [system] Activating via systemd: service name='org.freedesktop.home1' unit='dbus-org.freedesktop.home1.service' requested by ':1.4855' (uid=0 pid=1139735 comm="dovecot/auth -w ")
auth[1139735]: pam_systemd_home(dovecot:account): systemd-homed is not available: Unit dbus-org.freedesktop.home1.service not found.

**Comment by t8m** [comment]
Removal of nullok should definitely prevent authentication of users with blank password so that should mitigate your problem.

However the logs are really suspicious. No need to revert any configuration changes but I'd really recommend to you to inspect the output of `getent passwd USER@domain.com` and `getent shadow USER@domain.com` commands on the affected system.

**Comment by fajabird** [comment]
Thanks. At no time I could find that user with the domain-suffix in /etc/passwd or /etc/shadow, without the suffix the user exists though:

`getent passwd USER@domain.com` -> no result
`getent shadow USER@domain.com` -> no result

`getent passwd USER` -> 1 result
`getent shadow USER` -> 1 result

**Comment by t8m** [comment]
And what about the second field (after first `:`) in these records? Is any of these two empty? I am slightly afraid of the interaction with pam_systemd_home and the systemd-homed service.

For example - this is imaginary scenario, so I do not really know if it is really like that - if the systemd-homed created the USER@domain.com entry on login with empty password hash field in passwd or shadow databases, then this would be the expected behavior. It would be of course a serious bug in the systemd-homed service to create passwd or shadow entries with empty password hash fields.

**Comment by fajabird** [comment]
So "USER" is a normal user on that system with a valid password - thus in shadow second field is not empty. Was this your question?

**Comment by loqs** [comment]
Can you reproduce the issue with https://github.com/systemd/systemd/commit/842067e6753d8cad951c83ac62681c539e1b1a07 applied?

**Comment by fajabird** [comment]
Unfortunately i was not able to reproduce the issue at all, manually. The only thing I could do right now is to revert the last change to reintroduce bullock and than wait for the hackers to come. 

If you have an idea how I can reproduce the issue locally I will do.

**Comment by robsonde** [comment]
If you are running Archlinux it is very likely this is the result of a change in May 2020.


Back in May 2020 there was a change to root account in shadow file such that root with no password was no longer supported.

During patching this created a file /etc/shadow.pacnew 

If that pacnew was not merged to the shadow file this will result in pam allowing any invalid account to successfully auth with no password.

The problem is that if the * is missing from the root line in the shadow file then the most recent pam system-auth config will allow auth bypass.

This impacted me when my mail server (dovecot/postfix) got breached via a “no password” and sent significant spam.

Go check if you have a * in the root line in your shadow file. You need it to fix this bug on Archlinux.

**Comment by fajabird** [comment]
@robsonde your input is very much appreciated and confirms what was my gut feeling - this is a VERY serious SECURITY ISSUE - devs should raise the priority of this to the maximum.

**Comment by lnicola** [comment]
@robsonde is `!` fine too?

**Comment by fajabird** [comment]
@robsonde my shadow root line looks like this:

root:$HASH:18166::::::

the pacnew file looks like this:

root:*:14871::::::

as I'm using the root account there was never an empty password for root - I'm I still affected? What do I need to do?

**Comment by Frederick888** [comment]
The change mentioned by @robsonde can be found at: archlinux/svntogit-packages@2d5af94ae55a5c98837ce9631f331ad2aad32bb3. I don't see how this makes a difference? If your root's got an empty password, authentication attempts made by root seem to always succeed both before and after this change, even if the account doesn't exist. For example, one could try:

```sh
# run as root
$ pamtester -v system-auth nonexist authenticate
```

So I think the best practice here is:

1. Avoid using root for Dovecot auth-worker. Arch's Dovecot hasn't got a default configuration file, but from Ubuntu's I can see:

```
service auth-worker {
  # Auth worker process is run as root by default, so that it can access
  # /etc/shadow. If this isn't necessary, the user should be changed to
  # $default_internal_user.
  #user = root
}
```

2. Set a root password or use `*` / `!` in shadow to disable root authentication via unix password according to `man 5 shadow`:

```
encrypted password
   This field may be empty, in which case no passwords are required to authenticate as the specified login name. However, some applications which read the /etc/shadow file may decide not to permit any access at all if the password field is empty.

   A password field which starts with an exclamation mark means that the password is locked. The remaining characters on the line represent the password field before the password was locked.

   Refer to crypt(3) for details on how this string is interpreted.

   If the password field contains some string that is not a valid result of crypt(3), for instance ! or *, the user will not be able to use a unix password to log in (but the user may log in the system by other means).
```

However if I understand correctly, this is not related to @fajabird's issue.

**Comment by Frederick888** [comment]
@fajabird One thing that just popped up in my mind -- which might be a stupid question to ask -- what about your `/etc/passwd`? Is the password column for root `x`?

**Comment by fajabird** [comment]
root:x:0:0::/root:/bin/bash

**Comment by kyrias** [comment]
I've found the cause of this, will send a patch for it Soon™.

**Comment by t8m** [comment]
@fajabird unless your system had at some point blank password hash field for root in /etc/passwd or /etc/shadow your issue should not be caused by #298 / #300.

**Comment by yeupou** [comment]
Hello,

Same issue, same effect: there are clearly bot targetting servers using root with blank password.

On LXC containers, it is not uncommon to have such blank password.

usermod -p '!' root
should solve this but the defaut config clearly allows it with software like dovecot 

grep nullok /etc/pam.d/ -R
/etc/pam.d/common-auth:auth	[success=1 default=ignore]	pam_unix.so nullok

grep common-auth /etc/pam.d/ -R
/etc/pam.d/dovecot:@include common-auth
...
