### ISSUE TITLE
pam_tally2 count not resetting once unlock_time is complete 

### ISSUE THREAD

**Issue by Uttakarsh1996** [linux-pam/linux-pam#288]
I was trying to use pam_tally2 to lock users for a specified period of time. 
auth    required    pam_tally2.so even_deny_root deny=3 unlock_time=30
account    required    pam_tally2.so

The locking feature works as expected i.e. after 3 unsuccessful attempts the user is getting locked out for 30 seconds. My issue is once unlock time is complete the count is not reset to 0. Thus it allows the user only 1 attempt to login once lockout time is complete rater than 3. If the user fails to login successfully it gets locked out with just 1 permitted attempt rather than 3. 
This behavior is not seen if user logs in successfully as the count goes back to zero.

Shouldn't the count go back to zero immediately once lockout time is over as I don't want to reset the failed attempts for a user manually.
Please let me know if this expected behavior? If not am I missing something in my config.
If yes doesn't it defeat the purpose of setting an unlock time if the count is not getting reset automatically once time is complete.

**Comment by ldv-alt** [comment]
pam_tally2 module was deprecated in 1.4.0 and removed later by commit 709e37b7e131d35b0ec30d31f858bc6917dd2b2e.
pam_faillock module was added in 1.4.0, consider using it instead of pam_tally2.

**Comment by Uttakarsh1996** [comment]
Thanks for the clarification, sorry couldn't respond earlier. Just wanted to know that whether the scenario I have mentioned would be covered by pam_faillock module or not?

**Comment by t8m** [comment]
In case of pam_faillock the module records each login failure (with some limit on the number of records) and it will simply ignore the failures older than the unlock_time.

**Comment by Uttakarsh1996** [comment]
Thanks for helping me out. Really appreciated.
