### ISSUE TITLE
New password strings are untranslatable

### ISSUE THREAD

**Issue by piotrdrag** [linux-pam/linux-pam#29]
Strings in https://github.com/linux-pam/linux-pam/blob/master/libpam/pam_get_authtok.c#L40 and https://github.com/linux-pam/linux-pam/blob/master/modules/pam_cracklib/pam_cracklib.c#L67 are not translatable to many languages. For example, in Polish we need to put %s%s after “password” for the sentence to make grammatical sense, which results in “Nowe hasło : ”, and that’s incorrect punctuation.

These strings should be split into two versions: one with “`<service>` ”, and one without.

The same issue is in https://github.com/libpwquality/libpwquality/issues/3

**Comment by piotrdrag** [comment]
It would be really great to resolve this problem — and it should be a relatively easy fix.

**Comment by ldv-alt** [comment]
Yes, the issue affects many languages, and the fix is going to be straightforward.
I'll prepare a patch.

**Comment by piotrdrag** [comment]
Thank you, I really appreciate it!
