### ISSUE TITLE
pam_faillock sets a delay unconditionally

### ISSUE THREAD

**Issue by tavianator** [linux-pam/linux-pam#295]
pam_faillock.so sets a delay unconditionally here: https://github.com/linux-pam/linux-pam/blob/11a8fda7911f5e17448d148734aaa4ddb8b19b75/modules/pam_faillock/pam_faillock.c#L657

I have `nodelay` set for pam_unix, so I don't want a delay.  But there doesn't seem to be a setting to disable the delay that pam_faillock introduces.

**Comment by t8m** [comment]
Adding a nodelay option support to pam_faillock would be a nice PR if someone wants to contribute.
