### ISSUE TITLE
OPT pam_wheel for checking the user in AD(Active Directory)

### ISSUE THREAD

**Issue by jinleiw** [linux-pam/linux-pam#297]
I login linux via AD authentication.

For example, a user named "jin", group named "xts", both are in AD:

```
# id jin    <==== "jin" is a AD user
uid=30000(jin) gid=30000(domain users) groups=30000(domain users),30001(xts),30005(yjs)
```

a local user named "test", local group named "xts":

```
# id test
uid=1000(test) gid=1000(test) groups=1000(test),1003(xts)
```

If i config `/etc/pam/d/su` like:

```
...
# only permit the users which is member of xts can "su root"
auth            required        pam_wheel.so use_uid group=xts root_only
...
```

For local user who is member of xts, `su - root` is OK

But for AD user who is member of xts, `su - root` got permission denied.

So, why not check a user which group it belong to like the `id` command, but not like this:

```
...
    if (is_on_list(grp->gr_mem, fromsu) || (tpwd->pw_gid == grp->gr_gid)) {
...
```

because when get the group's info, if the group is in AD, can not get the members of the group~

Thanks~

**Comment by jinleiw** [comment]
The source code path: linux-pam/modules/pam_wheel/pam_wheel.c, line 203

Anyone can help me? Please~

**Comment by t8m** [comment]
Your proposal would not solve it for user where the "wheel" group is not their primary group.

**Comment by t8m** [comment]
The change in PR #302 should fix it.
