### ISSUE TITLE
Stack processing continues through done if impression is negative

### ISSUE THREAD

**Issue by rowlap** [linux-pam/linux-pam#307]
The documented definition of action `done` is
>   equivalent to ok with the side effect of terminating the module stack and PAM immediately returning to the application.

However, in certain circumstances the stack will continue beyond `done`.

Example service configuration, "pambug":
```
# pam_deny returns PAM_AUTH_ERR
account  required                      pam_deny.so

# pam_permit returns PAM_SUCCESS
account  [success=done default=die]    pam_permit.so
# Q: why don't we stop here?
# the done / die options in the line above are both "decisive"

# if the pam_deny line above is commented out, this pam_echo is not invoked
account  optional                      pam_echo.so Unreachable
````
What happens?
The `pam_echo` line is executed.

What is expected?
The `pam_permit` line should stop execution.
The presence or absence of the `pam_deny` line should not affect whether `pam_echo` is called.

**Comment by rowlap** [comment]
The example given is a minimal test case, but the practical impact of this was in a substack where the lines following the `done` test had side effects which were intended to be guarded.

My basic analysis is that following https://github.com/linux-pam/linux-pam/blob/master/libpam/pam_dispatch.c#L209 the `goto decision_made;` is conditional on `impression` being positive. If we enter a test with negative `impression`, `done` cannot terminate on success.

**Comment by t8m** [comment]
Yes, we should clarify this in the documentation.

**Comment by rowlap** [comment]
Thanks for the edit. I wasn't expecting, simply for backward-compatibility, that the pam_dispatch behaviour would change.

What's the cleanest way to do-what-i-mean - i.e. stop regardless of `impression`? The best I can come up with is a jump over the side-effect parts of the stack to an optional pam_deny.

**Comment by t8m** [comment]
Yes, I have no better idea. Except I think you can just jump over all the remaining modules - there does not need to be the optional pam_deny module.
But please be aware that you need to somehow get the positive `impression`, which means you need to have some required module that succeeded before the module triggering the jump.
