### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by qcq** [linux-pam/linux-pam#318]
under modules/pam_faillock/main.c
in line 80, seems mixtured Tab with apace, which make me uncomforable
in line 132 -> line 151
why need to define int audit_fd to 133, which used in in line 143, which cause used two macro, which makes code ugly.

**Comment by t8m** [comment]
Please feel free to submit pull requests that improve code style, they will be considered.

As for the other issue - it has to be done this way because we do not allow declarations intermixed with other code. So that one has to stay as is.

**Comment by qcq** [comment]
`for the second issue, I mean why not change to below, which can remove one moacro which useless

original:
`	if (opts->reset) {
#ifdef HAVE_LIBAUDIT
		int audit_fd;
#endif

		while ((rv=ftruncate(fd, 0)) == -1 && errno == EINTR);
		if (rv == -1) {
			fprintf(stderr, "%s: Error clearing the tally file for %s:",
				opts->progname, user);
			perror(NULL);
#ifdef HAVE_LIBAUDIT
		}
		if ((audit_fd=audit_open()) >= 0) {
			audit_log_acct_message(audit_fd, AUDIT_USER_MGMT, NULL,
				"faillock-reset", user,
				pwd != NULL ? pwd->pw_uid : AUDIT_NO_ID,
				NULL, NULL, NULL, rv == 0);
			close(audit_fd);
		}
		if (rv == -1) {
#endif`


modify to

`#ifdef HAVE_LIBAUDIT
		}
		int audit_fd;
		if ((audit_fd=audit_open()) >= 0) {
			audit_log_acct_message(audit_fd, AUDIT_USER_MGMT, NULL,
				"faillock-reset", user,
				pwd != NULL ? pwd->pw_uid : AUDIT_NO_ID,
				NULL, NULL, NULL, rv == 0);
			close(audit_fd);
		}
		if (rv == -1) {
#endif`

**Comment by qcq** [comment]
yes, pull requested, help me check it.
for the second issue, seems you misunderstand my meaning

**Comment by t8m** [comment]
No, I understand it well. We do not allow declarations intermixed with other code as you did in your PR.
