### ISSUE TITLE
Define pam_fscrypt.so always before pam_systemd.so in common-session to avoid hanging systemd user services

### ISSUE THREAD

**Issue by 1989gironimo** [linux-pam/linux-pam#321]
(I'm not really sure, where this issue should be filed so bear with me if this git is the wrong one)

Having systemd and fscrypt with encrypted /home leads to several issues regarding systemd services.
They cannot start if /home isn't decrypted before systemd tries to start those services, for instance:

`>>> systemctl --user status ssh-agent.service
ssh-agent.service - SSH key agent
     Loaded: loaded (/home/user/.config/systemd/user/ssh-agent.service; enabled; vendor preset: enabled)
     Active: inactive (dead)`
     
This issue pretty much sums it up: https://github.com/google/fscrypt/issues/247

Editing /etc/pam.d/common-session manually (moving pam_fscrypt.so right before pam_systemd.so) fixes this, but this got reset after the last update, because I already forgot about the manual edit and ignored the warning.

**Comment by t8m** [comment]
The system pam configuration files are set up by the individual distributions shipping the Linux-PAM  such as Ubuntu, Debian, RHEL, Fedora... Please report the issue to the issue reporting system for the distribution where you see the issue. We cannot do anything with the report here.
