### ISSUE TITLE
Correctly handle "1 minute left to unlock"

### ISSUE THREAD

**Issue by Razzeee** [linux-pam/linux-pam#322]
At the moment we always show `1 minutes left to unlock` when it should be `minute`. I also believe, that there are some languages, that have other special numbers (https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#Polish) but that might be way harder to do.

**Comment by ldv-alt** [comment]
On Wed, Jan 20, 2021 at 06:20:52PM -0800, Razzeee wrote:
> At the moment we always show `1 minutes left to unlock` when it should be `minute`. I also believe, that there are some languages, that have other special numbers (https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals#Polish) but that might be way harder to do.

We already use dngettext in pam_lastlog.c and pam_unix_acct.c,
it is not hard at all.
