### ISSUE TITLE
How to set empty password in pam_unix.so?

### ISSUE THREAD

**Issue by arekmd** [linux-pam/linux-pam#325]
Hi, 

Is there any way to set empty password (or delete password) using pam_unix? 
I can change password to non-empty using "pam_chauthtok" function.

This is what i got, when I try to set empty string as password:

```
New password: 
Password change aborted.
Authentication token manipulation error
```
My config:
```
#%PAM-1.0
auth    required    pam_unix.so nullok nodelay debug 
account required    pam_unix.so debug 
password required    pam_unix.so debug  nullok
session required    pam_unix.so debug 
```

**Comment by t8m** [comment]
No, AFAIK there is no way to do that via PAM.

You can use `passwd -d` or `usermod -p ''` to set empty password for user, but you can do that only as root.

**Comment by arekmd** [comment]
Thank you for your answer t8m.

I checked the source code, and I think you're right.
