### ISSUE TITLE
pam_exec parameter 'quiet' writing error to syslog even if manpage implies to does not

### ISSUE THREAD

**Issue by adrelanos** [linux-pam/linux-pam#329]
Manpage quote:

> quiet
> Per default pam_exec.so will echo the exit status of the external command if it fails. Specifying this option will suppress the message. 

Source code https://github.com/linux-pam/linux-pam/blob/master/modules/pam_exec/pam_exec.c#L272

```
	      pam_syslog (pamh, LOG_ERR, "%s failed: exit code %d",
			  argv[optargc], WEXITSTATUS(status));
		if (!quiet)
	      pam_error (pamh, _("%s failed: exit code %d"),
			 argv[optargc], WEXITSTATUS(status));
```

That looks wrong to me. I would expect when `quiet` is used to not write an error message to syslog.

**Comment by t8m** [comment]
No, it is not wrong according to the manpage as the manpage talks about echoing the status which implicates echoing it to the user via the pam_error(). The manpage does not talk about the syslog at all. It would have to be a new option if anything.

**Comment by adrelanos** [comment]
What would be a good name for that since `quiet` is already taken?

**Comment by t8m** [comment]
For example `quiet_log`. @ldv-alt any different opinion?

**Comment by ldv-alt** [comment]
`quiet_log` is OK.

**Comment by adrelanos** [comment]
Alright, therefore this ticket of mine is invalid.
Created https://github.com/linux-pam/linux-pam/issues/334 for what is actually not a bug but a feature request.
