### ISSUE TITLE
Cloud-init target doesn't load while booting after changing common-password, Ubuntu 20.04 VM

### ISSUE THREAD

**Issue by RyanNgCT** [linux-pam/linux-pam#332]
**Linux VM, Versioning:**
![Screenshot 2021-02-09 211824_LI](https://user-images.githubusercontent.com/48358569/107370150-900e1e00-6b1d-11eb-8403-8039849e988d.jpg)

**Issue:**
After adding the following parameters in [this article](https://linuxhint.com/secure_password_policies_ubuntu/) in `/etc/pam.d/common-password` and rebooting the server, it hangs at `Reached target Cloud-init target`. Already tried restarting and shutting down the vm and powering on again. Only way to resolve issue is to revert snapshot. Also tried the solutions listed [here](https://serverfault.com/questions/1016349/boot-issue-on-clean-ubuntu-server-20-04-system) to no avail
```
password        requisite
pam_pwquality.so retry=4 minlen=9 difok=4 lcredit=-2 ucredit=-2 dcredit=
-1 ocredit=-1 reject_username enforce_for_root
```

![Image 2021-02-09 at 20 25 26](https://user-images.githubusercontent.com/48358569/107369920-49b8bf00-6b1d-11eb-9c94-7259e003bb4d.jpeg)

**Comment by ldv-alt** [comment]
Sorry, this is not a support forum, please direct your question elsewhere.
