### ISSUE TITLE
Update shadow field 5 to MAX_PASS_DAYS

### ISSUE THREAD

**Issue by joseph-reynolds** [linux-pam/linux-pam#336]
Would it be possible to add a new parameter to the pam_unix module to update shadow field 5 ("days before change required") to the value in `/etc/login.defs` `PASS_MAX_DAYS` variable when the password is successfully changed?  Alternatively, would it be better to have a separate module handle this?

Example usage:
```pam
password	[success=ok default=die]	pam_pwquality.so debug
password	[success=1 default=die]	pam_unix.so sha512 use_authtok update-days-before-change-required-from-MAX_PASS_DAYS=/etc/login.defs
password	requisite			pam_deny.so
password	required			pam_permit.so
```

**Comment by t8m** [comment]
What would be the concrete use case? I mean why you wouldn't want to actually do that as sysadmin explicitly when you decide to set this PASS_MAX_DAYS value?

Why would you allow the users to live with the existing password for indefinite time but then force them to change it periodically after they update it for the first time?

I think it should be possible to achieve this functionality with pam_exec and using the usermod command from a script. However it would be probably fragile and I am not sure how much secure.

**Comment by joseph-reynolds** [comment]
My proposal above is the most obvious way to implement a proposed specification using Linux-PAM.  I can't discuss the spec because it is currently private, but it says (excerpted & paraphrasing) to reset the local user account's _days before change required_ to the default value whenever their password changes.  I invite comments on that spec. 

Thanks for the reference: using pam_exec would work.

**Comment by t8m** [comment]
I am not sure we want to support arbitrary specifications which have no public reasoning behind them by adding extra specific features for such specifications.

If something has a generally acceptable use case, then it makes sense to add such feature but otherwise it is just adding maintenance burden.

**Comment by joseph-reynolds** [comment]
Thanks for the explanations.  Closing this issue.
