### ISSUE TITLE
example misleading

### ISSUE THREAD

**Issue by Lewiscowles1986** [linux-pam/linux-pam#34]
In https://github.com/linux-pam/linux-pam/blob/master/examples/check_user.c#L43 there is a comment in the code. `/* permitted access? */`

The man page says

> The pam_acct_mgmt function is used to determine if the users account is valid. It checks for authentication token and account expiration and verifies access restrictions. It is typically called after the user has been authenticated.

I'm not sure if the comment is needed, or if it should just link to https://linux.die.net/man/3/pam_acct_mgmt or another manpage source. 

I Found it a little confusing at first.

**Comment by t8m** [comment]
I am not sure why it would be confusing.
