### ISSUE TITLE
pam_tally2 & ChallengeResponseAuthentication yes

### ISSUE THREAD

**Issue by jiangqii** [linux-pam/linux-pam#341]
Although the latest version of PAM_ Tally2 has been cancelled, but many machines still use pamtally2.
 There is a problem here. When I use SSH, I want to display the message "account locked due to failed logins..." returned by pamtally2so. 

So I changed the parameter of sshd_config`
```
challengeresponseauthentication yes 
```
and changed the file / etc / pam.d/sshd.
```
auth required PAM_ tally2.so deny=3.
```
Then, log in with SSH, but I haven't entered my password, PAM_ Tally2 shows that the current user failed once

https://access.redhat.com/solutions/29233

NOTHING FOUND!

**Comment by jiangqii** [comment]
Maybe this.https://github.com/linux-pam/linux-pam/issues/71.

But is there a solution？

**Comment by ldv-alt** [comment]
Apparently, nobody is going to handle questions about pam_tally2 which was removed in 1.5.0 release.
