### ISSUE TITLE
Ubuntu Focal Apache2 

### ISSUE THREAD

**Issue by mfones** [linux-pam/linux-pam#344]
Command sudo sevice apahe2 restart failed. 
journactl -ex ...
pam_unix(sudo:auth): Couldn't open /etc/securetty: No such file or directory

**Comment by mfones** [comment]
Turns out ngnx was running at the same time. Shutting down nginx allowed apache to run. So I believe the error message has no impact on running apache.

**Comment by t8m** [comment]
Closing as this is not a bug in upstream Linux-PAM project.
