### ISSUE TITLE
expired SSL/TLS certificate on www.linux-pam.org

### ISSUE THREAD

**Issue by donfede** [linux-pam/linux-pam#346]
As of 2021-April, the website for linux-pam has an invalid SSL/TLS certificate, that expired circa 2012.  This limits user access to online Linux PAM documentation and information.

Please either replace the linux-pam certificate with an updated one, such as using the freely available https://letsencrypt.org/ website, or at least remove the invalid certificate.

Website addresses affected:
- www.linux-pam.org
- linux-pam.org

**Comment by ldv-alt** [comment]
Seems to be fixed.
