### ISSUE TITLE
install-dependencies.sh not installs dependencies for fedora.

### ISSUE THREAD

**Issue by AliyevH** [linux-pam/linux-pam#362]
install-dependencies.sh not works for fedora. only apt supports. Is there any script to install dependencies for fedora. if not i would like to send pr for it.

**Comment by ldv-alt** [comment]
ci/install-dependencies.sh is a script written for ci which used to be travis ci, now it's github actions, both provide environments based on ubuntu.  Is there any value in extending ci/install-dependencies.sh to support other distributions?

**Comment by AliyevH** [comment]
Thanks for response.
Ye, today i tried to install dependencies to build from source code for fedora. But it is very hard to install all this manually, that's why i think it could be good to include some automation script for dependencies.

**Comment by t8m** [comment]
I'd recommend using dnf builddep on the Fedora pam src.rpm package to install the build dependencies needed to build the upstream Linux pam.
