### ISSUE TITLE
Why using sftp successfully logined system, the output of pam_tally2 --user increase 1 every time?

### ISSUE THREAD

**Issue by okayabc** [linux-pam/linux-pam#377]
Sftp user name is sftpuser, before login into system, execute the following command:

linux-my7i:~ # pam_tally2 --user sftpuser --reset
Login           Failures Latest failure     From
sftpuser            7    07/14/21 10:09:02  172.16.70.82
linux-my7i:~ # pam_tally2 --user sftpuser
Login           Failures Latest failure     From
sftpuser            0    
Then use sftp command to login as:

linux-my7i:~ # sftp sftpuser@172.16.70.82
Password: 
Connected to 172.16.70.82.
sftp> exit
We can see login system successfully. Then pam_tally2 --user, the output is:

linux-my7i:~ # pam_tally2 --user sftpuser
Login           Failures Latest failure     From
sftpuser            1    07/14/21 10:15:26  172.16.70.82
Why the failure count increase 1 every time?

**Comment by t8m** [comment]
There can be various reasons. Most probably PAM stack misconfiguration for ssh/sftp.

**Comment by okayabc** [comment]
Where i can check the misconfiguration?
