### ISSUE TITLE
libpam_misc/misc_conv.c:329:19: warning: the address of 'binary_prompt' will always evalua te as 'true'

### ISSUE THREAD

**Issue by garrymar** [linux-pam/linux-pam#38]
Hello,

After last update of Gentoo GNU/Linux I caught following warning:

/var/tmp/portage/sys-libs/pam-1.3.0-r1/work/Linux-PAM-1.3.0/libpam_misc/misc_conv.c:329:19: warning: the address of 'binary_prompt' will always evalua
te as 'true' [-Waddress]

Thanks.

**Comment by t8m** [comment]
The warning is harmless, it would convolute the code if we tried to avoid it. The warning is coming from macro which cannot know whether it has a normal non-constant pointer as first argument and needs to test it for NULL or whether it is address coming from & operator which cannot be NULL.
