### ISSUE TITLE
Documentation needs updated for pam_set_item

### ISSUE THREAD

**Issue by mllegoman** [linux-pam/linux-pam#380]
Using `pam_set_item()` for setting items:
PAM_RHOST
PAM_AUTHTOK
PAM_OLDAUTHTOK
PAM_RUSER
PAM_USER_PROMPT

returns op-code 29 (PAM_DOMAIN_UNKNOWN).

There is also an undocumented item with integer definition 12 which I'm left scratching my head over.

(Not that this is in any way related to the issue but...)
Generally attempting to login as a user with a set password is virtually impossible (I'm guessing this is intentional), in any other context other than console/tty/pts logins.
I was wondering as to the purpose of this functionality.

**Comment by ldv-alt** [comment]
On Sat, Jul 24, 2021 at 07:39:01PM -0700, MLouden wrote:
> Using `pam_set_item()` for setting items:
> PAM_RHOST
> PAM_AUTHTOK
> PAM_OLDAUTHTOK
> PAM_RUSER
> PAM_USER_PROMPT
> 
> returns op-code 29 (PAM_DOMAIN_UNKNOWN).

In linux-pam, return value 29 means PAM_BAD_ITEM, see
https://github.com/linux-pam/linux-pam/blob/master/libpam/include/security/_pam_types.h

PAM_DOMAIN_UNKNOWN is provided by an alternative PAM implementation, see
https://www.openpam.org/browser/openpam/trunk/include/security/pam_constants.h

**Comment by mllegoman** [comment]
Oops. Looks like I got my sources a little mixed up. My bad.
I'm still confused though as to how I would set the password as an item. Would I need to write my own pam module, like it says here:

**Comment by mllegoman** [comment]
Not an actual issue
