### ISSUE TITLE
Is it possible to record unlock log in pam

### ISSUE THREAD

**Issue by StevenYGui** [linux-pam/linux-pam#387]
If we try 3 times to login by wrong password, account will be locked about 300s.

And I can find out the locking log in log file, like：
“Aug 23 05:33:19 localhost sshd[884]: pam_faillock(sshd:auth): Consecutive login failures for user root account temporarily locked”

But I can not find out unlock log after 300s.

So is it possible to add some logs when the account is unlocked after 300s?

**Comment by t8m** [comment]
As the unlock is simply done by expiration of the failed login attempts entries in faillock databases, it is not easily possible to do such logs. There would have to be a daemon that would monitor the faillock database files and created the log message once the entries expire. So no, it is not implemented and probably will not be as it is not so useful. You can just count the 300s after the lock event is logged.

**Comment by StevenYGui** [comment]
got it, thanks
