### ISSUE TITLE
pam_cracklib doesn't verify for reverse of old password

### ISSUE THREAD

**Issue by ssingam1** [linux-pam/linux-pam#39]
Hi,

It is strange and security concern that reverss of old password is accepted as new password.

Man page says

"Rotated
Is the new password a rotated version of the old password?
"
pam_cracklib actually verifies if new password is rotated version of old password but only anti-clockwise rotation but not clockwise. If clockwise rotation check is also done (case-insensitive), then reverse of old password will not be accepted as well as other weaker passwords based on clockwise rotation.

For example, if old password is XYZ, below new passwords are not accepted.
XYZ
YZX
ZXY

But it accepts below new passwords,
ZYX
YXZ
XZY

**Comment by ssingam1** [comment]
Actual password we were trying are
Old password : qweasdzxc
New password: cxzdsaewq

**Comment by ldv-alt** [comment]
pam_cracklib module was deprecated in 1.4.0 and removed later by commit d702ff714c309069111899fd07c09e31c414c166.
