### ISSUE TITLE
Faillock default directory usage is not consistent

### ISSUE THREAD

**Issue by Konrad-Ziarko** [linux-pam/linux-pam#390]
Hi
My issue is that faillock does not read `dir` value from `/etc/security/faillock.conf` when invoking `faillock` command without arguments.
I would expect that value `dir` in configuration is the default value.

Right now faillock is working a little unexpectedly:  
- On failed login, faillock uses `dir` from `/etc/security/faillock.conf` to store data.  
- When I invoke command `faillock` without arguments, it uses `dir=/var/run/faillock`.  
I have to specify `--dir` which is logical but I would expect `dir` from config file to be set as default for operations.

Is there any logical reason why it works this way?
> pam-1.3.1-14.el8.x86_64

**Comment by Konrad-Ziarko** [comment]
As I see in code `opts->dir = FAILLOCK_DEFAULT_TALLYDIR;` is set whenever argument `--dir` was not provided.
So it seems like this change would require inserting `read_config_file()` into `args_parse` function.

**Comment by t8m** [comment]
Yes, would you like to submit a PR?

**Comment by ldv-alt** [comment]
> As I see in code `opts->dir = FAILLOCK_DEFAULT_TALLYDIR;` is set whenever argument `--dir` was not provided. So it seems like this change would require inserting `read_config_file()` into `args_parse` function.

`args_parse` invokes ``read_config_file` since commit fc867a9e2, this issue seems to be resolved.

**Comment by Konrad-Ziarko** [comment]
it seems so; waiting for new pam release
