### ISSUE TITLE
auth pam_unix allows login on null password

### ISSUE THREAD

**Issue by rmackinnon** [linux-pam/linux-pam#391]
I noticed recently I had been receiving `pam_unix(sudo:auth): conversation failed` errors while trying to sudo
up some root consoles from my user.

```
Oct 03 16:32:26 linuxsys sudo[11766]: pam_unix(sudo:auth): conversation failed
Oct 03 16:32:26 linuxsys sudo[11766]: pam_unix(sudo:auth): auth could not identify password for [localuser]
```

Some digging and testing to diagnose this problem actually led me to discover something
horrifying (Happy Spooktober everyone), `null` passwords for any valid user were allowing login.
Upside, invalid passwords failed and valid password still succeeded.

Installed versions:
sys-libs/pam-1.5.1
sys-libs/pambase-20210201.1

Login via sudo:
```
localuser@linuxsys$ sudo whoami
Password:\n
root
```

`journalctl -n`
```
Oct 03 17:04:35 linuxsys sudo[14766]: pam_unix(sudo:auth): authentication failure; logname= uid=1001 euid=0 tty=/dev/pts/3 ruser=localuser rhost=  user=localuser
Oct 03 17:04:35 linuxsys sudo[14766]: localuser : TTY=pts/3 ; PWD=/home/localuser ; USER=root ; COMMAND=/bin/su root
Oct 03 17:04:35 linuxsys sudo[14766]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=1001)
Oct 03 17:04:35 linuxsys su[14769]: Successful su for root by root
Oct 03 17:04:35 linuxsys su[14769]: + /dev/pts/3 root:root
Oct 03 17:04:35 linuxsys su[14769]: pam_unix(su:session): session opened for user root(uid=0) by (uid=0)
Oct 03 17:04:43 linuxsys su[14769]: pam_unix(su:session): session closed for user root
Oct 03 17:04:43 linuxsys sudo[14766]: pam_unix(sudo:session): session closed for user root
```

Standard login:
```
root@linuxsys# login localuser
Password:\n
localuser@linuxsys$
```

`journalctl -n`
```
Oct 04 00:47:58 linuxsys login[50691]: pam_unix(login:auth): authentication failure; logname=localuser uid=0 euid=0 tty=/dev/pts/4 ruser= rhost=  user=localuser
Oct 04 00:47:58 linuxsys login[50691]: pam_unix(login:session): session opened for user localuser(uid=1001) by localuser(uid=0)
```

`/etc/pam.d/system-auth`
```
auth		required			pam_env.so
auth            [success=1 default=ignore]      pam_unix.so try_first_pass
auth		optional			pam_cap.so

account		required			pam_unix.so

password	required			pam_passwdqc.so config=/etc/security/passwdqc.conf
password	required			pam_unix.so try_first_pass use_authtok sha512 shadow

session		required			pam_limits.so
session		required			pam_env.so
session		optional			pam_mktemp.so
session		required			pam_unix.so
```

Solution and Diagnosis:
Through some troubleshooting I found that the setting for `[success=1 default=ignore]` in `system-auth`
for `pam_unix.so` results in any null value password, for any valid user, allowed bypassing.  The
work-around/fix here is to set this line to `required`, as I believe the `default=ignore` was resulting
in the password checking being bypassed. You could enter a valid password and things would check
and allow login, and invalid passwords were bounced out. That whole part, great.  But if the password supplied
was `null`, as seen above, `pam_unix.so` would fail (not great), be ignored, and proceed to session
creation and command prompt (horrifyingly not great).

I think this is probably mostly a Gentoo bug (which I'll cross post an issue to their bugzilla after
this as I believe they are doing the defaulting to success/default), but uncertain if this is the intended function of the
auth feature of `pam_unix.so`? FYI adding `debug` or `audit` options didn't really help me diagnosis this
deeper. Now that I can reproduce this, anything you'd want me to test and give results for?

**Comment by t8m** [comment]
This is just a crazy pam stack configuration, and yeah, you can probably get all sorts of various results from that stack. And no, we cannot _fix_ the pam library or pam_unix to not produce weird results with such incorrect configuration.
To correct the stack it would be sufficient to put a pam_deny.so module after the pam_unix.so. Or, even more simply just replace `[success=1 default=ignore]` with `required`.

**Comment by rmackinnon** [comment]
@t8m definitely not arguing that this config is not fscked, nor that pam_unix should be fixed/corrected in some way.  After discovering that the config was not so sane, I did make some changes there. I'll work with the Gentoo folks on the default stack being rolled out and see what can be done there.  Thanks for the response, 100% agree that weird stuff can happen here (as observed).
