### ISSUE TITLE
 warns that the password is too short but still lets me change it

### ISSUE THREAD

**Issue by osments** [linux-pam/linux-pam#40]
I have edit the common-password --> minlen variable to 9 characters.
when i try to change with command "passwd <user>", i try to put a password with, for example, 5 characters and warms me that password is too short but let me change it...
Does someone else happens the same? I follow many tutorials and all says the same procedure. I think that it's easy but i can't do it...
![image](https://user-images.githubusercontent.com/36425744/36124645-1ca92ba0-1051-11e8-96bf-687faf4b2123.png)

**Comment by alexal** [comment]
What Linux distribution are you using?

**Comment by t8m** [comment]
Not enough info to investigate.
