### ISSUE TITLE
pam_exec needs SIGCHLD protection

### ISSUE THREAD

**Issue by oclsc** [linux-pam/linux-pam#405]
pam_exec spawns a child, then waits for it with waitpid(2).  If the program that called PAM has a SIGCHLD handler that itself reaps the child, this won't work: pam_exec's waitpid call is interrupted by the signal, the handler gets the child, and the interrupted call gets ECHILD, so that pam_exec always returns failure.

I gather that other modules such as pam_unix have bumped into the same problem in the past. The simplest fix is the same: save the SIGCHLD handler and return to the default before calling fork, restore the handler after waitpid returns.

The problem has been around for a while but apparently hasn't been passed upstream; see for example https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910967 .

Here's a fix in the form of a patch for modules/pam_exec/pam_exec.c:

*** pam_exec.orig.c	2021-11-22 18:08:12.057215320 -0500
--- pam_exec.c	2021-11-22 18:16:23.264906527 -0500
***************
*** 48,53 ****
--- 48,54 ----
  #include <sys/wait.h>
  #include <sys/stat.h>
  #include <sys/types.h>
+ #include <signal.h>
  
  #include <security/pam_modules.h>
  #include <security/pam_modutil.h>
***************
*** 226,231 ****
--- 227,241 ----
      return PAM_SERVICE_ERR;
    }
  
+   /*
+    * disable SIGCHLD; if caller has set up a handler,
+    * it will steal our child's status
+    * and waitpid() below will fail
+    */
+   memset(&newsa, 0, sizeof(newsa));
+   newsa.sa_handler = SIG_DFL;
+   (void) sigaction(SIGCHLD, &newsa, &oldsa);
+ 
    pid = fork();
    if (pid == -1)
      return PAM_SYSTEM_ERR;
***************
*** 263,268 ****
--- 273,279 ----
  
        while ((rc = waitpid (pid, &status, 0)) == -1 &&
  	     errno == EINTR);
+       (void) sigaction(SIGCHLD, &oldsa, NULL);	/* restore handler if any */
        if (rc == (pid_t)-1)
  	{
  	  pam_syslog (pamh, LOG_ERR, "waitpid returns with -1: %m");

**Comment by ldv-alt** [comment]
Yes, and it seems to me that `pam_xauth` has a similar issue.
Could you submit a proper PR, please?
