### ISSUE TITLE
nonewprivs (PR_SET_NO_NEW_PRIVS) requires kernel >= 3.5

### ISSUE THREAD

**Issue by lancethepants** [linux-pam/linux-pam#406]
Linux-pam 1.5.0 added support for nonewprivs (PR_SET_NO_NEW_PRIVS) which is available in kernels 3.5 and newer. There's no configure time check for PR_SET_NO_NEW_PRIVS availability, so projects with kernel before 3.5 will be unable to use recent verions of Linux-pam, which is an essential library.

**Comment by ldv-alt** [comment]
Manual page `limits.conf(5)` documents the following use of `PR_SET_NO_NEW_PRIVS` in `pam_limits` module:
```
nonewprivs
    value of 0 or 1; if set to 1 disables acquiring new privileges by invoking prctl(PR_SET_NO_NEW_PRIVS)
```
Besides that, Linux-PAM does not use `PR_SET_NO_NEW_PRIVS`.

**Comment by lancethepants** [comment]
Sorry, my post wasn't very clear.  I should have said this is a compile time issue.  I was thinking of running `./configure` when I said "configure".
The error I get when compiling is shown below. It's looking for `PR_SET_NO_NEW_PRIVS` which doesn't doesn't exist in pre 3.5 kernels. There is no ./configure kernel version check or option to disable this, and there is nothing like ifdefs around the code in pam_limits.c to prevent it from being included in kernels that don't have this feature.
```
pam_limits.c:1068:19: error: ‘PR_SET_NO_NEW_PRIVS’ undeclared (first use in this function); did you mean ‘LIMIT_NONEWPRIVS’?
 1068 |         if (prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0) < 0) {
      |                   ^~~~~~~~~~~~~~~~~~
```

**Comment by ldv-alt** [comment]
Yes, there should be an ifdef, e.g.
```
#ifndef PR_SET_NO_NEW_PRIVS
# define PR_SET_NO_NEW_PRIVS 38 /* from <linux/prctl.h> */
#endif
```
