### ISSUE TITLE
pam_faillock: reboot unlocks accounts

### ISSUE THREAD

**Issue by beroal** [linux-pam/linux-pam#413]
I use the default `pam_faillock` configuration provided by Arch Linux which consists totally of comments. If I type in an incorrect password three times, I cannot login. After I reboot, I can login. I believe the default `unlock_time` is 600 seconds. I reboot much faster than that.

This may be an Arch Linux misconfiguration.

**Comment by t8m** [comment]
This is not a misconfiguration and not a bug either. This is the default behavior. Please read faillock.conf manual page. The defaults for the options are mentioned there.

**Comment by t8m** [comment]
Here is a hint - you can use `deny=0` to switch the locking off completely.

**Comment by beroal** [comment]
> This is the default behavior. Please read faillock.conf manual page.

`faillock.conf` contains lengthy comments, so I thought they are enough. Thank you for providing the way to change this behavior.
