### ISSUE TITLE
faillock counter increments on password timeout

### ISSUE THREAD

**Issue by greyltc** [linux-pam/linux-pam#422]
If I enter nothing at a password prompt and then the prompt times out, the faillock counter seems to go up by one. That seems wrong to me since no password entry is not, and should not be considered the same as a failed password attempt.

**Comment by greyltc** [comment]
I should probably have mentioned that this is with Arch Linux's pam package, version 1.5.2-1 https://archlinux.org/packages/core/x86_64/pam/

**Comment by t8m** [comment]
This is nothing we can handle in pam_faillock. If a specific error is returned by pam_unix (or any other authentication module asking for password) I suppose in the PAM configuration you could distinguish this specific error and not call the pam_faillock locking. It would complicate the pam configuration severally I suppose. Anyway closing as there is nothing we can do with that.
