### ISSUE TITLE
linux-pam strategy need to modified

### ISSUE THREAD

**Issue by JustinWuCN** [linux-pam/linux-pam#424]
### system is be locked

Today, my system is be locked with linux-pam.
This is how it happened:
I copied data from the remote computer to the local machine through ssh, after entering the wrong password three times, the local machine was locked.
So I search online information.

https://superuser.com/questions/1597162/how-to-unlock-linux-user-after-too-many-failed-login-attempts
https://bugs.archlinux.org/task/67644
https://github.com/linux-pam/linux-pam/issues/420

After reading the above discussion, I think it is necessary to modify this locking strategy.

### Imagine the following scenario:
When I left the workstation temporarily, the cleaner came to clean up and cleaned the dust on the keyboard with a rag. 
At this time, three wrong password entries were triggered.
I want to continue working when I come back, but the computer is locked.
Why should I pay for a stranger's inadvertent loss?

### Consider the following scenario again:
If a colleague make a joke, enter the wrong password three times on your computer when you leave, The computer is locked.
Why should I pay for a joke?

### Consider again a more general scenario:
Because the user can access computer from internet,
the hacker can lock your system with failed remote logins.
Why would you pay for a malicious attacker?

---

That last scenario is more generic, considering that my system be locked out is caused by a remote login.

After being locked, use faillock to see the information:
````
[root@justin log]# faillock
justin:
When Type Source Valid
2022-01-12 16:19:10 RHOST 10.64.30.82 V
2022-01-12 16:19:13 RHOST 10.64.30.82 V
2022-01-12 16:19:15 RHOST 10.64.30.82 V
````

Compared with `fail2ban`, after a login failure occurs, fail2ban locks the IP and not allows this IP to access.
However, linux-pam locks the user, then the users cannot use system again.

## Another strategy also needs to be modified.
that is, the strategy of locking users after 3 failures within 15 minutes.
After I use the `faillock --reset` command to unlock the user and continue to copy the data, even if the password I entered is correct, but in these 15 minutes, there have been three records of wrong passwords, so the user is immediately locked again.

```
sudo lastb
justin   ssh:notty    10.64.30.82      Wed Jan 12 17:03 - 17:03  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 17:02 - 17:02  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 17:02 - 17:02  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 17:01 - 17:01  (00:00)
justin   ssh:notty    10.64.30.42      Wed Jan 12 17:00 - 17:00  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:55 - 16:55  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:55 - 16:55  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:52 - 16:52  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:20 - 16:20  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:20 - 16:20  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:19 - 16:19  (00:00)
justin   ssh:notty    10.64.30.82      Wed Jan 12 16:19 - 16:19  (00:00)
```

### my system info:
```
[root@justin faillock]# uname -a
Linux justin 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59 +0000 x86_64 GNU/Linux
[root@justin faillock]# cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

**Comment by t8m** [comment]
Please report this issue to Arch Linux. We are not going to change pam_faillock. It is not supposed to be used in default configuration especially with the built-in defaults.

**Comment by JustinWuCN** [comment]
and the ssh caused lock, may be the pam can change?

**Comment by t8m** [comment]
Arch Linux should not put pam_faillock to default configuration or it should use some different settings for it. Period. This is not an upstream Linux-PAM issue.
