### ISSUE TITLE
pam_namespace_helper to support support /etc/security/namespace.d

### ISSUE THREAD

**Issue by maage** [linux-pam/linux-pam#438]
Only /etc/security/namespace.conf is read:

https://github.com/linux-pam/linux-pam/blob/feef4ebc21131261dfcd54959572c5f7aaf98af3/modules/pam_namespace/pam_namespace_helper.in#L3

but pam_namespace supports /etc/security/namespace.d too:

https://github.com/linux-pam/linux-pam/blob/feef4ebc21131261dfcd54959572c5f7aaf98af3/modules/pam_namespace/pam_namespace.8.xml#L317
https://github.com/linux-pam/linux-pam/blob/b872b6e68a60ae351ca4c7eea6dfe95cd8f8d130/modules/pam_namespace/pam_namespace.h#L100

**Comment by ldv-alt** [comment]
See #440.
