### ISSUE TITLE
pam_exec: arggv not free'd on error

### ISSUE THREAD

**Issue by setharnold** [linux-pam/linux-pam#444]
https://github.com/linux-pam/linux-pam/blob/2f289878b6a7bd888fdfcfe4286b87006074da11/modules/pam_exec/pam_exec.c#L416

Hello, the `arggv` array and referenced strings aren't free'd on any of the error paths. This is probably not a big deal but does seem out of character given other things are free'd in the same error paths.

Thanks

**Comment by ldv-alt** [comment]
Thanks for reporting.
I think freeing memory right before pam_syslog() followed by _exit(ENOMEM) is rather useless,
so wouldn't it be better to remove all those `free(envlist)` calls instead?

What's worse is the unchecked return value of strdup in
https://github.com/linux-pam/linux-pam/blob/2f289878b6a7bd888fdfcfe4286b87006074da11/modules/pam_exec/pam_exec.c#L421

**Comment by setharnold** [comment]
Heh, I thought about that, too, but it's nice to clean up memory before exit() to keep valgrind reports short and sweet. It's up to you what you'd rather do, but I'd argue for consistency either way.

I can't believe I looked right past that unchecked `strdup()` though. Sigh.

Thanks

**Comment by ldv-alt** [comment]
@thkukuk Thorsten, I think it's your code, would you prefer freeing `arggv[]` array before `_exit()` calls, or removing `free(envlist)` calls?

**Comment by thkukuk** [comment]
It's not only arggv which is not free'd, but freeing envlist also leaves a lot of unreachable allocations behind.
So before we write long, complex code to free all kind of memory, just remove `free(envlist)`.
