### ISSUE TITLE
Question about pam.d folder and backup files

### ISSUE THREAD

**Issue by mabicca** [linux-pam/linux-pam#463]
Hi everyone,

This is more like a question, is there any documentation out there that talks about what kind of files PAM looks for within its .d folder?

It appears, that anyfile added in there will be looked at, just trying to clear up the behavior since I've seen users backing up files within that folder, for example, copying sshd to sshd.bak while they test something and I was wondering if there are any types that pam will ignore OR if it's not recommended at all to use that folder to keep backups since it will look in all files.

Thanks,
-Marco

**Comment by thkukuk** [comment]
> This is more like a question, is there any documentation out there that talks about what kind of files PAM looks for within its .d folder?

`man pam.d`
 
> It appears, that anyfile added in there will be looked at,

Not by libpam. It only looks at the configuration file specified by the application, see `man pam_start`.

> just trying to clear up the behavior since I've seen users backing up files within that folder, for example, copying sshd to sshd.bak while they test something and I was wondering if there are any types that pam will ignore OR if it's not recommended at all to use that folder to keep backups since it will look in all files.

As written, libpam will only look at the files specified by the application, nothing else.

**Comment by mabicca** [comment]
Hi @thkukuk , thanks for the help. So in other words, when pam calls are made, there's usually an application associated with it, let's say sshd, and it will look specifically for sshd in that folder, not sshd.bak for example or anything else? Sorry to ask again but I wish we had something a bit more clear like other services/modules document like for instance *.conf or any other patterns.

**Comment by t8m** [comment]
Yes, you understand that right.
