### ISSUE TITLE
Undefined variable 'exec_prefix' in Pkgconfig file pam.pc and others

### ISSUE THREAD

**Issue by lechner** [linux-pam/linux-pam#466]
Thanks for providing Pkgconfig files per #369. On Guix, their current [build recipe produces](https://github.com/guix-mirror/guix/blob/master/gnu/packages/linux.scm#L1601-L1613) a defective `pam.pc` in that the placeholder `${exec_prefix}` is used but not defined:
```
libdir=${exec_prefix}/lib
includedir=/gnu/store/bxzpnbpss9raf0gcbyv67x640s31il1p-linux-pam-1.5.2/include/security

Name: PAM
Description: The primary Linux-PAM library. It is used by PAM modules and PAM-aware applications.
URL: http://www.linux-pam.org/
Version: 1.5.2
Cflags: -I${includedir}
Libs: -L${libdir} -lpam
```
In Guix, the issue can probably be mitigated via additional command-line options to `./configure` but somehow there still seemed to be a bug in the interaction between [AC_PREFIX_DEFAULT here](https://github.com/linux-pam/linux-pam/blob/master/configure.ac#L17), the [m4/shell test here](https://github.com/linux-pam/linux-pam/blob/master/configure.ac#L28-L36) and the substitution of shell (and perhaps Makefile) [variable here](https://github.com/linux-pam/linux-pam/blob/master/libpam/Makefile.am#L45-L46).

The same issue occurs in the other two Pkgconfig files, `pamc.pc` and `pam_misc.pc`.

Thank you for taking a look!

**Comment by ldv-alt** [comment]
The `exec_prefix` variable is maintained by [autoconf](https://www.gnu.org/software/autoconf/manual/autoconf-2.71/html_node/Installation-Directory-Variables.html).  The documentation says:
```By default it’s the same as prefix.```

**Comment by lechner** [comment]
Is the issue perhaps that Autoconf is not in charge of Pkgconfig files? The variable is apparently no longer available when `pkg-config` runs at a later time—long after PAM was configure and installed—unless the variable is also declared in Pkgconfig via `exec_prefix=[LITERAL EXEC PREFIX]`.

**Comment by ldv-alt** [comment]
`libpam/pam.pc`, `libpam_misc/pam_misc.pc`, and `libpamc/pamc.pc` are listed in `AC_CONFIG_FILES` and therefore autoconf _is_ responsible for `exec_prefix` substitution.

However, `prefix` and `exec_prefix` variables are not defined in these files, so if `libdir` or `includedir` is defined using these variables, they are not substituted.

**Comment by lechner** [comment]
You hit the nail on the head! From what I can tell, `libdir` is defined as `${exec_prefix}/lib` by `autoconf` without any doing by the Linux PAM maintainers or downstream consumers like Guix.

Either way, the reference to `exec_prefix` should probably be resolved before the value is used in `pam.pc` and friends. The literal value is not being substituted in those files and renders them defective.

**Comment by ldv-alt** [comment]
Apparently, `prefix` and `exec_prefix` were present in the initial patch, but were removed after my review comment at https://github.com/linux-pam/linux-pam/pull/369#discussion_r650504735

**Comment by lechner** [comment]
@ldv-alt You are right! Like you, I think your comment at https://github.com/linux-pam/linux-pam/pull/369#discussion_r650504735 was a mistake. It should probably be reverted. At least, it would be a great first step.

Over the years, there seem to have been some [attempts](https://stackoverflow.com/a/3607678) to expand variables inside `configure` but I do not believe they were viable or are still recommended.

On a more general note, I am also not sure that generating the Pkgconfig files via `configure` is still the preferred way. I know it's common (and have done so myself) but the Autoconf documentation envisions [overriding the `prefix` at `make` time](https://www.gnu.org/prep/standards/standards.html#Directory-Variables) too. (Please further see the comment [here](https://stackoverflow.com/a/8635808).)

Either way, reverting the removal above would be a quick fix for the reporting party. Thanks!

**Comment by ldv-alt** [comment]
Would you like to submit a PR?

**Comment by lechner** [comment]
Hi, thanks for the invite! Please have a look at https://github.com/linux-pam/linux-pam/pull/493. A release would be appreciated. Thank you!

**Comment by lechner** [comment]
@ldv-alt Being a first-time contributor, I believe that a maintainer needs to approve my CI workflow for the merge request, if you have such standing here. Thanks!

**Comment by Behinder** [comment]
If I can add something to the mix but regarding cairo I got
`Variable 'exec_prefix' not defined in '/opt/local/lib/pkgconfig/cairo-script-interpreter.pc'`
after running `pkg-config --list-all -print-errors` 
even after I edited file manually so the assumption autoconf or pkg-config does not see *.pc files seems to be correct
