### ISSUE TITLE
Support /etc/motd.d (cf. util-linux /etc/issue.d)

### ISSUE THREAD

**Issue by allisonkarlitskaya** [linux-pam/linux-pam#47]
The cockpit project would like to add a brief bit of text to the motd to advertise the availability of the admin interface at a given URL.

We're able to do that for console (read:getty) logins via /etc/issue.d/ which is a recently added feature of util-linux, but the main beneficiary of such a message would be a user who is logging in via ssh.  We don't want to do an ssh banner, as that would be much too obtrusive, but since most interactive sessions already feature a motd, this seems like a good place to include it.

We also don't want to update the distribution's /etc/motd file.

Our approach to doing this for issue.d is that we have systemd tmpfiles create a "cockpit isn't running" text and write it to /run/cockpit/issue.  We change that text according to if the cockpit listener socket is started or stopped.  We symlink that into /etc/issue.d/.

If I were to design the feature, I'd:
 - add a new motd_directory= argument that would allow displaying other directories.
 - change the default arguments to motd=/etc/motd motd_directory=/etc/motd.d
 - if either of motd= or motd_directory= is given, don't apply the defaults

I'm willing to do a patch, if you like.

Thoughts?

**Comment by t8m** [comment]
I think the design is sound. So if you want to write a patch for pam_motd, please go ahead.

**Comment by allisonkarlitskaya** [comment]
Please see pull #48
