### ISSUE TITLE
Two wrong passwords in SSH exhaust max number of retries for service

### ISSUE THREAD

**Issue by iftach7997** [linux-pam/linux-pam#488]
Hi,
1. Open an SSH terminal (Putty)
2. Enter a valid username
3. Enter 2 wrong passwords
4. The SSH connection has dropped with dialog: "No supported authentication methods available (server sent: publickey)"

I expected it to occur after 3 wrong passwords, as it behaved before and also according to (#define UNIX_MAX_RETRIES  3)

I am attaching:
- A capture of the above dialog
- An sshd log with log level DEBUG3 (with comments for my different actions marked with: "//USER ACTION: ")

**Comment by iftach7997** [comment]
Attachments:

[SSH_disconnects_after_2_wrong_passwords_log_debug3.txt](https://github.com/linux-pam/linux-pam/files/9469001/SSH_disconnects_after_2_wrong_passwords_log_debug3.txt)
![SSH_drop_pop_up_dialog](https://user-images.githubusercontent.com/112617474/187890433-421a2535-d88f-47e3-aee4-e84c9d5d8703.JPG)

**Comment by ldv-alt** [comment]
The relation with linux-pam is not obvious.
