### ISSUE TITLE
pam_unix account component should not check password expiry/account inactivity/locking when no password is set

### ISSUE THREAD

**Issue by bugspencor** [linux-pam/linux-pam#489]
Security policies (e.g. CIS) often require that passwords are renewed after a defined time interval and accounts are locked when the password is not changed, which is enforced with /etc/login.defs and /etc/shadow. 

I came across the problem that a user could not login via ssh with public key because pam_unix returned an error due to expired password even the account has no password set. A non-existing password cannot expire in my opinion ;-)

The user is asked to update "the password", requesting "the current password", which cannot be entered because there is none. Sys admin action is required to recover the account.

Likewise the account would be locked if the inactivity interval has also passed.

I am aware of the "no_pass_expiry" option, and I could use that to enable login for users without a password after the expiry interval, but that would also allow users with an expired password to login. Also this option does not workaround the account locking when the inactivity interval has passed. Users would lose access to their accounts when the inactivity interval has passed.

In my opinion password expiry should not be checked in pam_unix when no password is set, so all use cases (account with password -> correct enforcing of password expiration rules; account without password -> password expiration rules do not apply). Would you consider a change of the current behaviour?

**Comment by thkukuk** [comment]
Password expiry is also used very often to force people set or change the password at the first login. So your suggestion would break all the setups where this is used correct.

But I don't understand why you set password expiration for this accounts. Just don't do that. If your security team requires to set password expiration for non-existing passwords, you should discuss this with them.
This is a pure administration problem and not a tooling problem.

**Comment by bugspencor** [comment]
In that first-login use case these accounts have an initial password set, correct? (at first login the "current password" must be entered, so there has to be one). In that case my request would not interfere with the first-login use case, as it only would affect accounts without password.

Disabling the password expiration is the ad-hoc solution. The problem occurred on a default Red Hat EL 8 installation with a configured security policy after the expiry interval has passed (365 days).

The current behavior seems counter-intuitive to me and led to a acute problem in my case, therefore I created the report. Of course well-established use-cases should not be broken by a potential change.

**Comment by thkukuk** [comment]
> In that first-login use case these accounts have an initial password set, correct? (at first login the "current password" must be entered, so there has to be one). 

If for a first login an initial password needs to be set or not depends purely on your configuration. So no, there must be no initial password set.

> In that case my request would not interfere with the first-login use case, as it only would affect accounts without password.

And exactly this is the problem. It affects existing setups.

> Disabling the password expiration is the ad-hoc solution.

Disabling the password expiration for an account without password is the correct solution.

**Comment by bugspencor** [comment]
> > In that first-login use case these accounts have an initial password set, correct? (at first login the "current password" must be entered, so there has to be one).
> 
> If for a first login an initial password needs to be set or not depends purely on your configuration. So no, there must be no initial password set.

OK. I did not know that. Thanks for clarification.

**Comment by t8m** [comment]
The "no_pass_expiry" does exactly what you want, i.e., ignore the password expiration checks if pam_unix was NOT used to authenticate the user. See the description in the manual page.
