### ISSUE TITLE
pam_cracklib: Abort the retry loop when user cancels pam_chauthtok conversation

### ISSUE THREAD

**Issue by hoehnth** [linux-pam/linux-pam#49]
Minor issue.
Abort the retry loop when user cancels prompt.
The retry loop must be aborted for any pam_get_authtok() error except for PAM_TRY_AGAIN.

See commit with neccessary changes in: [libpwquality](https://github.com/libpwquality/libpwquality/commit/bddd1dfe5a13e39e04ed1593cba4263dfd528fad).

Original issue: [libpwquality PR#7](https://github.com/libpwquality/libpwquality/pull/7)

**Comment by ldv-alt** [comment]
pam_cracklib module was deprecated in 1.4.0 and removed later by commit d702ff714c309069111899fd07c09e31c414c166.
