### ISSUE TITLE
Does exist any pam item that expands to the UID at pam_env.conf?

### ISSUE THREAD

**Issue by ltsdw** [linux-pam/linux-pam#501]
Like there's @{PAM_USER} that expands to the user string.

So is there something like @{PAM_UID}? That would expand to something like 1000, 1002, etc.

I was looking at the code and dind't see anything related.

**Comment by t8m** [comment]
Nope, there is no such item.

**Comment by ltsdw** [comment]
@t8m ok, got it, I guess it would be trivially to implement it, as it is already getting the information from passwd, but does you guys have interest on implementing it?

**Comment by ltsdw** [comment]
Thank you, I'll close this one now.
