### ISSUE TITLE
How does /etc/motd.d directory works?

### ISSUE THREAD

**Issue by karpse** [linux-pam/linux-pam#502]
Hi,

My system (CentOS 7) has /etc/motd and /etc/motd.d/ by default. I can use the first one: it's just a text file and the content of which is printed by motd after logging into the terminal. However, I don't know how to use /etc/motd.d/ directory. My assumption was that it is the same as the previous one, but there you could split the motd message into pieces, from which a whole message is assembled. For example, /etc/motd.d/10-welcome, /etc/motd.d/20-hostname and /etc/motd.d/30-noticeboard, the output:
“Welcome!
your-hostname
Today is maintenance break at 20:00.".
However, it apparently doesn't do this or nothing else I've tested. So how does the /etc/motd.d/ directory work and what are its use cases?

Thanks,
karpse

**Comment by thkukuk** [comment]
It works exactly this way: either you have a `/etc/motd` file, or all snippets of the `motd.d` directories are combined and shown.
Works exactly this way on openSUSE MicroOS.
If it does not work on your system, please check your configuration files, if they are not correct configured.

**Comment by karpse** [comment]
> It works exactly this way: either you have a `/etc/motd` file, or all snippets of the `motd.d` directories are combined and shown. Works exactly this way on openSUSE MicroOS. If it does not work on your system, please check your configuration files, if they are not correct configured.

So when using /etc/motd.d/ my system must not have /etc/motd file? Would you list all the configuration files that affect this? :)

**Comment by karpse** [comment]
Would it be possible to add documentation on the operation of these to the man page?

**Comment by thkukuk** [comment]
It's documented in the manual page. There is a list of priorities and it's written, that pam_motd stops if /etc/motd exists, and if that does not exist it looks for /run/motd and stops if that exist, and so on.

**Comment by karpse** [comment]
> It's documented in the manual page. There is a list of priorities and it's written, that pam_motd stops if /etc/motd exists, and if that does not exist it looks for /run/motd and stops if that exist, and so on.

Okey, thanks for your answers. I've tested this today on Ubuntu (but I soon realized it uses the update-motd, which changes the behavior of the upstream motd), Rocky Linux, Fedora Linux and Manjaro Linux. I couldn't get this to work anywhere :( Targeting for RHEL/Rocky, once I get it working I can refine it for others. So I want my files 00-example-welcome, 01-example-todaypost to be combined into one motd post. I delete /etc/motd , create (if it doesn't exist) /etc/motd.d, then move the text files described above to /etc/motd.d/ After that it should work, or am I missing something?

**Comment by karpse** [comment]
@thkukuk What are all the configuration files of Linux PAM or its motd? I could check them then.

**Comment by thkukuk** [comment]
Start reading the pam_motd documtation, this gives you already a start how to configure it.
Afterwards, you need to check your Linux Distribution, how they do configure this. This has nothing to do with Linux-PAM upstream. This is distribution specific.

And if it does not work on your Linux Distribution, maybe they don't support it? Only because the current upstream Linux-PAM version supports it does not mean your Linux distribution is current enough or enables it.

But your questions are all Distribution specific and have nothing to do with the Linux-PAM projec itselft, we cannot help your there.

**Comment by karpse** [comment]
Sorry to bother you, but I have one more question... Hopefully you (@thkukuk) or someone else will have time to answer this.
Was it so that the /etc/motd file must be deleted when you want to use /etc/motd.d? Then why are the values ​​defined in different variables in the source code?

```
#define DEFAULT_MOTD	"/etc/motd:/run/motd:/usr/lib/motd"
#define DEFAULT_MOTD_D	"/etc/motd.d:/run/motd.d:/usr/lib/motd.d"
```
