### ISSUE TITLE
motd(5) man page

### ISSUE THREAD

**Issue by karpse** [linux-pam/linux-pam#503]
motd(5) man page does not mention that motd is also affected by /run/motd, /usr/lib/motd, /etc/motd.d/, /run/motd.d/ and /usr/lib/motd.d/ files.

https://man7.org/linux/man-pages/man5/motd.5.html

**Comment by thkukuk** [comment]
Please read the page to the end: this is a generic manual page from he man-pages project and it specifies an URL where to report bugs. And that is not this project. Linux-PAM does not have anything to do with that.
And for all tools, especially the referenced login(1) application, displaying /etc/motd and not using pam_motd, that manual page is correct.
