### ISSUE TITLE
doc page vanished since 2021 on WP?

### ISSUE THREAD

**Issue by skramm** [linux-pam/linux-pam#506]
The WP page (https://en.wikipedia.org/wiki/Linux_PAM) points today as first reference this link:
http://www.linux-pam.org/Linux-PAM-html/sag-introduction.html
Was valid in 2021 but ends nowhere but here. (domain linux-pam.org redirects to GH project).

Too bad, because I think it could have a great educational value from a trusted source.

Could somebody either correct the link if that page is now lying elsewhere (couldn't find it in the repo?) or just remove if it is simply gone.
Maybe the content was just obsolete?
(I can do it if somebody tells me what to do).

(Yes, I know, not really an issue with PAM, but I don't know where I could post this...)

**Comment by Ingo-Albrecht** [comment]
@skramm The guide you ask for is still available under [https://github.com/linux-pam/linux-pam/blob/master/doc/sag/Linux-PAM_SAG.xml#L19](url), but only as xml. The guide is generated and installed in html format on each system with the package.

I see wp has replaced the broken link with the waybackmachine version meanwhile. While the linked page has not changed, up-to-date html versions are available on various machines on the web. For example [https://fossies.org/linux/Linux-PAM-docs/doc/sag/html/sag-introduction.html](url) should update regularly, when the package does.

**Comment by skramm** [comment]
> I see wp has replaced the broken link with the waybackmachine version meanwhile. 

Yep, somebody might have seen this issue, was corrected a  couple of days after I wrote this ;-)

Thanks for your comment, I think I can close this.
Side note: don't know happened but there is a discrepancy between your link text and the link itself.
Corrected:

- https://github.com/linux-pam/linux-pam/blob/master/doc/sag/Linux-PAM_SAG.xml#L19
- https://fossies.org/linux/Linux-PAM-docs/doc/sag/html/sag-introduction.html
