### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ikerexxe** [linux-pam/linux-pam#507]
Hi,

Is there any release planned for the next few weeks? The last one happened more than a year ago, and there are nearly 90 commits on top of it.

**Comment by ldv-alt** [comment]
I think it would be great if we could complete the vendordir support first.
Which means I need to do more PR reviews per week. :)

**Comment by ikerexxe** [comment]
No problem. I just wanted to raise awareness on this topic.

**Comment by ldv-alt** [comment]
As the vendordir support efforts have been stalled for a while, maybe it's time to revisit this.

**Comment by thkukuk** [comment]
> As the vendordir support efforts have been stalled for a while, maybe it's time to revisit this.

I'm only aware of two open things:
* the new pwhistory.conf file
* installing the configuration files in the vendordir if specified and not in /etc/security

I can ask Schubi tomorrow about the status here, but I don't see that as something blocking a new release.

**Comment by ldv-alt** [comment]
Once again, do we have something in the queue, or should we rather proceed with releasing a new version?

**Comment by thkukuk** [comment]
I wanted to suggest already that we should release a new version. I don't have anything in the queue.

In the NEWS we should mention something like:

* Deprecated pam_lastlog: this module is no longer built by default and will be removed in one of the next releases, use pam_lastlog2 (from https://github.com/thkukuk/lastlog2) and/or pam_wtmpdb (from https://github.com/thkukuk/wtmpdb) instead

**Comment by t8m** [comment]
+1

**Comment by thkukuk** [comment]
Building without NIS is currently broken, looking at it.

**Comment by thkukuk** [comment]
PR#554 fixes building without NIS/RPC.

**Comment by ldv-alt** [comment]
https://github.com/linux-pam/linux-pam/releases/tag/v1.5.3 was released in May 2023.
