### ISSUE TITLE
pam_unix.so: linked against yppasswd_xdr even with --disable-nis

### ISSUE THREAD

**Issue by thkukuk** [linux-pam/linux-pam#523]
pam_unix.so is always linked against yppasswd_xdr, even if NIS is disabled via the --disable-nis configure option.

**Comment by thkukuk** [comment]
@t8m @ldv-alt 
What do you prefer: changing the Makefile to not link against yppasswd_xdr.o or changing yppasswd_xdr.c and wrap the code in a big "HAVE_NIS" define like in the other pam_unix code?

**Comment by ldv-alt** [comment]
I prefer changing the Makefile, but I'm fine with either.

**Comment by t8m** [comment]
Same preference as @ldv-alt
