### ISSUE TITLE
libpam rejects pam config files containing long lines

### ISSUE THREAD

**Issue by DDDas7** [linux-pam/linux-pam#532]
Hi,
     
    Greetings!
     
    I would like to  highlight an issue related to the "pam_tty_audit.so" module. Login issue is observed if the number of comma separated user  lists is very large. If the complete string is larger than 1024 bytes  then "Permission denied" error is observed during the login example (su - <username>).
     
    ---------------------------------------------------------------------------
    session     required      pam_tty_audit.so disable=* enable=abc,xyz, ............, zzz
    ---------------------------------------------------------------------------
     
    the 1024 bytes limitation is hardcoded and  is coming from below file.
     
     - libpam/pam_handlers.c
     
       ---------------------------------------
       #define BUF_SIZE                  1024
       ---------------------------------------
     
    I would like to write a patch for the above issue  but would like to confirm the following.
     
    1) Will it be possible to increase BUF_SIZE to 4096  or dynamically to the default BUF_SIZE value to "getconf  ARG_MAX" which is 1/4th the size of stack size (uimit -s)?
     
    2) If solution in point 1 is not possible will it be fine to create a separate config file similar to faillock (/etc/security/faillock.conf) to customize the value.
     
    Any  suggestion / feedback will be helpful to resolve the above issue.
     
    Regards,
    Deepak Das

**Comment by DeepakDas7** [comment]
Hi, 

Greetings!

Anyway update is available regarding  the above query?

Regards,
Deepak Das

**Comment by ikerexxe** [comment]
@ldv-alt can you guide us on the best solution for this issue?

**Comment by thkukuk** [comment]
By looking at the code, I'm against just increasing the buffer, as this does not solve the fundamental problem here, that _pam_assemble_line returns that the buffer is too small, but the calling function aborts on this.

Either _pam_assemble_line increases the buffer dynamically, or the calling function tries it again with a bigger buffer. But hardcoded buffer sizes should not be used anymore today.

**Comment by DeepakDas7** [comment]
Hi Thorsten (@thkukuk),  

Thank you for your feedback!

As per your suggestion, I have  make the necessary changes and created  PR (https://github.com/linux-pam/linux-pam/pull/561)

Can you please review the same .

Thanks and Regards,
Deepak Das

**Comment by ldv-alt** [comment]
This is not related to pam_tty_audit.so in any way, one could achieve the same effect with pam_permit.so

**Comment by ldv-alt** [comment]
The proposed patch essentially raises the line buffer size limit from 1024 to 8192.

**Comment by DDDas7** [comment]
Hi Dmitry,

The last feedback shared  by you  is not clear. Can you kindly elaborate?

Are you proposing to raise the buffer size to another value? Or should the size be dynamically allocated?

Regards,
Deepak Das

**Comment by stoeckmann** [comment]
My attempt to fix it can be seen here: https://github.com/linux-pam/linux-pam/pull/658
