### ISSUE TITLE
memset to explicit_bzero

### ISSUE THREAD

**Issue by igorDi86** [linux-pam/linux-pam#533]
Hello everyone!
What do u think if to change memset to explicit_bzero ?
Because compiler could delete the 'memset' function call.
it was in #305

**Comment by ldv-alt** [comment]
See #531.

**Comment by igorDi86** [comment]
Hah! Just in time. )

**Comment by cgzones** [comment]
Should be addressed by #528.

**Comment by ldv-alt** [comment]
Addressed by #528.
