### ISSUE TITLE
/bin/bash: ./padout: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by ZhYingJie** [linux-pam/linux-pam#536]
updating parse_y.h
make  all-am
make[7]: Entering directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32/doc/specs'
/bin/bash ../../build-aux/ylwrap parse_l.l lex.yy.c parse_l.c -- flex  
mips64-octeon-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../..      -MT parse_l.o -MD -MP -MF .deps/parse_l.Tpo -c -o parse_l.o parse_l.c
mv -f .deps/parse_l.Tpo .deps/parse_l.Po
mips64-octeon-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I../..      -MT parse_y.o -MD -MP -MF .deps/parse_y.Tpo -c -o parse_y.o parse_y.c
mv -f .deps/parse_y.Tpo .deps/parse_y.Po
/bin/bash ../../libtool  --tag=CC   --mode=link mips64-octeon-linux-gnu-gcc     -o padout parse_l.o parse_y.o  
libtool: link: mips64-octeon-linux-gnu-gcc -o padout parse_l.o parse_y.o 
./padout < ./draft-morgan-pam.raw > draft-morgan-pam-current.txt
/bin/bash: ./padout: cannot execute binary file: Exec format error
make[7]: *** [draft-morgan-pam-current.txt] Error 126
make[7]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32/doc/specs'
make[6]: *** [all] Error 2
make[6]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32/doc/specs'
make[5]: *** [all-recursive] Error 1
make[5]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32/doc'
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32'
make[3]: *** [all] Error 2
make[3]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32'
make[2]: *** [/home/cdsw/test/software-tap-V2-gre/build_dir/target-mips64/libpam-1.1.32/.built] Error 2
make[2]: Leaving directory `/home/cdsw/test/software-tap-V2-gre/package/libpam'
make[1]: *** [package/libpam/compile] Error 2
make[1]: Leaving directory `/home/cdsw/test/software-tap-V2-gre'
make: *** [package/libpam/compile] Error 2

How to solve

**Comment by ldv-alt** [comment]
When you're doing a cross build, you have to specify `CC_FOR_BUILD`.

**Comment by ZhYingJie** [comment]
OK. Thanks
