### ISSUE TITLE
Y2038: Linux-PAM uses utmp/wtmp/btmp/lastlog in several places which are not Y2038 ready

### ISSUE THREAD

**Issue by thkukuk** [linux-pam/linux-pam#537]
utmp/wtmp/btmp/lastlog are on 64bit systems, which support a 32bit userland, too, not Y2038 safe.
Even on x86-64 with a pure 64bit userland glibc uses 32bit time_t for this files.
The bad thing is, it doesn't look like glibc developers want to fix that, but they think more about deprecating this interfaces.
I wrote something together, who uses on a default server installation what: https://github.com/thkukuk/utmpx/blob/main/Y2038.md

For Linux-PAM this are mainly:
* libpam/pam_modutil_getlogin()
* pam_issue.so
* pam_lastlog.so
* pam_limits.so
* pam_timestamp.so/pam_timestamp_check

I would like to deprecate at least pam_lastlog. All relevant applications have own support for wtmp/btmp/lastlog and people who use this module do it most of the time wrong, which leads to e.g. duplicate wtmp entries and similar issues.

And we wouldn't need to bother with this special files `btmp` and `lastlog`, for which no official API exists.
About `pam_modutil_getlogin()`: do we really need to implement our own getlogin() function? Or wouldn't it be enough to use the libc one, and only read/set the _PAMMODUTIL_GETLOGIN data?

**Comment by thkukuk** [comment]
After discussion on libc-alpha: glibc getlogin() variant is Y2038 safe, our from libpam is not. So I will adjust our code to call the glibc variant again.

**Comment by ldv-alt** [comment]
The relevant libc-alpha discussion starts [there](https://sourceware.org/pipermail/libc-alpha/2023-February/145407.html).

**Comment by thkukuk** [comment]
An update, with using getlogin() from libc (PR#538) and deprecating pam_lastlog (PR#539) the following issues are open:
* pam_issue.so counts users currently logged in.
* pam_limits.so counts how often the user is currently logged in.
* pam_timestamp.so/pam_timestamp_check (uses utmp entries to get time of login)

If somebody has an idea how to get this information without utmp...

**Comment by thkukuk** [comment]
Some ideas how to solve the remaining Y2038 problems:
* pam_issue.so/pam_limits.so - query systemd-logind for the number of logged in users
* pam_timestamp.so - query systemd-logind for the login time of that user

So we can really live without utmp on a systemd system. 

Between: with musl libc this functionality isn't available at all, since the functions we call are dummies, musl libc has no support for utmp nor wtmp.

**Comment by thkukuk** [comment]
PR #541 should fix this.

**Comment by thkukuk** [comment]
Linux-PAM should be fine now if logind is enabled.
