### ISSUE TITLE
Is Linux-PAM-0.76 support SHA512 for root users

### ISSUE THREAD

**Issue by ierasa** [linux-pam/linux-pam#542]
We are using Linux-PAM-0.76 release in our project, We implemented the SHA512 encryption password for admin and non-default users thru CLI. But when we tried to modify the password thru root prompt for root users, It is accepting only for first 8 characters of password.
I have identified the Root cause, By default it's DES algorithm. Please let us know, are we supporting SHA512 for root users. 
How to resolve the issue. 

Code snippet
PAM_EXTERN int pam_sm_chauthtok(pam_handle_t * pamh, int flags,
				int argc, const char **argv)
{
		if (on(UNIX_MD5_PASS, ctrl)) {
			tpass = crypt_md5_wrapper(pass_new);
		} else {
			/*
			 * Salt manipulation is stolen from Rick Faith's passwd
			 * program.  Sorry Rick :) -- alex
			 */

			time_t tm;
			char salt[3];

			time(&tm);
			salt[0] = bin_to_ascii(tm & 0x3f);
			salt[1] = bin_to_ascii((tm >> 6) & 0x3f);
			salt[2] = '\0';

			if (off(UNIX_BIGCRYPT, ctrl) && strlen(pass_new) > 8) {
				/* 
				 * to avoid using the _extensions_ of the bigcrypt()
				 * function we truncate the newly entered password
				 * [Problems that followed from this are fixed as per
				 *  Bug 521314.]
				 */
				char *temp = malloc(9);

				if (temp == NULL) {
					_log_err(LOG_CRIT, pamh,
					         "out of memory for password");
					pass_new = pass_old = NULL;	/* tidy up */
#ifdef USE_LCKPWDF
					ulckpwdf();
#endif
					return PAM_BUF_ERR;
				}
				/* copy first 8 bytes of password */
				strncpy(temp, pass_new, 8);
				temp[8] = '\0';

				/* no longer need cleartext */
				tpass = bigcrypt(temp, salt);

				_pam_delete(temp);	/* tidy up */

**Comment by ldv-alt** [comment]
> We are using Linux-PAM-0.76 release in our project,

Version 0.76 was released more than 20 years ago, and sha512 support was added to pam_unix module in version 0.99.10.0 that was released more than 15 years ago.  If for some reason you have to stick to a more than 20 year old version, you're on your own, sorry.
