### ISSUE TITLE
> > We are using Linux-PAM-0.76 release in our project,

### ISSUE THREAD

**Issue by ierasa** [linux-pam/linux-pam#543]
> > We are using Linux-PAM-0.76 release in our project,
> 
> Version 0.76 was released more than 20 years ago, and sha512 support was added to pam_unix module in version 0.99.10.0 that was released more than 15 years ago. If for some reason you have to stick to a more than 20 year old version, you're on your own, sorry.

Thanks for response. 
I agree, There is no plan to upgrade LIBPAM release and was tried to support sha512 in the same release. The only issue we were seeing that, when we tried changes password thru root prompt it accepts only first 8 character and it works fine thru CLI.
Please share your inputs how to implement the same in current libpam.

_Originally posted by @ierasa in https://github.com/linux-pam/linux-pam/issues/542#issuecomment-1441117119_

**Comment by thkukuk** [comment]
As @ldv-alt already wrote: Linux-PAM 0.76 is  over 20 years old, we don't support that anymore in anyway.
If you really care about security, you should really update to the current version with all bugfixes and security enhancements and not just add sha512 support.
And we will not support anybody in enhancing such old code, we have enough to do with current code.
