### ISSUE TITLE
PAM_TTY and PAM_XDISPLAY, documentation is unclear when to use what.

### ISSUE THREAD

**Issue by thkukuk** [linux-pam/linux-pam#546]
Our documentation contains:
```
PAM_TTY
The terminal name: prefixed by /dev/ if it is a device file; for graphical, X-based, applications the value for this item should be the $DISPLAY variable.
```

But in  2007 we introduced:
```
PAM_XDISPLAY
The name of the X display. For graphical, X-based applications the value for this item should be the $DISPLAY variable.
```

So shouldn't the $DISPLAY reference be removed from PAM_TTY?
The unclear behavior is a problem if you want to create utmp and/or wtmp entries out of a PAM module, since every display manager interprets this different...

@ldv-alt @t8m Opinions?

**Comment by ldv-alt** [comment]
Has `PAM_XDISPLAY` become popular?  My _feeling_ is that most users are unaware of `PAM_XDISPLAY` and `PAM_TTY` is still being used instead.  If that's the case, the removal of the reference from docs would result to the situation where a lot of code just follow some undocumented practice.  Maybe the description could be rephrased to read that in the past `PAM_TTY` used to have this meaning, but later `PAM_XDISPLAY` was introduced for this purpose.

**Comment by thkukuk** [comment]
PR #547 solves this
