### ISSUE TITLE
Did you provide system-auth and common-xxx by default? 

### ISSUE THREAD

**Issue by markwester** [linux-pam/linux-pam#549]
Did you provide system-auth and common-xxx by default? If you did, how did you create them?

**Comment by thkukuk** [comment]
This are distribution specific configuration files managed by distribution specific config tools.
Linux-PAM does not provide configuration files for services.

**Comment by markwester** [comment]
> This are distribution specific configuration files managed by distribution specific config tools. Linux-PAM does not provide configuration files for services.

Ok, thank you for your attention this probllem.
