### ISSUE TITLE
--enable-openssl build is broken by introduction of vendordir support

### ISSUE THREAD

**Issue by ldv-alt** [linux-pam/linux-pam#553]
Regardless of whether vendordir support is enabled or not, it defines `--stringparam profile.condition` which conflicts with those defined by --enable-openssl, see https://github.com/linux-pam/linux-pam/actions/runs/4605735966 where I tried to add some --enable-openssl jobs to the CI matrix.

@schubi2 @thkukuk @ikerexxe: please have a look.

**Comment by schubi2** [comment]
@ldv-alt thanks. I will have a look on it.
