### ISSUE TITLE
 Compilation error(Linux-PAM-1_1_8)

### ISSUE THREAD

**Issue by wpf97** [linux-pam/linux-pam#557]
https://github.com/linux-pam/linux-pam/archive/refs/tags/Linux-PAM-1_1_8.tar.gz
./configure --disable-selinux && make

[root@10-13-99-218 linux-pam-Linux-PAM-1_1_8]# rpm -qa | grep pam
pam-1.1.8-23.el7.x86_64
fprintd-pam-0.8.1-2.el7.x86_64
[root@10-13-99-218 linux-pam-Linux-PAM-1_1_8]# cat /etc/redhat-release
CentOS Linux release 7.9.2009 (Core)
[root@10-13-99-218 linux-pam-Linux-PAM-1_1_8]#

libtool: link: ( cd ".libs" && rm -f "pam_access.la" && ln -s "../pam_access.la" "pam_access.la" )
make[3]: *** 没有规则可以创建“all-am”需要的目标“access.conf.5”。 停止。
make[3]: 离开目录“/root/linux-pam-Linux-PAM-1_1_8/modules/pam_access”
make[2]: *** [all-recursive] 错误 1
make[2]: 离开目录“/root/linux-pam-Linux-PAM-1_1_8/modules”
make[1]: *** [all-recursive] 错误 1
make[1]: 离开目录“/root/linux-pam-Linux-PAM-1_1_8”
make: *** [all] 错误 2

**Comment by ldv-alt** [comment]
Duplicates #553.
