### ISSUE TITLE
Using PAM authentication as non-root user

### ISSUE THREAD

**Issue by Smriti-Ayushi** [linux-pam/linux-pam#565]
I am running a daemon in non-root user and tried performing PAM authentication and it fails.
Tried giving permission to /etc/shadow file but still PAM auth fails for application running in non-root user.

Would like to know how PAM auth can be performed by an application running in non-root.

**Comment by Smriti-Ayushi** [comment]
@ldv-alt Can you please provide your inputs on this? Any help would be appreciated :)

**Comment by ldv-alt** [comment]
If the authentication is performed using pam_unix, then the unprivileged application running under user `NAME` shall be allowed to invoke its privileged helper unix_chkpwd, this way the application can authenticate the user `NAME`.

**Comment by Smriti-Ayushi** [comment]
I was able to authenticate non-root user which the application was running in.
Is there a way to get around the issue of not able to authenticate other users? Will giving file permission to non-root user help? like /etc/shadow file.

**Comment by thkukuk** [comment]
> I was able to authenticate non-root user which the application was running in. Is there a way to get around the issue of not able to authenticate other users? 

No, allowing this would be a big security issue.

> Will giving file permission to non-root user help? like /etc/shadow file.

This will help, but again, this would be a big security issue.

PAM needs administrator privileges (somewhere mentioned in the documentation) for good reasons: everything else would be a big security risk and allow hackers a brute force attack to crack your passwords.

**Comment by arunlalkm-intel** [comment]
Thanks @thkukuk and @ldv-alt 😄

**Comment by arunlalkm-intel** [comment]
@thkukuk do you have a recommendation for what approach I should take to accomplish the following use case?

Use case:
There is a deamon running in my device which has a webserver attached to it. When a user tries to login through https the deamon will receive the username and password. Now how can we authenticate this user assuming that the deamon is running as non-root. 

Few suggestion I have got is,
1) Use a separate deamon to perform authentication and that deamon should run as root. And make sure the communication between these two deamons are done in such a way that username and password is not shown as plain txt. 
2) use systemd-login, as in use org.freedesktop.login1's CreateSession to perform authentication. 

It will be helpful to know if you have a better solution. And also your thoughts on solutions mentioned above.

**Comment by thkukuk** [comment]
Sorry, I have no idea. There is no best practice, this heavily depends on the use case and environment. You should speak with a security expert about this and create a security design first.
