### ISSUE TITLE
compiling on wsl

### ISSUE THREAD

**Issue by zeilenschubser** [linux-pam/linux-pam#569]
I tried configuring / autogen branch master (2a4b23d) on WSL and it resulted in some errors.
I got it to work after 
- installing `./ci/install-dependencies.sh` and
- renaming the `./CHANGELOG` file (because windows filesystem is not case-sensitive).`

Can this be somehow documented? If not, this issue will do for others i guess.

**Comment by jtojnar** [comment]
The changelog thing should be fixed by https://github.com/linux-pam/linux-pam/commit/a7eb114974b20aa02ead19e8f905a863ef34ce55

**Comment by ldv-alt** [comment]
The build system was changed from autotools to meson, closing this issue.
