### ISSUE TITLE
pam_unix: paasword aging make the first login always error

### ISSUE THREAD

**Issue by arunkvnss** [linux-pam/linux-pam#57]
After the root password got aged , for the first login the below text appeared,

"**You are required to change your password immediately (password aged)
New password must be a minimum of 8 characters in length. It must contain atleast one uppercase letter, one lowercase letter, one number and one non-alphanumeric character. It must not contain too many letters/numbers in sequence.
Changing password for root.
(current) UNIX password:

Authentication t
SYNC3000  3000M03KA1805000001 **/dev/console**"**

**Comment by arunkvnss** [comment]
But for the second time i could successfully changed the password

**Comment by ldv-alt** [comment]
According to the citation, the version of PAM being used is 1.2.1 or older.
The latest release at this moment is 1.3.1, please try it first.

**Comment by ldv-alt** [comment]
Please reopen if the issue persists.
