### ISSUE TITLE
[ot] info echo "*" on login

### ISSUE THREAD

**Issue by sacarde** [linux-pam/linux-pam#58]
hi,
   is possible to have echo '*' when entering the login password ?
like old function in login.defs "GETPASS_ASTERISKS"

thank you

**Comment by oxr463** [comment]
@sacarde can you provide more information or possibly an example of what you mean?

**Comment by ldv-alt** [comment]
No, it's up to the conversation function provided by the client.

**Comment by Lew-Rockwell-Fan** [comment]
Thanks.  I haven't been able to figure out what package that would be, but it's a step in the direction anyway.  I found a work around for su.  Install sudo and then sudo su [face palm] using the user's password. That doesn't help with logging in in non-graphical environment  though.

**Comment by t8m** [comment]
There are multiple such packages also depending on which distribution you use - the main ones are util-linux and shadow.
