### ISSUE TITLE
Permissions errors with pam_setcred() after jump actions with pam_exec.so

### ISSUE THREAD

**Issue by swolebro** [linux-pam/linux-pam#583]
Hello! I am trying to implement some simple 2FA for sshd. I have a script that functions properly when using `auth required pam_exec.so expose_authtok /my-script`. However, once I attempt to build on that with jump conditions (for `pam_faillock.so`), sshd throws errors when calling `pam_setcred()`.

I am reporting the error here (not with OpenSSH), since nearly-identical PAM configs still work as expected, making me think it's something to do with how `pam_exec.so` is handled.

For a minimal example, this config _should_ always grant access immediately (no prompts or anything):
```
#%PAM-1.0

auth     requisite                      pam_faillock.so preauth
auth     [success=1 default=ignore]     pam_exec.so /bin/true
auth     [default=die]                  pam_faillock.so authfail
auth     required                       pam_faillock.so authsucc

# Standard rules, replacing the base-auth with our own above.
#auth      include    base-auth
account   include    base-account
password  include    base-password
session   include    base-session
```

_Instead,_ when calling `sshd -d` for debug output, you see:
```
[...]
Postponed keyboard-interactive for root from 10.89.1.18 port 60280 ssh2 [preauth]
debug1: do_pam_account: called
Accepted keyboard-interactive/pam for root from 10.89.1.18 port 60280 ssh2
debug1: monitor_child_preauth: user root authenticated by privileged process
debug1: monitor_read_log: child log fd closed
debug1: PAM: establishing credentials
PAM: pam_setcred(): Permission denied
debug1: do_cleanup
exit code: 0
```

For reference, the sshd callstack [starts here](https://github.com/openssh/openssh-portable/blob/V_9_1_P1/sshd.c#L2290) and [goes here](https://github.com/openssh/openssh-portable/blob/V_9_1_P1/auth-pam.c#L1100). It doesn't appear to change based on the PAM config.

Replacing the auth rules above with these works exactly as expected. You enter a password. If incorrect, faillock records it and you are denied access. If correct, authsucc clears your failures and you're granted access.
```
auth     requisite                      pam_faillock.so preauth
auth     [success=1 default=ignore]     pam_unix.so
auth     [default=die]                  pam_faillock.so authfail
auth     required                       pam_faillock.so authsucc
```

Then to make matters more confusing, these auth rules also work as expected. When you remove the `die`, every login attempt is granted immediately.
```
auth     requisite                      pam_faillock.so preauth
auth     [success=1 default=ignore]     pam_exec.so /bin/true
auth     required                       pam_faillock.so authfail
auth     required                       pam_faillock.so authsucc
```

Is this is an error in my configs, a known limitation (didn't see it in the manpages), or a bug?

I have a little repo I put together with a Dockerfile and several different configurations testing the various failure modes. I'll upload that momentarily.

Edit: Here is the repo: https://github.com/swolebro/debug-linux-pam-583

This uses Alpine v3.17.3 with OpenSSH v9.1p1 and PAM v1.5.2, though I have found the same results when testing with Arch Linux and slightly newer software (OpenSSH v9.3p1 and PAM v1.5.3).

The Dockerfile installs the software, sets dumb passwords for `root` and `user` (either account hits the same error), copies whatever PAM config the `sshd.pam` symlink points at, and kicks off sshd in debug mode. If you use the `compose.yaml`, it'll be listening on localhost:2222.

Configs 01, 02, and 03 are the ones I mention above. I added a few more, with commentary on how they behave in the git log.

**Comment by ldv-alt** [comment]
What happens when `pam_exec.so /bin/true` is replaced with `pam_permit.so`?

**Comment by swolebro** [comment]
`pam_permit.so` will grant immediate access, the way you'd expect `pam_exec.so /bin/true` to do.

Config file for reference: https://github.com/swolebro/debug-linux-pam-583/blob/master/08-like-01-but-pam_permit.pam

**Comment by ldv-alt** [comment]
If `pam_permit.so` grants access while `pam_exec.so /bin/true` doesn't, it most likely means that openssh has configured a sandbox that disallows `execve` syscall.

**Comment by swolebro** [comment]
Hm, except when I replace the `[default=die]` from below the jump with a `required` (third config in the first post), then `pam_exec.so /bin/true` works (ie. skips over the authfail, uses authsucc to clear the user's faillock file, and lets you on).

Using an actual script (with logging and such), it's easy to see that the script gets called and that the return code gets used. I'm only using `true` to remove any doubts of it being a problem in my script.

**Comment by t8m** [comment]
pam_exec does not execute processes in the pam_sm_setcred() call, it just returns PAM_IGNORE. That would not be a problem with other pam applications except with sshd (if I remember correctly) which runs the authentication in a different process than the setcred call which means the _frozen stack_ feature of libpam will not work correctly.

Please try this:
```
auth     requisite                      pam_faillock.so preauth
auth     [success=1 ignore=1 default=ignore]     pam_exec.so /bin/true
auth     [default=die]                  pam_faillock.so authfail
auth     required                       pam_faillock.so authsucc
```
