### ISSUE TITLE
(Pop!_os) Cannot log in

### ISSUE THREAD

**Issue by Cobra00747** [linux-pam/linux-pam#585]
(Pop!_os)
I was setting up Pam, libpam, and pkcs on my PC. The guide I was using was outdated so it was taking longer than I thought, so I had to work. I shut down mid setup and when I powered it back up I couldn't log in because it wouldn't let me type a password. 
I tried recovery mode however that's bugged or something, and tty, what appeared to be my best hope, is also bugged. No matter what I type, I get this:

![1685848421969-1741161576](https://github.com/linux-pam/linux-pam/assets/121925475/d3ad5f69-f24b-4d63-a2a2-870dbddd3c1f)

It doesn't let me type in my password here either.
Reinstalling would be too much of a hassle at the moment so I'd rather forego that, for the time being. If you know of any ways I can resolve this and log in, please drop it in the comments.

Yes, I'm not a Linux pro.
No, I didn't make a backup.

Thank you for your time.

**Comment by Abdillah** [comment]
Use Live USB to restore PAM configuration or continue your effort. I think that is something expected when you set your config wrong / incomplete.

**Comment by thkukuk** [comment]
As Abdillah wrote, use a Live USB system, mount your root and restore your PAM configuration or create a new, working one. There is no other way.
