### ISSUE TITLE
SEGV on unknown address 0x000000000000

### ISSUE THREAD

**Issue by ToxyFlog1627** [linux-pam/linux-pam#589]
When I'm using PAM with `-fsanitize=address` as root I get the following error:
```
AddressSanitizer:DEADLYSIGNAL
=================================================================
==13914==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffe4e10a1a0 sp 0x7ffe4e109918 T0)
==13914==Hint: pc points to the zero page.
==13914==The signal is caused by a READ memory access.
==13914==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x7f7ea32d4b04  (/lib64/security/pam_unix.so+0x5b04)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>) 
==13914==ABORTING
```
It even happens when I run examples (tested on `examples/xsh.c`).
It appears to be somewhere is `pam_authenticate`.

It works fine if I run it as a normal user. Is it wrong to use PAM as root?

**Comment by t8m** [comment]
Could you please add debugging information (-g) in the build so we get better backtrace?

**Comment by ToxyFlog** [comment]
Does your answer mean you can't reproduce it? Unfortunately, I don't have access to my machine for 2 more weeks :/

**Comment by ToxyFlog1627** [comment]
Does this mean you can't reproduce it? I don't have access to that machine for 2 more weeks :/
