### ISSUE TITLE
Is it possible to force a user to change their password on first login by configuring a pam custom policy.

### ISSUE THREAD

**Issue by muyu888** [linux-pam/linux-pam#592]
Is it possible to force a user to change their password on first login by configuring a pam custom policy.
Prerequisite:
The root, secadm and auditadm users have been created and initialized with passwords during system installation, while the rest of the ordinary users need to be created by the root user and have their passwords changed by the secadm user before they can log in.
The above prerequisite is the equalization of the separation of powers function, has been realized

**Comment by thkukuk** [comment]
Question answered, no more questions, closing.
