### ISSUE TITLE
pam_env(8) is wrong about ~/.pam_environment

### ISSUE THREAD

**Issue by lahwaacz** [linux-pam/linux-pam#6]
[pam_env(8)](http://man7.org/linux/man-pages/man8/pam_env.8.html) says:

> user_envfile=filename
>           Indicate an alternative .pam_environment file to override the
>           default.The syntax is the same as for /etc/environment. The
>           filename is relative to the user home directory. This can be
>           useful when different services need different environments.

But that is not what the code does. The `user_env_file` is parsed with [_parse_config_file](https://github.com/linux-pam/linux-pam/blob/5b4c4698e8ae75093292f49ee6456f85f95a3d5d/modules/pam_env/pam_env.c#L826), same as the [conf_file](https://github.com/linux-pam/linux-pam/blob/5b4c4698e8ae75093292f49ee6456f85f95a3d5d/modules/pam_env/pam_env.c#L793) (i.e. `/etc/security/pam_env.conf` by default). `/etc/environment` is parsed with [_parse_env_file](https://github.com/linux-pam/linux-pam/blob/5b4c4698e8ae75093292f49ee6456f85f95a3d5d/modules/pam_env/pam_env.c#L796).

**Comment by glensc** [comment]
@lahwaacz never link to branch when referring to code lines by their numbers. use permalinks (git tag or git commit ref instead). edit your post to fix  that.

**Comment by lahwaacz** [comment]
The links still pointed where inteded, nevertheless they're permalinks now.

**Comment by glensc** [comment]
yes, they may not be so over the time passes.

**Comment by ChALkeR** [comment]
Previous discussion: https://lists.fedoraproject.org/archives/list/pam-developers@lists.fedorahosted.org/thread/GK7PNA3ZBNJMI2LJFAAKXZZ23L2QMW52/

**Comment by ChALkeR** [comment]
Also related: https://answers.launchpad.net/ubuntu/+source/pam/+question/159345 (inability to add variables with spaces).

**Comment by lilydjwg** [comment]
There is still a wrong description in the manpage:

https://github.com/linux-pam/linux-pam/blob/0e9b286afe1224b91ff00936058b084ad4b776e4/modules/pam_env/pam_env.8.xml#L231-L233

**Comment by lahwaacz** [comment]
This has been fixed in https://github.com/linux-pam/linux-pam/commit/f83fb5f25263356391d71da595def409e8dd90f7.
