### ISSUE TITLE
pam_strerror() fail to localize strings when linux-pam is installed into non-standard prefix (missing bindtextdomain() call)

### ISSUE THREAD

**Issue by trofi** [linux-pam/linux-pam#602]
In https://github.com/NixOS/nixpkgs/issues/249010 rypervenche nitoced that in `nixpkgs` `su` lacks expected translation of a login prompt.

`nixpkgs` installs every package into it's own unique prefix and never overlays directoryes from different packages. As a result for `su` we have at least 3 locale directories:
- `shadow`: /nix/store/ymcln55n92xm25sk2pipqbcp5xghwc3j-shadow-4.13/share/locale/
- `glibc`: /nix/store/ibp4camsx1mlllwzh32yyqcq2r2xsy1a-glibc-2.37-8/share/locale
- `linux-pam`: /nix/store/k1lvsb3vyw2ijk9naamnay5nwc4mibda-linux-pam-1.5.2/share/locale

To find the locale one need to call `bindtextdomain()` or rely on a default.
- `shadow` calls `(void) bindtextdomain (PACKAGE, LOCALEDIR);` in `src/su.c` (ok)
- `glibc` uses default textdomain search path within `glibc` itself, no need to bind it explicitly (ok)
- `linux-pam`: does not bind it's directory anywhere (bad)

At least `glibc` runs `bindtextdomain ()` under a lock, thus should be safe to run it in `pam_start()` or `pam_strerror()`.

WDYT of adding a form of `(void) bindtextdomain (PACKAGE, LOCALEDIR);` call for `linux-pam`-specific `LOCALEDIR` as well? Other libraries do it in library initialization routines in static constructor or at first session start.

Thanks!

**Comment by trofi** [comment]
Possible naive solution: https://github.com/linux-pam/linux-pam/pull/604

**Comment by ldv-alt** [comment]
Implemented in #604
