### ISSUE TITLE
No way to tell if a service passed to pam_start is missing/not present

### ISSUE THREAD

**Issue by pontaoski** [linux-pam/linux-pam#610]
Expected behaviour:
- `pam_start` fails with an error code indicating that the service passed in does not exist
Actual behaviour:
- `pam_start` succeeds
- `pam_authenticate` fails with generic PAM_AUTH_ERR which means application nor user can tell that the service passed in is faulty

**Comment by ldv-alt** [comment]
When the configuration corresponding to the service name does not exist, PAM falls back to "other" default "service", e.g. /etc/pam.d/other; this is intended behavior.
