### ISSUE TITLE
PAM module always send incorrect password to radius server for authentication

### ISSUE THREAD

**Issue by dayDPTR** [linux-pam/linux-pam#639]
Hi experts,

I met one issue described [here](https://github.com/FreeRADIUS/pam_radius/issues/82): PAM module always send incorrect password to radius server for authentication.

Could you help look into the issue ?

Thanks in advance.

**Comment by ldv-alt** [comment]
Sorry, Linux-PAM doesn't send anything to any radius server, so it's outside the scope of this project.
