### ISSUE TITLE
Follow NIST guidelines for quantity of password attemps

### ISSUE THREAD

**Issue by es20490446e** [linux-pam/linux-pam#641]
At [faillock.conf](https://github.com/linux-pam/linux-pam/blob/master/modules/pam_faillock/faillock.conf) we could set `deny = 10`, so it follows [NIST guidelines](https://pages.nist.gov/800-63-3/sp800-63b.html):

> Allow at least 10 entry attempts for authenticators requiring the entry of the authenticator output by the user.

If you agree I can make a pull request.

**Comment by ldv-alt** [comment]
I don't think we can change the defaults without breaking backwards compatibility.

**Comment by ldv-alt** [comment]
You're suggesting to change the default for `deny=` option, aren't you?
Please have a look at an earlier discussion on this topic at #420.
