### ISSUE TITLE
Add an example of using groups in access.conf to permit access

### ISSUE THREAD

**Issue by cubranic** [linux-pam/linux-pam#65]
It would be useful to have an example in access.conf(5) man page of using a group to permit access. E.g.,:

```xml
   <para>
      Members of group <emphasis>wheel</emphasis> should be allowed to get access
      from all sources.
    </para>
    <para>+:(wheel):ALL</para>
```

**Comment by oxr463** [comment]
@cubranic where is this snippet from?

**Comment by cubranic** [comment]
I wrote it a year and a half ago, so my memory is a bit hazy, but I think I wrote it myself, just mimicking the syntax and style from the rest of the docs.

**Comment by oxr463** [comment]
@cubranic this has been added. Please review my PR when you get a chance.

**Comment by cubranic** [comment]
Added, thanks!
