### ISSUE TITLE
Clarify pam_wheel behaviour when run from a remote agent and there is no controlling terminal

### ISSUE THREAD

**Issue by ikerexxe** [linux-pam/linux-pam#666]
Hi experts,

I will need some help from you to clarify a behaviour and set a standard for all distributions. One of our users is complaining that there are different behaviours when pam_wheel is run from a remote agent and there is no controlling terminal. I think it's easier to understand the problem if I provide the reproduction steps and then I explain the difference in behaviour.

Steps:
1. Create "testuser" user and set password
2. Configure "testuser" user in sudoers to be able to sudo without password:
```
...
testuser        ALL=(ALL)    NOPASSWD: ALL
...
```

3. Configure `/etc/pam.d/sudo` to verify the account based on group membership.
Replace `#account    include      system-auth` by `account    sufficient   pam_wheel.so trust group=users debug`

4. Add the below line on `/etc/pam.d/su`
```
...
account    sufficient   pam_wheel.so trust group=users debug
...
```

5. Add user to users group: usermod -G users testuser

6. ssh into the machine as "testuser" and run `sudo su`

There are three different behaviours:
1. Before https://github.com/linux-pam/linux-pam/commit/9091ea1d81e85f49a221b0325d27b22ce69e444a pam_wheel fails with `who is running me?`
2. After https://github.com/linux-pam/linux-pam/commit/9091ea1d81e85f49a221b0325d27b22ce69e444a and with glibc v2.28 pam_wheel recognizes the user as the one that made the call to `sudo`.
3. After https://github.com/linux-pam/linux-pam/commit/9091ea1d81e85f49a221b0325d27b22ce69e444a and with glibc v2.34 pam_wheel recognizes the user as the one that made the call to `su`, or in other words, root.

The difference in behaviour between 2 and 3 is due to `getlogin()` changing its return value from the user that made the call, to NULL. The latter being the correct behaviour. As a reference from the man page: getlogin() returns a pointer to a string containing the name of the user logged in on the controlling terminal of the process, or a null pointer if this information cannot be determined. If NULL is returned, then the fallback implemented in https://github.com/linux-pam/linux-pam/commit/9091ea1d81e85f49a221b0325d27b22ce69e444a takes action and [PAM_RUSER](https://github.com/linux-pam/linux-pam/blob/master/doc/adg/Linux-PAM_ADG.xml#L391) is used to decide which user called (root).

As you can see, those differences in behaviour are non-consistent and even contradictory, making it impossible for a system administrator to use them. That's why I come here to decide which should be the correct behaviour (if any), and to provide a proper solution to this problem.

Original discussion for further reference: https://issues.redhat.com/browse/RHEL-16727

**Comment by ldv-alt** [comment]
> The difference in behaviour between 2 and 3 is due to `getlogin()` changing its return value from the user that made the call, to NULL. The latter being the correct behaviour. As a reference from the man page: getlogin() returns a pointer to a string containing the name of the user logged in on the controlling terminal of the process, or a null pointer if this information cannot be determined.

As far as I remember, getlogin implementation from glibc on linux hasn't changed, it primarily uses /proc/self/loginuid, and all the rest might come into play only when loginuid is not initialized, which shouldn't be the case nowadays.  That is, I'd expect getlogin() to return a string regardless the controlling terminal.

**Comment by ikerexxe** [comment]
I added additional debugging messages and `pam_modutil_getlogin()` returns NULL when there isn't any controlling terminal. This is not the case when there is a controlling terminal. So maybe the difference comes from this wrapper, but I doubt it.

**Comment by ldv-alt** [comment]
FWIW, `pam_modutil_getlogin()` is essentially `getlogin()`.

**Comment by ikerexxe** [comment]
There are some subtle differences, but yeah, `pam_modutil_getlogin()` is a wrapper for `getlogin()`.

Still, I would like to insist that `getlogin()` returns different values depending on the version of glibc used. This can be easily checked with RHEL8 (or Centos Stream8) and RHEL9 (Centos Stream9).

**Comment by ldv-alt** [comment]
If I remember correctly, `getlogin()` started to use `/proc/self/loginuid` as the primary source since glibc-2.12.
The reason why `pam_wheel.so` has `use_uid` option in the first place is that `getlogin()` without `/proc/self/loginuid` support was inherently unreliable.

Could you check, please, whether `/proc/self/loginuid` is properly initialized before `pam_modutil_getlogin()` is invoked in those environments where you experience issues with `pam_wheel.so`?

**Comment by ikerexxe** [comment]
Ok, I see the problem. RHEL/CentOS Stream 9 are using Linux-PAM v1.5.1 and it misses this change https://github.com/linux-pam/linux-pam/commit/244b46908df930626535c0cd7c2867407fe8714a, so we are relying on the old implementation from utmp instead of `getlogin()`.

**Comment by ldv-alt** [comment]
OK, is there anything we could do about it upstream?

**Comment by ikerexxe** [comment]
No, I don't think so. Sorry, I should have closed this ticket when I posted my previous comment.
