### ISSUE TITLE
pam_timestamp_check: potential null pointer dereference on error path

### ISSUE THREAD

**Issue by Fmiard** [linux-pam/linux-pam#677]
Hi:
In the code on line 816 of the pam_timestamp.c file, if the pointer variable pwd is null, then a null pointer dereference problem occurs on lines 821 and 825.
To avoid this problem, I think we should return the value of the variable retval directly after determining that pwd is null, please review this modification to see if it makes sense, and if so I will create a commit. Thank you very much! 
![9 M)}Y0MJIL@RR@K2G96)0A](https://github.com/linux-pam/linux-pam/assets/154431208/2b2517c0-e232-4add-a16a-dfa17be04722)

**Comment by stoeckmann** [comment]
Agreed. You can reproduce this by renaming `/etc/passwd` temporarily or by removing the entry of the calling user before calling `pam_timestamp_check`.

**Comment by Fmiard** [comment]
@stoeckmann Thank you very much for your guidance!

**Comment by Fmiard** [comment]
I have created a pull request on this issue, please review it to see if it is correct.Thanks!
https://github.com/linux-pam/linux-pam/pull/679
