### ISSUE TITLE
seems pam_env.so always return PAM_IGNORE?

### ISSUE THREAD

**Issue by mashuai191** [linux-pam/linux-pam#680]
hi there,
i have below config. i want to load the env variables(e.g. TEST_VAR) from /etc/test_environment into global env then i assume i can use the TEST_VAR in later steps. but,
1. add 'debug' to pam_env.so has no effect as i didn't see any output in /var/log/secure
2. the env variable TEST_VAR seems not set at all.
3. looks pam_env.so always return PAM_IGNORE as i didn't see "111111111111111111111" in logs.

anyone can help on this case? Thanks in advance for any help or comments!

my custom PAM file:
...
auth  [ignore=1 default=ignore]   pam_env.so debug  envfile=/etc/test_environment readenv=1 user_readenv=1
auth  required   pam_echo.so "111111111111111111111"
auth  required   pam_echo.so "222222222222222222222"
auth    [success=done auth_err=die ignore=ignore]    pam_google_authenticator.so  nullok   noskewadj  secret=/etc/otp/secrets/${TEST_VAR}/secret debug
...

cat /etc/test_environment:
TEST_VAR=ACCESS-QA\aduser1

**Comment by mashuai191** [comment]
# rpm -qa | grep pam
nss-pam-ldapd-0.9.9-5.el8.x86_64
systemd-pam-239-74.el8_8.5.x86_64
pam-1.3.1-25.el8.x86_64

**Comment by ldv-alt** [comment]
> 3. looks pam_env.so always return PAM_IGNORE as i didn't see "111111111111111111111" in logs.
> my custom PAM file:
> `auth [ignore=1 default=ignore] pam_env.so debug envfile=/etc/test_environment readenv=1 user_readenv=1`

Are you aware of the meaning of `default=ignore` in this example?

**Comment by mashuai191** [comment]
i understand that if pam_env.so return PAM_IGNORE, it go with ignore=1, and that's why "111111111111111111111" was not seen in logs.
if it go with default=ignore, the "111111111111111111111" should be seen.

**Comment by ldv-alt** [comment]
> hi there, i have below config. i want to load the env variables(e.g. TEST_VAR) from /etc/test_environment into global env then i assume i can use the TEST_VAR in later steps. but,
> 
>     1. add 'debug' to pam_env.so has no effect as i didn't see any output in /var/log/secure

The effect of `debug` option is that `pam_env.so` sends some diagnostic messages to syslog.
In your case, for example, there are going to be `pam_putenv("TEST_VAR=ACCESS-QA\aduser1")` messages there, please check the appropriate syslog file.

>     2. the env variable TEST_VAR seems not set at all.

It is set not by `pam_authenticate` but by `pam_setcred`.

>     3. looks pam_env.so always return PAM_IGNORE as i didn't see "111111111111111111111" in logs.

When invoked by `pam_authenticate`, `pam_env.so` always returns `PAM_IGNORE`.
`pam_env.so` does it job for the auth stack only when `pam_setcred` is invoked.

However, after `pam_authenticate` the pam auth stack is already frozen, so during `pam_setcred` the modules are being called in the same order as they were called during `pam_authenticate`.

This essentially means that there is no way to take `pam_env.so` return value into account when configuring the pam auth stack.

**Comment by mashuai191** [comment]
i know only PAM module, don't know the pam_setcred.
do you mean there is no way to load a custom env variable(in this case it is TEST_VAR) into PAM stack for use?

**Comment by ldv-alt** [comment]
Note that PAM `auth` stack controls both `pam_authenticate` and `pam_setcred`.
`pam_env.so` does nothing at `pam_authenticate` stage, so given that `pam_authenticate` is the first stage, `pam_env.so` cannot be used to export environment variables for use by `pam_authenticate`.

**Comment by thkukuk** [comment]
I created PR#782 to enhance the documentation with this informations.
