### ISSUE TITLE
pam_access: add quiet_log option

### ISSUE THREAD

**Issue by voegelas** [linux-pam/linux-pam#706]
It would be useful if pam_access had a `quiet_log` option similar to pam_exec. Currently, pam_access logs an "access denied" message to the syslog if pam_access is used to skip other modules like in the example below. See also the [Arch Linux wiki](https://wiki.archlinux.org/title/Google_Authenticator#Request_OTP_only_when_connecting_from_outside_your_local_network) for an example.

```
auth [success=1 default=ignore] pam_access.so noaudit quiet_log accessfile=/etc/security/access-local.conf
auth required pam_google_authenticator.so
auth substack password-auth
```

**Comment by voegelas** [comment]
I've got the patch voegelas/linux-pam@c1d94cdc5fbc17f21fc3aaec2e45a3404573903a and could create a pull request if there is interest in such an option.

**Comment by ldv-alt** [comment]
Feel free to submit a PR.
