### ISSUE TITLE
Spurious "Warning: your password will expire in 0 days" after update to 1.6.0

### ISSUE THREAD

**Issue by VorpalBlade** [linux-pam/linux-pam#743]
After updating to pam 1.6.0 I'm getting spurious "Warning: your password will expire in 0 days." from su and login (not sudo though!).

It happens when the password change date (third field) is empty in /etc/shadow. According to man shadow(5) this should be explicitly allowed "An empty field means that password aging features are disabled.". I have a custom automated config management tool, where I never implemented support for putting anything in that third column (since it was optional according to the man page), which is likely the reason I ran into this.

My PAM config is Arch Linux default (apart from also adding fprintd support for graphical login and sudo, no changes to su/login or their included files).

Based on grep the string "Warning: your password will expire in" comes from pam_unix.so. So something is buggy in pam it seems.

I don't know if it is a Arch pam configuration bug or an upstream bug.

Downstream Arch Linux bug report: https://gitlab.archlinux.org/archlinux/packaging/packages/pam/-/issues/2

## Steps to reproduce:

1. Create an user with empty password change date in /etc/shadow. E.g. `root:PASSWORD-HASH-HERE:::::::`
2. su to that user, or login on the VT (outside X/Wayland) as that user
3. Observe incorrect warning

**Comment by stoeckmann** [comment]
I have created PR https://github.com/linux-pam/linux-pam/pull/744 which fixes the problem. Fortunately it is really "just" a warning but a regression nonetheless.

Thanks for your detailed description and how to reproduce the problem!
