### ISSUE TITLE
Builds but fails to install with make install DESTDIR=

### ISSUE THREAD

**Issue by ColumPaget** [linux-pam/linux-pam#765]
using gcc 13.2.0, gnu make 4.4.1, libtool 2.4.7

pam seems to build correctly, and will install with "make install". However, when trying to install to a DESTDIR for packaging the following errors occur:

e.g. for make install DESTDIR="/tmp/install"

libtool:   error: error: cannot install 'libpam_misc.la' to a directory not ending in //lib

Making install in libpam_misc
make[1]: Entering directory '/distro/builds/pam-1.6.0.build/libpam_misc'
make[2]: Entering directory '/distro/builds/pam-1.6.0.build/libpam_misc'
 /bin/mkdir -p '/tmp/install//lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libpam_misc.la '/tmp/install//lib'
libtool:   error: error: cannot install 'libpam_misc.la' to a directory not ending in //lib

Not sure, but it seems to me that somewhere an extra '/' is being appended to DESTDIR and upsetting libtool.

**Comment by ldv-alt** [comment]
Are you trying to build from a released tarball or from git repository?
What are the options being passed to configure?

**Comment by ColumPaget** [comment]
Hi, I'm building from release tarballs from github. I've had this happen with just './configure --prefix'. I've tried building both in-source and out-of-source.

**Comment by ColumPaget** [comment]
In order to check the issue isn't localized to the LFS distro I was building under, I've tried to build under linux mint. I took a tarball from the github releases page, and built with an out-of tree build using "configure --prefix=/".  The same issue occurs. The compiler this time is "gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0" make is "GNU Make 4.3" libtool is "libtool (GNU libtool) 2.4.6".

**Comment by ldv-alt** [comment]
Looks like argument to `--prefix` option shouldn't end with `/`.

**Comment by ColumPaget** [comment]
That's really odd, every other program I've ever compiled supported a prefix of '/'? How does one specify a 'root prefix', is it with "configure --prefix="" ? If so, that solves my problem, but isn't this really non-standard?

**Comment by ldv-alt** [comment]
We have a special handling for --prefix=/usr, which is also the default, but besides that I don't think Linux-PAM is any different from other projects that use libtool.

**Comment by ColumPaget** [comment]
well, it's the only thing I've ever encountered that won't build with ' configure --prefix=/ ', but I can confirm ' configure --prefix="" ' works.
