### ISSUE TITLE
Suspicious places in the source code

### ISSUE THREAD

**Issue by Yugend** [linux-pam/linux-pam#769]
Hello guys!

I was looking through the source code of util-linux and found a few suspicious places.

1. **[modules/pam_xauth/pam_xauth.c, line 654](https://github.com/linux-pam/linux-pam/blob/1e2c6cecf81dcaeea0c2c9d37bc35eea120cd77d/modules/pam_xauth/pam_xauth.c#L654).** I think, 'cookiefile' might be NULL in some situations, since memory is allocated for it using strdup().
2. **[modules/pam_unix/support,c, line 319](https://github.com/linux-pam/linux-pam/blob/1e2c6cecf81dcaeea0c2c9d37bc35eea120cd77d/modules/pam_unix/support.c#L319).** There is NULL check for 'failure-user' in this line. But if 'failure->user' is NULL, anyway, there is an attempt to output it. As far as I know, this can lead to undefined behavior.
3. **[modules/pam_unix/support.c, line 837](https://github.com/linux-pam/linux-pam/blob/1e2c6cecf81dcaeea0c2c9d37bc35eea120cd77d/modules/pam_unix/support.c#L837).** The situation is similar as in the previous paragraph.
4. And the most strange thing for me is in **[modules/pam_timestamp/pam_timestamp.c, line 854](https://github.com/linux-pam/linux-pam/blob/1e2c6cecf81dcaeea0c2c9d37bc35eea120cd77d/modules/pam_timestamp/pam_timestamp.c#L854).** The first 'do-while' loop have no 'while' operator.. I tried very hard to figure it out, but I couldn't.

Perhaps there is some sense in all this, but I did not understand it. Or maybe I was wrong and everything is fine. In that case, I'm sorry to bother you and I'll be glad if you tell me where I was wrong.

**Comment by cgzones** [comment]
The first three issues should be resolved by #770.
The associated `while` operator of the fourth issue is here:

https://github.com/linux-pam/linux-pam/blob/1e2c6cecf81dcaeea0c2c9d37bc35eea120cd77d/modules/pam_timestamp/pam_timestamp.c#L908

**Comment by Yugend** [comment]
Oh, you`re right, the loop is ok. The problem is with my syntax highlighting, it connects braces incorrectly.

Thank you for the explanation!
