### ISSUE TITLE
missing include in modules/pam_unix/support.c

### ISSUE THREAD

**Issue by xiao1wen2** [linux-pam/linux-pam#772]
support.c: In function '_unix_getpwnam':
support.c:386:23: warning: implicit declaration of function 'yp_get_default_domain' [-Wimplicit-function-declaration]
  386 |                 len = yp_get_default_domain(&domain);
      |                       ^~~~~~~~~~~~~~~~~~~~~
support.c:387:28: error: 'YPERR_SUCCESS' undeclared (first use in this function); did you mean 'PAM_SUCCESS'?
  387 |                 if (len == YPERR_SUCCESS) {
      |                            ^~~~~~~~~~~~~
      |                            PAM_SUCCESS
support.c:387:28: note: each undeclared identifier is reported only once for each function it appears in
support.c:388:31: warning: implicit declaration of function 'yp_bind' [-Wimplicit-function-declaration]
  388 |                         len = yp_bind(domain);
      |                               ^~~~~~~
support.c:391:29: warning: implicit declaration of function 'yp_match'; did you mean 'rpmatch'? [-Wimplicit-function-declaration]
  391 |                         i = yp_match(domain, "passwd.byname", name,
      |                             ^~~~~~~~
      |                             rpmatch
support.c:393:25: warning: implicit declaration of function 'yp_unbind' [-Wimplicit-function-declaration]
  393 |                         yp_unbind(domain);
      |                         ^~~~~~~~~
make[3]: *** [Makefile:909: support.lo] Error 1
make[3]: Leaving directory '/apps/Linux-PAM-1.6.0/modules/pam_unix'
make[2]: *** [Makefile:508: all-recursive] Error 1
make[2]: Leaving directory '/apps/Linux-PAM-1.6.0/modules'
make[1]: *** [Makefile:508: all-recursive] Error 1
make[1]: Leaving directory '/apps/Linux-PAM-1.6.0'
make: *** [Makefile:438: all] Error 2

**Comment by ldv-alt** [comment]
pam_unix/support.c contains
```
#ifdef HAVE_NIS
#include <rpcsvc/ypclnt.h>
#endif
```
and that should be enough.

**Comment by stoeckmann** [comment]
> and that should be enough.

The yp functions are searched in system libraries. If they are found, the `HAVE_` defines are set
If headers are not found, `WITH_NIS` is set to 0.

Unfortunately the pam_unix support.c code checks the `HAVE_` defines without checking for `WITH_NIS` as well.

@xiao1wen2 could it be that you are lacking the header files of libnsl? Which distribution do you use and have you installed the -dev packages?
