### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by mani3029** [linux-pam/linux-pam#774]
Hi Team,
Released 1.6.0 code compilation fails due to missing header files in pam_namespace.c (https://github.com/linux-pam/linux-pam/blob/v1.6.0/modules/pam_namespace/pam_namespace.c), below is the error
`pam_namespace.c: In function 'process_line':
pam_namespace.c:649:41: error: 'SIZE_MAX' undeclared (first use in this function); did you mean 'SSIZE_MAX'?
         if (count > UINT_MAX || count > SIZE_MAX / sizeof(uid_t)) {
                                         ^~~~~~~~
                                         SSIZE_MAX
pam_namespace.c:649:41: note: each undeclared identifier is reported only once for each function it appears in
Makefile:796: recipe for target 'pam_namespace.lo' failed
make[6]: *** [pam_namespace.lo] Error 1
`

Changes have been pushed in master branch .
https://github.com/linux-pam/linux-pam/commit/cc9d40b7cdbd3e15ccaa324a0dda1680ef9dea13
When can we expect next version release with above code inclusion ?

**Comment by mani3029** [comment]
hi Team any input on this ?

**Comment by mani3029** [comment]
hi team any update ?

**Comment by thkukuk** [comment]
Updates will be made if somebody has time and all regressions are fixed or a serious issue is found (compile problems for a few people easy to fix themself are not serious issues). For the time being: take the patch and apply it locally to compile Linux-PAM.

**Comment by ldv-alt** [comment]
I'd like to sort out #758 before the next release.

**Comment by thkukuk** [comment]
I agree, we should do that now.

**Comment by ikerexxe** [comment]
Sounds good to me

**Comment by stoeckmann** [comment]
I fully agree as well.
