### ISSUE TITLE
undefined symbol: pam_get_use

### ISSUE THREAD

**Issue by Qintiy** [linux-pam/linux-pam#801]
Hello,
I am new to this pam stuff and was asking on the site of service I want to use and their response was we don't give support to think like pam. I am trying to connect openvpn to privacyidea for authentication of users but I ran into a wall if I can say like this.

when I check the logs of pam I get
`openvpn[371]: PAM unable to dlopen(/lib64/security/pam_privacyidea.so): /lib64/security/pam_privacyidea.so: undefined symbol: pam_get_user
openvpn[371]: PAM adding faulty module: /lib64/security/pam_privacyidea.so`

I googled a lot and there is no answer for this. Is anyone able to help me or should I give up on the privacyidea and pam.

**Comment by ldv-alt** [comment]
Please note that `pam_get_user` is provided by libpam - the very library that performs the loading of PAM modules.

You must be doing something really odd, like linking with libpam statically.

**Comment by ldv-alt** [comment]
There is no need to use full path in pam.d config files.  As you can see, other modules are listed without a full path.
Also, the whole config example is unnecessarily too complicated.

**Comment by ldv-alt** [comment]
You must be misreading the instruction or trying to follow the wrong instruction. There is no issue with pam itself, so there is nothing we can do.
