### ISSUE TITLE
libpam_misc.so has rpath even configured with --disable-rpath

### ISSUE THREAD

**Issue by xry111** [linux-pam/linux-pam#809]
libpam_misc.so is linked with rpath and flagged by checksec.sh.

It seems hardcoded in Makefile.in generated by automake:

```make
libpam_misc.la: $(libpam_misc_la_OBJECTS) $(libpam_misc_la_DEPENDENCIES) $(EXTRA_libpam_misc_la_DEPENDENCIES) 
    $(AM_V_CCLD)$(libpam_misc_la_LINK) -rpath $(libdir) $(libpam_misc_la_OBJECTS) $(libpam_misc_la_LIBADD) $(LIBS)
```

Is it intended?

**Comment by ldv-alt** [comment]
This normally shouldn't end up with a rpath in installed binaries.

**Comment by xry111** [comment]
Hmm if I run `autoreconf -fi` before building the package, the rpath is removed by libtool.

I'm building on a custom distro w/o lib64 thus I'm using `--libdir=/usr/lib`.  Removing this option also gets rid of rpath but I just need this option...

`autoreconf -fi` updates `m4/libtool.m4` and changes `sys_lib_dlsearch_path_spec`.

**Comment by ldv-alt** [comment]
The build system was changed from autotools to meson, closing this issue.
