### ISSUE TITLE
The configuration order causes SSH to log in with any password

### ISSUE THREAD

**Issue by Opanma** [linux-pam/linux-pam#833]
`View the current operating system version and kernel version`
![image](https://github.com/user-attachments/assets/0a91aa0e-414e-4f35-8305-081f146a7525)
`View the current PAM version`
![image](https://github.com/user-attachments/assets/c12b90ef-1ef6-4de7-838c-b30cdfcef6f1)
`Modify /etc/pam.d/common-auth`
`auth sufficient pam_faillock.so authsucc audit deny=10 unlock_time=900`
![image](https://github.com/user-attachments/assets/3f86e986-5a77-47c7-8abb-eb6dee958ff5)
`Restart sshd to enable root user to log in with any password`
![image](https://github.com/user-attachments/assets/2face360-9fdc-4907-8109-a6945f74684a)

**Comment by thkukuk** [comment]
The system behaves the way as you configure it. Why do you expect a password check, if you tell PAM quit the auth stack before it would reach the necessary module?
Please read thepam.conf manual page, especially the section about "sufficient".
