### ISSUE TITLE
There is a problem with the loop condition

### ISSUE THREAD

**Issue by bin-ly** [linux-pam/linux-pam#849]
When entering the loop here, i is equivalent to i-2, and there will be one missing loop. I wonder why the original code was written like this?
![image](https://github.com/user-attachments/assets/8af8ff03-9c9b-4f9d-a469-d978937066a3)

**Comment by bin-ly** [comment]
test result:
![企业微信截图_17301066023659](https://github.com/user-attachments/assets/1e11e3c2-4256-4ae4-a62f-13f8ada9be67)

Modified results
![企业微信截图_17301066498865](https://github.com/user-attachments/assets/0b2061f9-f890-40da-acf2-8d8b2842d23c)

**Comment by ldv-alt** [comment]
As the last item in pamh->env->list[] is always NULL, the index of the last non-NULL item is `pamh->env->requested - 2`.
