### ISSUE TITLE
Unable to cross compile

### ISSUE THREAD

**Issue by Uglymotha** [linux-pam/linux-pam#850]
since switch to meson build system cross compilation fails, because padout is not compiled as a native binary.
Please add 'native : true' to the build config of padout in doc/specs/meson.build:
padout = executable(
  'padout',
  native : true,
  sources: [parse_l, parse_y],
  include_directories: [libpam_inc],
  c_args: [
    '-Wno-unused-function',
    '-Wno-sign-compare',
  ],
  link_args: exe_link_args,
)

**Comment by ldv-alt** [comment]
Would you like to submit a PR?

**Comment by Uglymotha** [comment]
submitted
