### ISSUE TITLE
pam_env conf is badly written. 

### ISSUE THREAD

**Issue by scapjoe** [linux-pam/linux-pam#88]
First, options are case sensitive, and PAM env is conventionally uppercase for variable names. DEFAULT as an option. default=hi is an error.

**Comment by oxr463** [comment]
Pardon my ignorance, but aren't the config files for PAM itself (e.g. `/etc/pam.d/*`), case sensitive also?

Also, uppercase environment variables are normal on UNIX-like systems e.g. EDITOR, SHELL, etc.
