### ISSUE TITLE
Adding pam_setquota

### ISSUE THREAD

**Issue by shartge** [linux-pam/linux-pam#92]
I've "rescued" and "maintained" a [pam_setquota](https://github.com/shartge/pam_setquota) module for several years and use it as locally compiled PAM module on several hosts in production.

But since I only know enough C to be dangerous and adapting and fixing bugs for this module is more than I can handle, it would be nice if it could eventually be included in the main PAM code.

**Comment by t8m** [comment]
This looks like nice idea. Supplying a PR integrating it would help.

**Comment by shartge** [comment]
I'll see what I can do to automakify the code before submitting it.
